apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: true
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
    - hosts:
        - home.elposhox.dev
  ingressClassName: nginx
  rules:
  - host: 'home.elposhox.dev'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homepage
              port:
                number: 80