apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: homepage
    homelab.local/OwnedBy: ElPoshoX

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- cm.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- sa.yaml
- sa-token.yaml
- secret.yaml
- pvc.yaml