apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: homepage
    homelab.local/OwnedBy: ElPoshoX

configMapGenerator:
- name: homepage
  files:
  - files/custom.js
  - files/custom.css
  - files/bookmarks.yaml
  - files/docker.yaml
  - files/kubernetes.yaml
  - files/services.yaml
  - files/settings.yaml
  - files/widgets.yaml

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- sa.yaml
- sa-token.yaml
- secret.yaml
- pvc.yaml
