---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  volumeName: pvc-7f5e1af6-7147-4be6-a7e0-0db4a013bc83
  resources:
    requests:
      storage: 2Gi
