apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homepage-secret
          stringData:
            HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:i7ZOVkwC,iv:HWjnZLZe6UOXFsBhRlkjENW6+glo5FfPJ8opkjjZ8Lk=,tag:KZMIsFdWbKK+wiI4xw7LKg==,type:str]
            HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:JncP5fHz1EbEIIYcoJccNXz0HNYgutaP1ZQ3jVGlQybtBJNgw3/eSFBVX6JS,iv:T6Wy9u9MmJvIUYc4Vml5sxH3Px02lj/wqQCC266lk+k=,tag:MHJAVh1eAAqbhkLza0mSgA==,type:str]
            HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:RA8+d3MbBax6WPV+43ftys5rmE5jgwIhcer955oM0rlkn0LZVtpppNAnNWuFi+w04B8M/fu4pDvy+fwWdysSI45uhtAmcJPn1W6KAXAz3pnnVpllr0eHaF3ZZ1/mnjcepJlwJKcQovhJ6Cy6uIGfcgSHIvtbQPgbdyRa7m9Wz3CAokvIUQV04xcXJTtkXqxi9My/zWkG0wfbBAVO/RH84TSvVQvyxrKEkinLspmPzOUgSwwpxr4aP1Lnoc2yjiNJuIU2OQVGyvbHYfPa4rPTPtiEbU/I0E+Wor+TyvVraMo0N3TGaCemgHNaRrmZFHOQ,iv:PwDmcmvHXowqwe4ufzjCXkAVr148CJSwZiYx/PMZ2rE=,tag:FJCpwvxNuCRiwNh8pz+Yfg==,type:str]
            HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:Rdya0JBroEsNF2SeSe6AOncEBErNUKcKJ+hBvW/RzAFdrPGD4EJYNvrUmI7LtijYDabvM573dOefAwqPos5znfKxO2a3AN5M4fsrXOH7HYpXshDEUvUKxQa8CYtjn6+LJGqGej0mHTfIicN5EDXlJMGOs3e8devikQSgvzHgxn64X/FuXt9HxNAt6QhwXQ8VbxLyLVhkyw25O6RTpGxHeqOtQSNpdsGkGakmx87CUaPVcFARJPrw,iv:bMnVIBaVGvR19fk0KmPfEhEWOEba+9OmZ9HI5T2PiBU=,tag:vkTri2celj9hFsICHwGqag==,type:str]
            HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:sLhr5jtSVovbqC9aEzlyp4Asm/N8z8G9tlrCmRtBjRDd7mLAOP8UqRPzaugmqWvAvjgDRBPA5VNwBCc95sIeO599XLc=,iv:aVYpYQObvQR/qvxjD3H0dXhpvYxAdVUfvJJLFDMD8dQ=,tag:0ev02Y9xDZNd06QiW9QdKA==,type:str]
            HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:CNZLNrkA21CfkBSz2frjRPkKc/iVVtzt/JXa6Yyongg=,iv:vqATKfc+aJ75gkZdOaSUXQito/M7HpIRjRLBz5QKCBc=,tag:KW1YEUpsU63GwRZHoCaU9A==,type:str]
            HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:IstvZsZnUwwkseDKR7XBvlNAvRs9H7zocKgL5nPmZBc=,iv:AvsOpwAkjvn4Pxwzz3vL+p3HtA8ngX/oQSEu7GmmYdw=,tag:Gtb34/l/yqJ11Wni04EQ+w==,type:str]
            HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:0gfqVTyEzdf9rs2tydx43jwAdg/qOQMMTUtAzVRC61c=,iv:QY2ds0uKzz2RjXr0reykMPUcs8VOVFWtqxkG8K/zpE8=,tag:LV5ND6WfL5g9paeoiwJiDw==,type:str]
            HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:IyXj5G3JcAA4RumVen3TG3Ek8fQ1KYC3RaTtuvGxmHM=,iv:FrQ/1Q0YfJHTvOiLuKm7ropbcJrGU54lFmCxBpzTh3s=,tag:k2fzDhjSVLdkZ3u7sFx/zg==,type:str]
            HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:JzEugz8zzcDAddBidcsCLXksir+j+Fksuol56YO6PeE=,iv:1X0eSfmte8jwIJMlh/+jB7294XnmtPE8VlYaJZcLBh8=,tag:tymoX28FeguWw2/XF1s6+Q==,type:str]
            HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:FMCIpxf1n14xPp4O6bQokZ3PeFpxUh5hBC/hJtBEjNuj5E44vshqJA==,iv:vU9n8GLAE7qp2re0PMBvKjoL0gHWmZTgAoAEGEbLNjo=,tag:SRpooHyXzUk75riW5s/1+g==,type:str]
            HOMEPAGE_VAR_UNIFI_USER: ENC[AES256_GCM,data:Wja0Jv2fr4M=,iv:sJgNLA/q7VjSLnkPHOIozBTxZtpZX2/Pq5IL8RDJ54s=,tag:/0LBhAN51Ls3iGu6Wc7fxg==,type:str]
            HOMEPAGE_VAR_UNIFI_PASS: ENC[AES256_GCM,data:6ltFlDrSLfd52CAOOHVkry+21MFCCv32HBYeFwb10UU=,iv:J1XwfxKcAkrquT4fvJyjYTCUuSlRQUXgA81AjH2T4HE=,tag:1BtuwXomr5ZA0kPVOQeKJg==,type:str]
            HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:c6By+amOnHyD9rOCTG6QJPPulTEN6oSA1rcXyBR8849CZ15LUjgQvpe06zVMqz1oUeS1IG1xCKwkz2fuxNKd3C3l,iv:FcNSi788OUATuDZh9Zd1xHJViqCAIcXfZGod4/UB9ZU=,tag:cYTlUwbgLb/ekn8g5sQWPQ==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ0lCQ1h5OVZjV24xUzBh
            VElMYXVrajh0d2EvdHlwUkE3eHFEOHgreTN3CmtlaHQ5TDB0bCthSUV4bkNxczEz
            dkI4cnIwS3Z0bVp5bDdUZ2dXek1Ec1UKLS0tIGkzc0x5N0hVaVhrT25MajQxV3Rz
            NTZxczlCSzlNWW9lRUM3YlF0MVhXYzQKZZl9CnTdZQv4+PLUXoms4IG/1oJqBkX1
            zUQRf9T1QJcgw8T2MUScB7EI0Hft8mHn48c9VpE9gj01l5fcSVAqlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T02:42:51Z"
    mac: ENC[AES256_GCM,data:wcTDNj0pGHoNXYfGpgWtiRwdMk8swp7RpBRX5EpNXt4va2WahgLTVbMxcVuIlmAS0t5VznOKRIGjLHE4wv1SzJbekAJJfyZKGWvmQ4Iq88/MhdaBK7nF10RLsddRpRSOVW7yOpyW7/lK49Iy86eNrS5FJkti6Nn4ccFGJwnaa1c=,iv:cYqmfZVBtTbPszmHZnA0Gnbej9EDAvj0Sat1jnjpKig=,tag:oY++kk5dA8dssHFMa6RgsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
