apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homepage-secret
          stringData:
            HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:q+m3eLnb,iv:QB9C8f2OX0/ByB3FQ5RAncfeUxYCRZdYoYtuAmXphQ0=,tag:tTex70XnoFie4Og3+YeCZw==,type:str]
            HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:XyQ7kdJPZdBRCnd+IvthBx9CTPZOc4hgFQV3dGxWi1A31B787Ix5L6SUuZW2,iv:KSjlpXSa01AxMdLOQXxc3KS0h9v0oKiE0W0IE27fIu0=,tag:M6aywQqmpRedCUWlOn+57A==,type:str]
            HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:gbnZvhfFaJIYeeaLPbW+hEGL6HWtlYJjy26lfHu5t5n7M+fLzspmi5cLyxwboQ11C/VWkzA6uprIKmhs+f4lJiCAKfhkUCdOO8y+8SCWdZsdsd74JJDJZ3AW23mmG7fGYf/9CAtdxm8AhH5CpOD7hhkYNIrqKp05miRKHNsuYICjT19WGkT7xl84P0AmZnvdbtbR8n/2JFatrVBfM5BQk+k7qDwVX4ja18o1/beiRBRU1TaFv3alQzcXDraci+bEF1gkZDxB5NyRuKgMAWO6Yy8ldTGJqzwZOz09RUFFBwRHDJ9SKcIc0zAvWH+Wg+OU,iv:bGSzUStk736jvW3h2ZWpT3M5j/q0kzdT9AsTLWPO9Go=,tag:SFtLg6b9+ezBXXW9LIHRHA==,type:str]
            HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:bzbqSGvXuLiKsV+ZDiAItdjEHpuu8PXbuFlA+oVB1ejExHABUseMOoL57rBcGXCK2rctnq6nbsPOvYyFJpGur3Q8nGhBbAe7zzQV8fgbJkCerO936sKDuLDGc9sqt5QPlyVAQ8SwkHCubSvJPpU3joToWX48U3yO/XBW0T/AxCYjPOyY9i/1vSq9MOJ1Yp6vfxfB5v5yra4+rl3GDyb4fA+GN2uREPzJYiz5UdSuukRZNBI3Olwa,iv:gbGzdNXc2URJrYkMCPcibfXapMOgxxXz1g7hXRDtaNA=,tag:nedPMwwcqiF2xbkUp4UBOg==,type:str]
            HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:Tks57Rqqwx31MEeKekRyF2SrA19fEL02D2biiCESCaDfIZLA0aibKh3lsYecTkeKqnbTcD6oHNsoi8eRaiii+djR+jk=,iv:mNMU5BmbkJ8slT07fDzIhGeuziYtkvcOSIkpc+IHteE=,tag:AMYZC9a4pfngJgS7g7/I1w==,type:str]
            HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:fmp8X1s+awGFp81VFtbnjQTUSEySM8fPUmg2tAd+zkk=,iv:zGkgavr/HRGzkvxQDYQIJ+WnRLm82HjB0SgM0dPQkiU=,tag:HcT+fIaKDsZIs8cyo6v0Wg==,type:str]
            HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:8oDE5ajkwNJozQ3kdv61n05+W8dr3iENHDwNmS1kgcA=,iv:z3BIh1bTArZogEMLbBRYmvdosZGGapx9MOfl/gppjDg=,tag:INsSNeHrOmkj9FLeH6R2zw==,type:str]
            HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:GqKY0G1+6eff3dwKz3Fs3wHUu/D4sBzRmFDIMKrS/IE=,iv:qRNCut0M7FxGe4oPjPrsI69bevXB1441AmdRn6utAkM=,tag:kBHRjXwhh51oB+L/DnNPsw==,type:str]
            HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:zom5xFCsc3yuoJLudLqg17ZoK4WRzxWHB98cPb4tc3A=,iv:7HDlCYmn8FPyx+6Wfr3gl9FuAAmX0dGbZnVvchNu214=,tag:3OvOyL+k6Ecd4GaUb0eFXQ==,type:str]
            HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:CWez7Sy/zsY79vygvshqY1XmWxphQW1/QHFWU5TZJ1o=,iv:0DPEBc4yBEyheiPF4kR2//BkpsfTP1V6KEJKpCBEeT4=,tag:4Wuu0u+I6Sv7QNxn1ZDZmw==,type:str]
            HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:H6yg1SUW6oszcEQFY3tjgro7INEz3PPSyHVOgD7BX+V5sODkDfssbA==,iv:elS2zZlugv6WfvCi81g6eJwW9P7/VoZ9q+vbleqTwxc=,tag:MKVOSvVgY2+eySWD9EOdBw==,type:str]
            HOMEPAGE_VAR_UNIFI_USER: ENC[AES256_GCM,data:UEGSi8L7BQ==,iv:4nmoriSSDK3BvD3iMNnuk/F6ZPPafcJmRgXYeKKaqe4=,tag:6ZvKYwL3Yspbig9AYWr+9Q==,type:str]
            HOMEPAGE_VAR_UNIFI_PASS: ENC[AES256_GCM,data:BXuQHMeHtXzK6h/Xg0cRewoQ/928t5yj4iyx/oYq,iv:Tq1JUj4LAd936on1Mm3Wxm4uv2bf3Mbq6YO3GF+2Nt4=,tag:eSAEAlkFRWG1cnVEHGvsTA==,type:str]
            HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:X7SdSUKD4hcUK+KZv9/F9S6O36BVIIqJNkuos0yx73zeGfNLJtdqIHqTNOITL29b8aS4NrkwwMk2l+y9ZLIBko6A,iv:heT9lJ2IevFgroXKLnnikl0h5XmupF6XBBwNOV85AdE=,tag:XId4bw6uCtShaCR0Id9Pbw==,type:str]
            HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:rFduK+bf1a+RNA1i7EP3Wg==,iv:/JFjkAELcvnq4aeW6gkSzilMOn1avUNxFnhz7leAJyA=,tag:Quz4kn6W1N2T8QkJd35Kww==,type:str]
            HOMEPAGE_VAR_PROXMOX_PASS: ENC[AES256_GCM,data:2vPlEhuQnWGyY8o7WNb1UktV71STUBClekxZHK7H9sOvWqQz,iv:hH0C+hThXpxYOKXklOlIYJ+XmNmnZdec5sSrw42dycM=,tag:HLQFMXxDpoE6aLMDeCcA2g==,type:str]
            HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:1KXdRlOGa98=,iv:JUUcp9hMTsxbwj4pMNcCmx72CA4Mj0k2M5yxkd1Y27w=,tag:aoCa20SPldYfatg86pykow==,type:str]
            HOMEPAGE_VAR_GRAFANA_PASS: ENC[AES256_GCM,data:jLC2mu+51dph8gX1f68aTX2Rqrp8ft+hsMC6GjCF,iv:Tl1Yq9eohiWGz9Gb0LbYJsvYxWtgZyfdnw1GwZ92/lg=,tag:k6mW43VG2MtnViH3pdwTCQ==,type:str]
            HOMEPAGE_VAR_PORTAINER_KEY: ENC[AES256_GCM,data:7T0+RzlLIKc5UmZPcuk7gLZXVcm97EflXXok5y1TGlqeGFk4eStXqz7mB8+1ChhI,iv:N+RFCkkbdn+jJgrkCkf6gqYTfF1L0J0JXQ/pK6up2Is=,tag:JrQgy1z2NR67/T3nF42y5w==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWnhVSVdJUnlKL09FbzA0
            bHV5ekk4MHNxTTJUdm1xcTU1RWJubGh0VFdnClA1a0g2MFNvWmg4RmhyOG55OUls
            UHY1QkVOSXZFM2x2MHZpcVRWMFp3Vk0KLS0tIDJxbU1rbzdwQm5uSytFODhFeEhN
            M240STFRVTdFcGs5TzlENStibkErZE0KwhWEwOhZmjaM93HZARPTdcjhPqC+CB/1
            UUSQNONjPQJierg7ntAMB4tNlgxFZVFzVc/rLRxEBSKjEKPCF9+v2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T20:25:04Z"
    mac: ENC[AES256_GCM,data:kvNefnUZHxmkGO/sD7KqbSSHv4qWWXYUGMkecOxRMhCsJfs3ObZyQImHGh7Rdam9qhD0wsm6woGIlR4u5+IwkRybCnbwlbSRCPU8wsJ42qxfKVH0HkcpFuD87JhYXSfISGCJeyMgKTgKbr3t1sRvksq4xKP6e8FS/tBxhadGWCI=,iv:fFzknqjyAJ4vbtGRSAXY7CxRpggOgJiJqGXA14fIpVs=,tag:HdnKbliEPDxiMPmEPN7tjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
