apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homepage-secret
          stringData:
            HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:2vePWKCI,iv:w5HIAvqZfpO+lEt/ULudCP8oM8hGLca+aRwe+aL5bDU=,tag:qJBVBt13bsw+ktQarKm9XQ==,type:str]
            HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:mycwjgZnLUKFHwhr97n5CbQu//ViL6ATDrbz2O9e4Mubes5KJAlEvq07YZzi,iv:HdKRrqwIAvkHoC2v5Ec5xuvLEkapXaZ4E2qhhHrJ+74=,tag:/vliqu1aZGhHEf3t+sB/Ew==,type:str]
            HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:xMLnxGj0RVwJ9wcYhuRC+coDZIOn6gIxiEO8XN4X7IfT5dyQOYZphpzgZMN04/k+dZaadgCCNpbA0okX90mQz4qgKRpW2ADRvjjbl1KqeegVI2RtZmrH63YnF5xkcBQn4zRaUTa9/WxUqmfIqc5frKkS7jzm6AS14vMzAOy+GZZ3w03ZflmbixYRx8a+AW22m6xwzQMRpgyvWXt0Pa/RIAkLa4X8AKYu0jKA0WkQTbW/c5GJGMMs4FBUFqKQbrh7RPQ1MZ3bewkWjN+njM04I2hj4FH7QJY6Am+G18UH/owgYpB5qg5+HTMoAXSTTQoE,iv:EcfGubj9jC3/vPgkvMZjvFFjM5j+DeDyu97vp53b24g=,tag:E2IV9+PFS/8lrjpgfBBE7Q==,type:str]
            HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:JWxdMz/DLoPZj3eF1hqbmxdB1d9TjvTDStTLNCEEhv481FNLnoX+TZKE+D+1d5/bRplniZii+/kLqnFjwWyClK4tTlKC8c4w0NheT4rfXnL8s+zOhbhe7IovwfVSV6inN1tzykyJ17Ng9Qx9RtkuC5LktmfSpOg58oGoU/pxeLuV3CjfslxCZI6sF+aM+LzWeqW+cRBzwqUWUsjbbkDZoLEl9ohP0P7bIG4T3AcLPiMzCqymdsDn,iv:dtBcwczMtU+UHyUsAWc9xxwrpjgpjg4hxE9jsCLMI4w=,tag:B+oPBVfeiIv7znZeodBfAA==,type:str]
            HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:Ieom7Vta0lhUam414eDMNwQyMCLuPqAqWXosC/GympHRxqYBP9VTLmyrjqyFEaFQmoUYr1+zNUWMegVawXL5/v251b0=,iv:a23neQ3BsH/ZXiBWTHlwotnRhHIGca7Z5vmraSKlLus=,tag:qI7GukRqaOk2PySpqmvetw==,type:str]
            HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:HSfSLvBxdGzX2Wpu0P/6N/sroRjNN9vs2BVGy3BCZqI=,iv:gY/9K3VbEqpt3xs9VL9ugICTK/XO6ad6rX40tct3W5A=,tag:uYzx8W2ApU1gKL9M/bmyBg==,type:str]
            HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:rXS1prbe4eOXM5QlrASDTI8b8Satw1xDBLlaiRHg5NU=,iv:cXuze2Do3swfHQYx+iuDYIyhQ+Hge1DiWO6hHdsA5p4=,tag:82qHluaiAeLVYJwg4Hyvxw==,type:str]
            HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:9HxlhkHaWNEtin6xvlDhxmOoG3TxGIK7XgDl+AdigBU=,iv:SgYQwOi0w4iYBq+3YosBALdRjw7/s///aBJ4e2Uf8Ew=,tag:PcefMt9Ch3i9Kr2pc0W7wQ==,type:str]
            HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:Cpx6Z9uucvEQ+9ggtx8TL3ioeeVb3PS7g80yjjpJlSI=,iv:elAeznqMQFy+XWqFi4x02fbOZb6OD5Rxa3mp42GsRxk=,tag:q2r/t9EvsWKzuesdpY7XHg==,type:str]
            HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:srpxRhw9/ZcChSdho9bC/2GCx/Fu8hrLE/QRiQ6xtz8=,iv:BtEVoSS3ejeatEMu2ylV679PS1HdeboVF8X41JO/ZJ8=,tag:Wex7mjHeuIqhHNoqEwTqPg==,type:str]
            HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:rGGaWy22yZrIV2+xS3GzrzWYVoxqcr5fF/+WbmfFuUhVtNlvSIYd3g==,iv:34AQRELd3NYtEYgHZ8vVSzUbGemb9Rc7s1SFKefUJ34=,tag:kYtp2XGf6htmZwVMB9ogrg==,type:str]
            HOMEPAGE_VAR_UNIFI_USER: ENC[AES256_GCM,data:DdGeJgrmB2I=,iv:x3XdbcZWCjRRJMSqP5ltaXonJdAxMGz4Tm4KqLz2of0=,tag:2hTs+HPvb2b1PGtXqvOMsg==,type:str]
            HOMEPAGE_VAR_UNIFI_PASS: ENC[AES256_GCM,data:BpIjNS0XEYDiElg49/QP7TJ2JgiqVzxUJgphd8Cwfmc=,iv:oh28p/E7h6ytmPJJuFfUt+OVW56Vq3bF9feC5BxbHVs=,tag:6M3+gj44qEUD9fQESKkyfw==,type:str]
            HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:PKI03+ZUabtX4s53dcttTkVyPINb0Roaf/VYks1OS8RGTGObwCvk7ExdytX52lEJUJQEwVSWya9oXpFZ357MnppY,iv:1gVTVXWFKGc8Na9bx0I5jtn5tGcLQDCRDCDnpRrMia0=,tag:EL6i+UU5SjDXqe+5XQb+/g==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUElsLzRpYjNCREZIMUN2
            ZmYzUnpUT1hPVlR1TEVFaXFPNmRkWmRZNnpZCnJKdU9ZTjlHYzMrUG1sN3VBTnRu
            eWxXdHFKM3pwVmpKL0lQTXRST3JHVUkKLS0tIHd2WUxWZXZ1UlVQN0pDZGdtMkZG
            Qk9JdVdrTmRBNnF6d0gxTk5FVW5BNGMK0qfUPYhfYVZpmzvaEBY+u7RTLcVaYtPz
            I7c26tFno00oXznymaU6HnEVF1l6aLOncaW4P9hQP9zT92EV2HHUlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T00:56:29Z"
    mac: ENC[AES256_GCM,data:9ta5VuP824TZX4CAuhbwJDYUfLeUSaFuI7zCyd4I5wVzBo9jY6ea5kjqNvYeanY0VDfbUn380fR6Ph+6bSGFM90otUIVsQdvica6atSGbOwc7CFEPOAoTvkJz9LGq4oFvYv/Hg06Pl7kSm+gC1zmKZLgHxKIE4pabQHUWRo+iRA=,iv:++JfrupGPwc3NELZdmK9oSphY8UbPSrmuNxKiLFcOhg=,tag:ajbtultbnbzvy+ieaukraA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
