apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homepage-secret
          stringData:
            HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:GEjQME5P,iv:WrFIcT/63FCNaQWPvnWqPs2dPblwwLjciJktjp8HeSI=,tag:jhvwm3nvG6fdf/aT4CFulA==,type:str]
            HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:EuW1L8OWEowZm2oq96833wCCoj2Vmt55KuuLobZgU2nw7gxwam339/HVDaYQ,iv:FECh7g4WefCCiepP3rO+CS5ykEotqIuuyRJhsf/Qgz4=,tag:plSk8VKGXppNhYhet3YJCA==,type:str]
            HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:rPa3jTKbGb5X0t48Fy0fR8+MZTyNqbb0xOaqzyQe3QMchCxTWmO5vapOkYKMoCje7akFhVfr8yniGaNPia+kOZIEDlehjCprHNWzg29QwiA+zYZrt7dAWXTHxd4YAM0sP5+1Bkg8PAyT76e8dpDy+XyMFgmPU30lmrR3ZwzHGrOi+Y/XJZ9ZLY9qW4/k1Vpl1xaSzsIb07YhhVXqINYgErnFECQ9T0JGGyNc8ykhuyuLSQ+ermpXbUVCxwtCh92ySURqxbKHfvvCZPMNkgrSs9IxhcW+KNQd/dbdEdzqsJ7ss/0HuTaGH7Yf30jxTeUn,iv:1snQ9m7DxrRIsWXCc1Y/QawL9F8slax1KUkWfAoGdao=,tag:qlCwHLEkLkfJRoW3vY77qg==,type:str]
            HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:CEpBM/GJieqWC03DNRFFCbLrWm2M7Z1uIF4EEzuRT77D+c1BzAamxhnbvJRu8h7QYBy2XmlPIv6yPfNNaw9w9XCyVjYJN3PMFc9BN+1OYjdO8HDLa0doTSCsKu2FOomWNmV3u8lpc32qCqD2fPRHSoAJ1taAP16PzTrNIrMXuGSrCiphjlK521dIxDgdqV2yBCxC3h0VOeccFXAxFxpuwm5DHmXQQDUQnstTFgpbelA4FtZxXEiX,iv:u+P0gfyNO2IlbcRJ8WOHztKmDXkGzBi6FZsCGLf+9tM=,tag:gex7Vhooqgntgn42x4TO9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQVRRRUVFTFNCUTI4UDB0
            eGtRZWlabTVNWXdlaFozK0I2ZjJnU1E3YmhzCmtzRWRIWWd0ZWxyMHBOV1h0MGpN
            ZDFZUS9FMWRReEpNWUhHWVhBcWl6NWMKLS0tIDVHY29iL3NZZzdnV0tBczk3QUtz
            UmpaeG9UemlSVmpEajRFRHVQWFdHaDQK9rhm3f2UHeL++XNg/kcBFdsuK/ALQkiQ
            O+snQRihdvFDAbreMR4wJ3hAx6eSvigyt8WGEYqFO8E2ynByKPPT7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T05:16:36Z"
    mac: ENC[AES256_GCM,data:hjQ6OELVmm5CxiWmjZvQCNAQH6dd/XTVg8Y+IzstfsUAP3oCeJ7nAgKtg4rwWp89qNbJ0v5wJ2yJnYC0sM3Ns2n+bEIe2RE75Z9EuU4XkVXFVbWjHtfimxGHZ5t3VAswcHO6VyarjShYaPG+ydLD6NOvb/OEyF6AoPmwjQeuuwU=,iv:JFgVDapobVs7TFEamTWolThzbn508WSM0PH6nynAb9w=,tag:yd6LJzu9nzVBG2/o/4s5yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
