apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homarr-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homarr-credentials
          stringData:
            encryption-key: ENC[AES256_GCM,data:1TnF3/9atXl+cNW7i+2QNtMw5gBwufVFOhTTrVjLn4HH8EFE1DIQgQyQhxeYx7WtOlcT77OohLpDePnoO6Af+Q==,iv:78nB8diZTMbb5rhOqjMzX46XbaWVOr/SCeZYHZkcOog=,tag:I5TaWGua1s1D2MCzNH2/Kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1unhax45cm95ngm2h984sq22v7uxm7rtle8mlrg4mfgs55t2kr57qxkxyml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSkdTVFE2UzBCMTdUOUdI
            cCtscUpqTWRaa0UraHN6RWRFVlpxNERNem13CmtqcTN2VS9VS3JiREFzMTVTOVFN
            QVIrMHd0ZUFVQ01hM2lWeDJsSXI4Z1EKLS0tIFRvT2NNNlI2aDIxUkEyWkw1NjJ5
            Z3ladDlmanR0ZzU3VTRkeWV2cGgrb1kKA9Q5BOew3NgZUXsPIfgh6rWCOjieoRYe
            iyC9hpMEjCs9wpnwpjJDOYMLkKjwsqn/PGXvYMnIraD6uUBCwQWZPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T00:59:11Z"
    mac: ENC[AES256_GCM,data:JT4cVSYN54BGJegouA/TEQtBwB/b9Mvp7aR+RQCQbl/gXQcib6MCLLkdTMiugaBNuvv0W/NgkLzdPltJCadnFzT2WC/RyNhP4xTlD1X0AAKSInVnpUCy8DNvMT6Eis7W2reJfAtuvs7DW2QLL1NXw8JkwymkM+bRu9Z3QFcMeic=,iv:g151vnjc+l3yQQ4g8htzkn0ZzWPxanx22J+aEuor940=,tag:aG1pgnql4LOcy7w5CMMQEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.4
