apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homepage-secret
          stringData:
            HOMEPAGE_VAR_ADGUARD_USER: ENC[AES256_GCM,data:h3KfH3JU,iv:B/jaDbI7lUXjSG1PqnjnXISH4HSyQ03W5NTc5YLH3RE=,tag:IvydMNbB2inxU0QB5l59VQ==,type:str]
            HOMEPAGE_VAR_ADGUARD_PASS: ENC[AES256_GCM,data:9fBZrRrT9DuLElukEq8IxhLRMgs6kku8pmVayqNWDGJMc+Rkhe1HPxSkC31S,iv:y+IkDU6DHQypaQZg++nXDKTw4/QCTIEJqa7p9skDEgg=,tag:4SDDJ+2PFWtJ4yTGLbUb9g==,type:str]
            HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:1yMJGRqsZbJUOaPVknij7fH/1Z87WkSLEg90IulHY4LqPcjGWomIyzSbjTwhDfO8XMVrLWkOYLIvy/QYHama0oRqjmMcSbJtTEBn6G4dETzpDNMB4OtTXLBmxxlQ/EtyO2o1ACOaAM4EGlHm7fj+w3GF4SdXIXV1dTMS/KjHzXBifPj9PAjdlQ1swbmgobw+AbhXeQ3c/sXEpZZmTSeU5tQNSoECg/ASUNXd+kXknzUhqLgVlqqQW9slMcv+fq10VG/YWH65xbLmmbDQygUVn/4/Soq619++Cu6BskFTv/kQy0SEFYK6FCpFZseNoFco,iv:9ZJasDyTbfr9EeIUPP52tHZHpKrooRtna8fF51/49lw=,tag:HX2850OVDmORGEMQX4DOSw==,type:str]
            HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:VmEEXglDOiF3ZrYSbLsydGbZ2yO8a1+xmuetVawHf28W97f9F5fOcGlMxLv4iCPE8t1zyeGn1vIRqXpVUlMNvbm68xop5Da3xrsuchjRjAvAggTsM5G6Wo/9XuulBCHpoB1DOLcldNIfpl2yl4Kd1EajHDEhvCZAwsu3EsHAEn9UOAgK8YRba1XwacT/77ekMENZSE567G+cAiN9aM8hW2CFvlB9fE7ZvsX3j6HYN+Few9Fq3jwI,iv:jIJYS2mN9EhYsyhzMavl5b4ZPKLyvScDguM8ybkmh3c=,tag:i55FKeP97d+/YkVusyuJgQ==,type:str]
            HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:V8Cnaqk1a5HOYatmR2EnsAhWVJk5BZKabZLtxGGcimSRs8C1HHYAfq+zLLTS7MrvYPWCCOtbwu/pLax5QMwMIUUOHDk=,iv:bodhGEBH/Ls6wiUAunE9S9S4lnVOa8eebsVluiwd7pA=,tag:Kh4kSMoKzicUkQU35hhKrw==,type:str]
            HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:xSPnKlc2fNDzBP5hBfePBwgh0ZSPJdp7Q51KbKkyv24=,iv:9lVr+ZvhQ/NlFAYiDDuKQe8/eUHcJMyAgP95G/yqzi0=,tag:5UN+8l2MLgPIExK4upuugg==,type:str]
            HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:nqhQeFm5gC5dgOg8eXTnBYZ/HWYy3lyPExWSgH7Wjbc=,iv:+sRUp+v62um0sB0fUxZvZJAMV4wmC5PSQbfsqiirA7o=,tag:LFsLc37i5826Roh9OA3ioA==,type:str]
            HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:zMY7/KZNQR7rRMbsQxPFXlp3ugFskN1pb3YtU98l/F0=,iv:8tmt21fJN22L8IHXXx4jB3qS9OsOD2IKFE6AdplsmFY=,tag:k/fUnZBiPU0QKFMWt5PHiA==,type:str]
            HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:d9iW9Ql2fn5aXi+nGLySy28ZLgtZM3/+smaK21dH+3c=,iv:VOyTcxtTqLYi+uDYK8NPEw0v8NxjymVRhImQt+UuMLI=,tag:t40eH6ACAIVG08JHldpeKg==,type:str]
            HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:SEfjQcUgg7Um/BsLoS4uwIlwbQSRzj+sCnlwSbIogtE=,iv:FjX0bbqaJTr0RzATZQtTVnYaulzmqtwSJ7l/209ZmJI=,tag:BQ36uSKhqKwHgebn9rShug==,type:str]
            HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:541rqqaxmFJAF2rtd6cBEfpSlh7oWubmC6JjRmRbiPe7O4WYWMhdJQ==,iv:s5NmiHuhDKx3SE+USSENxd310XiPBX/2QJ9YRx89bMU=,tag:JuDUyeIJcAOidgKQfe24iw==,type:str]
            HOMEPAGE_VAR_UNIFI_USER: ENC[AES256_GCM,data:mez9D7+FibY=,iv:d9h2aomuRdg3biEiZQIfYQEh34nJysLye7iCIrlJ+qE=,tag:Lud9dH/LK279AfjXx2IfCw==,type:str]
            HOMEPAGE_VAR_UNIFI_PASS: ENC[AES256_GCM,data:WcP9oAclcBBkJEqlQWI2TagOrHVgqP+XgSOfGt5Olzk=,iv:k3zw2t03X1fSK0/Xfv6sa1t75ufE3TSkfQ8Sgn43/YM=,tag:Bv0Hqasb85gp5n+ZnPYbUQ==,type:str]
            HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:Wl0h0mZ2GIzUaZYsTw/EzqaMs/6fTXbRxcVl1Uenm6N0C8EmYKIK9sD39P9+r1smBCZ5IH5NkpJH3eyqvY//RZGF,iv:Y9nnysINhlcDPPB5WOcQNoCMsNWdz336C0SABjZi910=,tag:2gD2mtrl4+ic/Fxp0bl6Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoemNGS3NqY2g4YVIrKzBp
            aHB5blFFTHYzL004b3hodXBhcUx0eGh0UjM4CnFKYWRiaTFhemEwbEQ1Q3J2Q1pC
            Ujk1KzIzTG9tQ0t0L3hnZkN3WDZiZmMKLS0tIDNZcjRRNGxUdTM4N2RGWVVRUzZO
            bFFzS3lBY0RMR2J0Yk1YR3BzY1l0WmcKrDBvfFuH73c7hhyq/vOlkhfUfUQC0CQm
            iV3wSyAxg57G4WDJTib2CHf6ZaVOoSHq9/RjkOO0Z7YzvlF+BLocdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T05:29:57Z"
    mac: ENC[AES256_GCM,data:OHNxbjQK9PoC6gLMN2FbuwoV1Rd+INRRYi/WrDhvYRjdD25aKhb1c7jJ/WN6sXTS99Ujv1NU96TRLYcgPPFXlnhGP+WjVFFw693YGS3IwT60UMJcozC471lUlwr/MFMcyUdAlvND1syesMVm8d11GOkFSGucyf3dAg5mFfjXeYg=,iv:OyDyhc+Xxt/FGELxCIZiLSQ9rBWLd9oBpbPH05SfQOM=,tag:cW1N/lcMxdFFQP8g1SadIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
