apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghcr-pull-secret
spec:
    suspend: false
    secretTemplates:
        - name: ghcr-pull-secret
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:yF16J3+1Wn1Rm0EvIHnBZo6zDketDeuMngAQZSglnyLpE94cfQnUqebgznVS9XCxGsDtX/A7UeU8cMjKbsMMKt7Ay47W5voMYOltuoe7VqYk/4QNzmUXrQQasZKYn1F41g0/,iv:c2Jlqn7JcUldlQ+gqF933vnheVvYsKQ3lCSHpXQhok0=,tag:2wM/M4yBBZeh/DeOQ/fG6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0xBdUZhOGgzUElXUE5G
            Z25CN1ZQaW9XNGhWVXRmQXkySEpka2lGNUdRCjEyMUdiaU55OFNhRGt2NWFKS1VY
            TW9TRXhQZTRJVnR5RDlHaWo5aWJKWEEKLS0tIDhCUUwzMFBpRFJNUC85OUNiZXNh
            YWRGNGZoRjhoOXgweFJEYlNRNnVsNncKoM0bhIaXyhlmXUC9D9fO4d/lOsDzXk28
            FLSXLf1M0stTc8tqwgMY9I0moAArl1m5IMwHvDOkRQQKuOFx4Ib5Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T23:06:30Z"
    mac: ENC[AES256_GCM,data:zUY5hJaDFe7a1tFcu01JrZ0LbAQAA/sH6VacnOrnOBDj9tTFTRVrHnFrAnvxLuBEp84wnE9+21USdILc7nLr3j2VVRj6vCmuoqEv+OCkxFrttqEyUKyySFnb6/ICiWmfXKEiRikPHWB+WUByOLCD+d1Y9ykJTjmpf5JXn55eLD8=,iv:R6WeWlm7rWwIS0fJOVAImLPwkyxgsrxDcCYzf/ZAft4=,tag:cm6yyowSTrALd4Exh7z9kg==,type:str]
    version: 3.13.0
