apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply labels to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: oneuptime
  homelab.local/OwnedBy: ElPoshoX

# Namespace for all resources
namespace: oneuptime

# Helm chart as a resource
helmCharts:
  - name: oneuptime
    repo: https://charts.oneuptime.com
    releaseName: oneuptime
    version: "10.0.34"
    valuesFile: values.yaml
    namespace: oneuptime

# Additional Kubernetes resources (non-Helm)
resources:
  - namespace.yaml
  - pvc.yaml
  - ingress.yaml
  - secret.yaml
