---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oneuptime-data
  namespace: oneuptime
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
