apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: oneuptime-secret
    namespace: oneuptime
spec:
    suspend: false
    secretTemplates:
        - name: oneuptime-secret
          stringData:
            #ENC[AES256_GCM,data:zM8EvzHO9535KvSKsBVK9Dojo8B2PUEUBw==,iv:xIKgq3tBirSWCE+581W/fn5FKfqimMBGlv7eisbcAKQ=,tag:5bqD5sIMDDBeXcoUH+086A==,type:comment]
            POSTGRES_HOST: ENC[AES256_GCM,data:IbdS0y6nO9ok12xUQcOn1uPje2awJ/JzfduAIljtBQ==,iv:YhqCKoU+XvhPfW6lxa6jvkt1LlCFaYP3mUSXodlh7FM=,tag:Y1Od6exVTHKoB/bxrRcgwA==,type:str]
            POSTGRES_PORT: ENC[AES256_GCM,data:FTsmL2g=,iv:s0rGnl1CYi7mbyXBMgNPzKJMgUlAfoZzWgGAk1vvHxs=,tag:YdCJ0/Dd8Pe5h7OPw2i/HQ==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:JmHUS90ioXpA,iv:21xT56GHw4IBm9Kgf2BxZc83xZRry+IrjLhvOxSMq+U=,tag:M3o/FF9Td200XUwRMDewVQ==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:xPVdjheh,iv:I5rL74qeiVHDB8lKJ1Bmete32MsV/9XORf/JPguKd3c=,tag:/O0ojh26k9EI18d95u00oQ==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:FOKdeYFU9yRXyUHL/g==,iv:WbSvnzFTNJ+wq+V3NJQNcWQ5Qvgz3T+vU1DysNMg3N8=,tag:aDU6X/iYjPhlop3BFLf+UQ==,type:str]
            #ENC[AES256_GCM,data:152ZjI9WBAlQJdJhqmlLFMsRxaI=,iv:8PmNNuAMuZvMeeQZsgxs02ga0BvIgZVsUBo8NYEsWbc=,tag:toR7kN8KL0Tyr95o4TwpOw==,type:comment]
            REDIS_HOST: ENC[AES256_GCM,data:mRIfODVoyxXHfsu8jgqnNLpKAQtnwcGlPtHb7Q==,iv:M4W0tU+HaK+N0JVT7K7Dp7cD4dJc0rk+vsp/isznKwo=,tag:hCtXY4QWBPWsumyLclXbSQ==,type:str]
            REDIS_PORT: ENC[AES256_GCM,data:KObVTek=,iv:YrpF+GBDjVanSHOC8yQBj8DPd0WHfYLYSSjGKzPwolc=,tag:NRyskgIzbR++sWKwTvMYmA==,type:str]
            REDIS_PASSWORD: ENC[AES256_GCM,data:nNT1E+PV7DHr/v6/,iv:h2D/KBUpb4fCtRbP9vruiONOh/afRvqblzQAHwb/oCw=,tag:U/W4rUbnE2H6BWCbD6KbZw==,type:str]
            #ENC[AES256_GCM,data:241GXFm9Ce/LF/CHWMoz+ah+V0VV2BGCmA==,iv:/4FdeSUsSb4XftuJ6Ps8V8itPhDGyPY0f8dpKbqkZy8=,tag:FD9g5urMBgj1iAGQzxZD/A==,type:comment]
            CLICKHOUSE_HOST: ENC[AES256_GCM,data:rpFex1AADpMHieDQMvCKr3kYVJ+LlSo1c1Zvt6GKs8mB,iv:IHDEA+It86U7Ov/AidMjEsvtYe9Z1Ue53Poe1iYeVik=,tag:ygFh7mUAyzRzoULBHR1ixQ==,type:str]
            CLICKHOUSE_PORT: ENC[AES256_GCM,data:t6s9vw==,iv:OYv4zcBrEiZ1wcj6lQgDBuhTNvuN+mYU2KwI8t0hZnA=,tag:dIvIvKD7/YXIDZJdMu3++A==,type:str]
            CLICKHOUSE_PROTOCOL: ENC[AES256_GCM,data:EGGa7uM=,iv:T2tzeQFttuuYkYDvXlXaXzDM8khDSzl5ydmlNfJxXEo=,tag:W1auEphMFv8GXCqIJioHfQ==,type:str]
            CLICKHOUSE_USER: ENC[AES256_GCM,data:QqwTuDcS,iv:VCe28lNBUond1axTx7qVe6CFvCtrtjTpjGwvVD4Bai4=,tag:clr88uVOZoS83TfTYBic3g==,type:str]
            CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:bSsps7zwHq9g1/w3Yui2xw==,iv:x9kaDWzVFZL6qKLwrpvIzMPuwTzLDyja+Y0XZs8a1wA=,tag:4jhWqsCOC3H4YEYEzWQsXw==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdzR1Z3h3ZTl4T1l0WGFC
            emRjVHJjSU9lQVhKdG1DSGdQUHNBWEIrQ1EwCmorOXIyNXhKNTIxVFhCc2FDc2Zq
            NnlmMmE5a1JFL2FFZHZicEdZdzFzamsKLS0tIGRuRmJya3pXT1cza0RTYjVrTjhO
            MjYzL1V0WlFRbFRzZ2FzZXNvb3p6bVkK8ZQjKNC0Mz1dW4Ohvq1bVkBxqM9T9yC/
            GKlY0FnzBdcB9V3eMTBiT78t6C0qfuB53g+jExhhuUKfgGAxm2jr2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:49:18Z"
    mac: ENC[AES256_GCM,data:RtpeNnYzMPodhBdZGizPC4oqXa3dzzilR6PY32E/T4ygrK1KKPOaoMTUY0klbPzDBJaqaMClAQ3GbcPyfcxq4vUjHJuGap1vgMIVHFZdqHhiZxxOT6Jsl+XTCQJaLBeZjfeNrOic3D/rrJ5xx6HAIvuDme0vGtZasPQqrWTaFWk=,iv:0x8oCmVZAelDg7ex0lSCCrPIs6W0vfQegLGPUcPkL3M=,tag:NmeEM9r8v8J6jLg+mFYNpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
