# Promtail DaemonSet Configuration
# Link: https://grafana.com/docs/loki/latest/clients/promtail/
#
# Promtail runs on every node and ships logs to Loki
# It discovers containers and tails their logs automatically

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: promtail
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/component: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/component: promtail
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3101"
    spec:
      serviceAccountName: promtail
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsNonRoot: false
      tolerations:
        # Tolerate all node taints to ensure logs are collected from all nodes
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: promtail
          image: grafana/promtail:3.0.0
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
            - "-client.url=http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 3101
              protocol: TCP
          securityContext:
            privileged: true
            runAsUser: 0
          livenessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: run
              mountPath: /run
              readOnly: true
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: run
          hostPath:
            path: /run

---
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: promtail
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: promtail
  ports:
    - name: metrics
      port: 3101
      targetPort: metrics
      protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: promtail
  labels:
    app.kubernetes.io/name: promtail
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 3101
      log_level: info

    clients:
      - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      # Kubernetes pod logs via kubelet API
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Use node name for pod location
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node

          # Use namespace for filtering
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          # Use pod name as label
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

          # Use container name as label
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container

          # Use image name as label
          - source_labels: [__meta_kubernetes_pod_container_image]
            target_label: image

          # Use labels from pod as additional labels
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: pod_label_${1}

          # Set path to kubelet logs
          - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__
            separator: /
            replacement: /var/log/pods/*$1/*.log

      # Host logs (syslog)
      - job_name: host-syslog
        static_configs:
          - targets:
              - localhost
            labels:
              job: syslog
              __path__: /var/log/syslog

      # kubelet logs
      - job_name: host-kubelet
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubelet
              __path__: /var/log/pods/kube-system_*/*/*.log
