---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: promtail

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
rules:
  # Read nodes for log retrieval
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get", "list", "watch"]

  # Read pods for pod metadata
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]

  # Read pod logs
  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: promtail
