apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.elposhox.dev`)
    services:
    - kind: Service
      name: longhorn-frontend
      port: 80
