apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-backup-credentials
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: longhorn-backup-credentials
          stringData:
            CIFS_USERNAME: ENC[AES256_GCM,data:SZjNrsw7,iv:Rxx54e0NnSlJQbz0LPGGh40uctm+emQSa6YZUzHpqGU=,tag:O/kvWoHJN8IUwGPUIJSClw==,type:str]
            CIFS_PASSWORD: ENC[AES256_GCM,data:tJ8iSsrVJThsK5ZwuS/t3dxCXEmovxmeSQjPQkYagz0=,iv:bYvS4rbbOuX5m7KjDaQPlKP+aL+kE7rMg09xJYzV9Ng=,tag:6i0/Jr7HlmSDELs0RUB6wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WkVjVlFqMGh3dkM1N09l
            RmdQL1RVY2sycjhTdXdhWVQreGliQ0cyR2xJCmIzK0g1MHM5QjR1V3FJZldmYktG
            OHNjODNRSExoOG1EaFpCTzNIYUp0akkKLS0tIFNQRVdhbzNjQXZSVzMwT1RQRXJ1
            NGF6VXhFZm1zMytjc05LTUp2QjFBN2cKA/HXLbEGsYucvx9J+CY6EhHWP9Dv275Z
            N3vX3rfwSUijwg5R9cRKyiZ58KrbHqYUCvGA1OMvBoQCRNRQ03+15g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T02:43:57Z"
    mac: ENC[AES256_GCM,data:qR7NGdPNw2r2TK94PrPyU0pWkjpwIfLDa9uLLVAnipJlOqKS9tg/DuJHv1lj7Uj7dahzN7Fk6BtvifkXDSRhX1uU7UCXjkaq201EPrqgR4k7Vj7KBGgQya4/x3LlNueNa/rNS5MK3vuhLqqUbLRxV7uDBboLpf60OM138qvFUas=,iv:hfD6B5A2zl3e4zI9m9RKiZV2qIKKC9uL0TDfACvmWUQ=,tag:PJDR+CUaEN+0JV+te5bwnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
