apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-backup-credentials
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: longhorn-backup-credentials
          stringData:
            CIFS_USERNAME: ENC[AES256_GCM,data:vV8pO2iu,iv:o6sZg0kP2+heip/zQe2velks8K05KmPrzkEp0k5D+RY=,tag:gMOtDCzJIt6Zj+a0mslwEQ==,type:str]
            CIFS_PASSWORD: ENC[AES256_GCM,data:M0Ypk0Cmt5KvKBu671d1Zf9yScl3Fxwai8f4RRzuVmU=,iv:xBkqIbTIi/AwHl9tRHTQ54qJ5QlzU/V7Vaa48dykcTE=,tag:3mRxo1oa9RG6gatJaiG4ag==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbXBYSUtaeGlTQ2xiaE5C
            UW1iK1VCQnlRYTg0NEJ0cVZGZm5xR1pmVzNBCkFzU3k2WXVCMFNMOUFjZzdibVM3
            SVFhak1meGtzVFlMOXd5SjMxOXEyQTgKLS0tIGQ4RE5FdjN4NEtaOVllN29ieEl2
            ZzNPbExxdVR0VFQzcVAvT3d2NWhBeEEKnecDDGYC0EXz2LIJM6P++/Txwa96jC6t
            FnwUHrdzwMRoI36TvTuyn1bAMn9T5ykbsHHsQjbpxPl91NvRtvmSZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T00:14:55Z"
    mac: ENC[AES256_GCM,data:OUaBdXyvTvVtU+Ee9fQq32/E1Htn4xqzYuyPhZKHKro+mtiMc1ptIWtg/CRcMjIcLFFZF/2TJeuTT7CfXCu07nsqMESb7Xxi9ciFuDo5cq1PlP5s/Uyx0417N7ieRgcgvAR0lP9XdHkHIdekpIdwsFHaGykxqZ81caArpYd0rT0=,iv:vJByDPlPeJbpUWb1cFTetUDNCSeq4gWRPaWm2gQHvBc=,tag:lq1xGMrh6JjugMcJPkuWpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
