# Encrypt before committing:
#   sops -e -i apps/opentelemetry-collector/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: otel-collector-secrets
spec:
    suspend: false
    secretTemplates:
        - name: otel-collector-phoenix
          stringData:
            PHOENIX_API_KEY: ENC[AES256_GCM,data:RRKML2sJVveJ+CUs/kCFxLOmper4MEdsoFn7BzioOrCJPgf5WyM1PBmG/klT147aoi7rhIfkgvg4MvZcPBZUl1ghBJq3p91RddJ5+Fq+JRsiMQCldRvWHbdJS3c5xuocvIUHmFaR1XG8ICc=,iv:SMwT5doLiyi+xk8uVTvCD8UeEigEWbsjt3TEC6Z/MRE=,tag:VB5I0WfzZ5J9YGz3s7mUQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaGpjYitxVGpvSC91U3VX
            VkZxNW5UNWJ6L3pDMlRWN25CTzQzbm03UUJ3CktMNWxZZXJXbzZHWi8ycm5oVXR4
            d1o2cmNuSHkrRDlZOTBncjk2VS85SjgKLS0tIGJQYlR3RjBSakd3a2tEdTd2M1pH
            SzVBMEJ5TnJ5VnNSdWErWVFVcVNxT0UKa2RJkHU26Bf0//gS8GfHQrFpkwLqgLVe
            tdmLhkf9GqoGEm6f3MB7yCGVYWOIDTDS2pJkp1vweKHoZvTjiba1RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T23:32:24Z"
    mac: ENC[AES256_GCM,data:tSzbDgbEhnNuGIymqW33kA3wDAH399AE8UyZlTsBrQ9kgb5BgmHnCZ7w5C6MkL1HudE1pQ1ZQsqFXrA7M0UsKbNLmhDNJ1ylfstOdCCKCfRCc7VNhDhs7Fjjr84xyRTbdY8SaAGQstsKMrEwOHZ7cPJbcKhTh358NCrLpKns0lk=,iv:vjuNJtPS9k9pdMDz3r0FQkFEL4Clj6zqeBYi8R+UzX0=,tag:k7eXptupE4Wh+E8G83c4SQ==,type:str]
    version: 3.13.0
