services:
  adguard:
    image: 'adguard/adguardhome:latest'
    container_name: 'adguard-primary'
    hostname: 'adguard-primary'
    restart: 'unless-stopped'
    ports:
      # Plain DNS
      - '53:53/tcp'
      - '53:53/udp'
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - '8080:80/tcp'
      - '8443:443/tcp'
      - '8443:443/udp'
      - '3000:3000/tcp'
      # DNS-over-TLS
      - '853:853/tcp'
      # DNS-over-QUIC
      - '784:784/udp'
      - '853:853/udp'
      - '8853:8853/udp'
      # DNSCrypt
      - '5443:5443/tcp'
      - '5443:5443/udp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'adguard-work:/opt/adguardhome/work'
      - 'adguard-conf:/opt/adguardhome/conf'
  
  proxy:
    image: nginx:1.27.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/elposhox.dev/:/etc/nginx/certs
    depends_on:
      - adguard

volumes:
  adguard-work:
  adguard-conf:
  proxy: