apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-secret
    namespace: alertmanager
spec:
    suspend: false
    secretTemplates:
        - name: telegram-token
          stringData:
            #ENC[AES256_GCM,data:vCicAHIdk9aeeWgCdwWBqdOlcAahSvoa/w1kQnaVwjKuLunTTEmFE2kbSks=,iv:mpvHTVafQWvwDrMOT/6HC/vlLoT3drR1aUSbReW6+5M=,tag:C/ahyr9ymisRyM1hNL2FRA==,type:comment]
            token: ENC[AES256_GCM,data:Z+dEIq1QMDtMCVd+I7U5ZvmiG2OuPkkObxgilmsTKGH81DdxgQbRIKAmiD/36A==,iv:62Ej2y9c/5FTE6ZrQopI5viMFGPN/LsM9rP0qgeZHVs=,tag:07UCxGQyNAXba2XmCBCxgA==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOUJaYVBCTW9aN2RWWEtH
            azhrejlwN3hWTVd6a0t4MVhLY1NnRkRSNEhvClVVVUY2UFY2WTFOZ0NPZ1pOamJo
            M2Z3K1RYZm5ZRXphVXNqbTdlL3NPaE0KLS0tIGVreVEvN3p5UlIwMVBxVWQwREdH
            NVRhZnFyTjEveTVrdFZCQ3djUTBKbzQKbL39lutacePCNftTMX/wK8tz5+M3JczA
            VPRLCVxPSIOiNGpQ7kEdyz/vUq8jRtdUOr3779FHd0q4QPZQvXPN1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T00:31:36Z"
    mac: ENC[AES256_GCM,data:jl03remKefZ/kzzI0Yvqm+Dbm9wpREayxERna6Fpy2apeGeIV6fb0umr/RLBrqOuRE4++CjMZvy3uA7wtRtjdyuDRXBYLl2MSvghTgnXBQnzi6kX9cWDFAV5TW5Ard3qRlSG6rV1gUu2KibHaGFgU+lij5xasgGwmY6LA396WU4=,iv:yY49dnYh7NfPgXCDsUIncCId7x0Vgz15S0KjmL9q4Tc=,tag:WkeIPRrTfpEDal+t1TcRsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
