apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-secret
    namespace: alertmanager
spec:
    suspend: false
    secretTemplates:
        - name: telegram-token
          stringData:
            token: ENC[AES256_GCM,data:nSTpQrJJ1mSRV+Lq2F7dUoFgvIDbKyei7dRqvG45LOKWJK4EAh7vwtC6uVsidn9Vl7E=,iv:rGIOXbangVXGRk/WwekDkG/2eRNFD3yDfaD5cQyv9d0=,tag:Io9kSxaO189I32J4h0MevA==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNTJlelA4aUtsNmtybmFK
            UUR0d0FCTjB3Mkd5YWRMaDdDL2RTcmJUNmpJCndSeTdtdkk5akdzbXlzRXFWMEx4
            NzFtZGY5ZVd1dzlGd01URXd4cDFPdW8KLS0tIFdpVzF3cElWejB5UC9YM1dmZjE4
            WXIwRXBubzZrQ3ZSNDFERHd1SGFNVEUKH5ajOq4tLpeDf2xCFCNWx1/qZYt/AbU7
            dfqXm34dsZIUTw1dPVntD4Ngy/BxSaBr+PHb4GI7qfW89bNc1x895A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T02:29:48Z"
    mac: ENC[AES256_GCM,data:5bjzB0MQJZC/+fN/sv8uSl3vPPd4wHMG5a9yG0m5acB2qBQqiG1MUENQB0pj9t+kldG3wq+RtTAkJlhEwBIIOyX5USLZlHRdLo38ZDpFbEiRey1S79Bd5O2HpbDrOP1aWvyvTP52h1lOVMX9Cwa0i8WLxqYYkGZykoh7JFPNs1o=,iv:xebL0E19f2KbAM6btTffxRUij3cawI0IlYdq3U4Po3c=,tag:4L7Gsn4zRZ3VqHGkQyA6rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
