# Encrypt before committing:
#   sops -e -i apps/officina/base/pull-secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: officina-pull-secret
spec:
    suspend: false
    secretTemplates:
        - name: ghcr-pull-secret
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:B3f2OmBfzXbzWSXlXe/xJHYGuTNL4Ya+fXj8sQC5qeRS5TkP9Cff1kIHG1rqmmRE0E+vBkOybGQntUHXyhxFdnrmY+tFepU4Ia41kRXgrC2ebCg3P6YmvVeqUCYMbz+eC0fk,iv:OrMC+q5CF1+QY6PnpQj+Wa+f4s+xoqTWB1rEoEfe6Nc=,tag:4BNf/jxiJaKP9kYd/sHhZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSGR3VWVwQ0haVkZpb3VN
            VzV1WFBpQXZTaEwyWmFvZjdNOEFDU2pOT0ZVClMxOTQyRHpCNHdjbnlZWHdVbXJu
            d2RZRUozVmdxZTJYTWVXQTRGTmI4N2sKLS0tIFJPVnJna08yZDFRc0ZxYXBtRmFP
            ayt5a0tETVBtRkNNbHFzai9TcThpcTgK1GEgia/7uOv/IA68IvxLM9OzqgaKLEWS
            y22JydIp/nqu5P3tbCv0NK8dWNHBmzI8yVwFRGoeh+edYJXbMBQbCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T04:14:13Z"
    mac: ENC[AES256_GCM,data:tQk7aPozGBaG/V8s5qN1c6sQ9GkiccRPnFHtB5KEqHh9nXtXUCje9dJG3JNiS3uOHyBbqhVOqohtRIEQtRS1uN4aEFZkcIHXfDHo5f7AWuS1L3h5uO8mmtj5Ewc9W/axrOM6g7076PspgkbbzGplpN8qshQF9cG4aDfgoEAUYEU=,iv:BsIvCkLRfp2XvPmYTzvPplTDVPxgELvImvTUJp3mItQ=,tag:cVb1zsED56UXlxhITD1eSQ==,type:str]
    version: 3.13.0
