apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: officina-workspaces
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-officina
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: officina-state
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-officina
  resources:
    requests:
      storage: 50Gi
