# Encrypt before committing real values:
#   sops -e -i apps/officina/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: officina-secrets
spec:
    suspend: false
    secretTemplates:
        - name: officina-secrets
          stringData:
            GITHUB_TOKEN: ENC[AES256_GCM,data:wvK2hWuVjI7KaS0JdCYbV7OVfqSq2WisXzu+sF2ZgmIAdjfxwp2JtA==,iv:1DJZyMhF4I7GDigIw+wQNSPOgPRr3AvhJxa1WCk421A=,tag:tAe5eUdfdpNgirbHNwE1YA==,type:str]
            NATS_URL: ENC[AES256_GCM,data:hDy592UZcFWGi/ROenhHLPhhxWm/QtIC8CQj9Ql72cHXu7dj9k3I,iv:N/9Ybxl982UVjAyVYw4KdrFQLJqubGvEpTvdxxLpSKI=,tag:9XjEL1u0x/CUW290T9TqqQ==,type:str]
            KIMI_API_KEY: ENC[AES256_GCM,data:b3YTYLt7jLBAzBNCNvOameHO16sThxC167TPivX+HOQK8kQcXp9vvHgLpev3YjIakVLZ/EXN7mB0W4+nDhI/oKJpMNGoAvWz,iv:EwdchOz8I6TwkyrSFHV7LSGJKHUtDmZn6Ig1Qxwi+hU=,tag:ezvGGCUna/kbqwpuwy8beA==,type:str]
            KIMI_BASE_URL: ENC[AES256_GCM,data:QkfLJqxom/9FHepD9OUyEAxh1a99lRJyhZ6L0bXkUZUvpZxUne4teiG3zRXl8O8=,iv:PYg2Axjr0v4nalllykj2BnirVLqHZuTlT0Rpvhun6Ls=,tag:BlpXLVw0FpLY4Gk5noGe3w==,type:str]
            DEFAULT_DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:vSxPd4lAiHciPzL/zl6rzKs8iBmX2PkRpchyMKTfE8NNvaDZ1Z4uHy2ww8JYsw+1BYE4fzxtkSS3rpcWoqXmYC8kpz5EUpdH,iv:nAJaleTlNFCxT/ApSzKk2BhUAbnj3wTNjEwPXdiYw5g=,tag:jwChBjDC7CaXKdDHOSz3JQ==,type:str]
            DEFAULT_DISCORD_GUILD_ID: ENC[AES256_GCM,data:GivrT2hKjM+QTijX9U3IREwufg==,iv:VDQ3s8hpN/gDZTg2IzkPbDCyQfTl4m0Q5i6Sz8+ZJTU=,tag:p8Jy4wlhIZhVIOu2nqhAEw==,type:str]
            DEFAULT_DISCORD_AUTHORIZED_USER_ID: ENC[AES256_GCM,data:mNFbkaKiC8u6dOrGBIB9mKoA5Q==,iv:IZQElHZ7T8xe2CdNyeRJAdfeePe2aWSnp0aKHk4WDqo=,tag:xprBMpBKUwzrA0SFKe+O+Q==,type:str]
            DEFAULT_DISCORD_CATEGORY_ID: ENC[AES256_GCM,data:Rugk0FDZQ8oLjjCClKkxOf5xJA==,iv:QWS8Atu+/XcpzqEQ+Pf0Su4C1QXWd1ygV4X07ynQgc0=,tag:7MK2cXU8aswPrBLv5LHVMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQVVtVWlDRyt4eDlLaDlZ
            UTVvN0hkbUFvc1Y2SlRGNWNHdzRHbTFkekZzCkpMc1B6ZTBBZndoaFVLRDlPUVh2
            bVlzU3NnL1hhalpJRFpKRkVreUsvNlUKLS0tIE1FelZjekpNam1UMnZvK1MyVWZT
            WFJoQXMzUXFnMHRQV0E2R3R2aFM1V1EKA4BonYrrP7U0Umxz1ZhoidkAgzEQ6YC8
            23cST/I7dlE8S2Wu6bxYU+8qsjRt7BKegevoZBWbnqm523sdty/HIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T00:45:29Z"
    mac: ENC[AES256_GCM,data:kfW3TryQRYT13EYgLTNXydjCuFcM/7WJ2D2mJmmDHK9ESwlwtgrvTqz9HPap7e4J5gp+OQyKdfTow1LuXU21yxwnpQKZe4qtergjNuYyp8vJtOnRxfrrcfXY1+WC+btTZwA2A7Jxka+B2cazVgPD9oAS69vblzELtBFnqX83Qzs=,iv:qLU5sD5hwjLphSypvBLNNJRE/ewrOYRWqocqBSraXC4=,tag:kazqFskM3U7No6faFb+pAg==,type:str]
    version: 3.13.0
