# Encrypt before committing real values:
#   sops -e -i apps/officina/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: officina-secrets
spec:
    suspend: false
    secretTemplates:
        - name: officina-secrets
          stringData:
            GITHUB_TOKEN: ENC[AES256_GCM,data:JfDVVVhP1+dLwmz90ebaRJW9lnE+fWRDAhZT/fEV+UtDw+zPkRUJlQ==,iv:MqTyBgixvDZeV3wlYSOcLkUF0ZJlb04SYifVqWhp1yA=,tag:vlnFR/zXKlzlHj9VJWKyHg==,type:str]
            NATS_URL: ENC[AES256_GCM,data:n7gWwjo0/2RPR6mb5a8lXTjPij010h0oKRq99gvBLCNzLAfGBJJj,iv:rOXuvyaJ9mHpVQ+qHEHktmPBV027/nEyiI8oQU3dvLE=,tag:6dzp7Y+Y+FhxrL9IUIPXgQ==,type:str]
            KIMI_API_KEY: ENC[AES256_GCM,data:buE8owzH3S00iEevuEgWJ7SIdpNik+Dmqs2dAZ+gXEU0N/iXtKMEnIUp4LhY2WrjAF9rOGHU1yv5+7zFu8PGD7ajb5R6ewp6,iv:wwstcF2BzWVz9+l1EYBZwOOSSNodU+7thmZtloNXrP4=,tag:yZsyuG2EtKST4UgcjYMS8w==,type:str]
            KIMI_BASE_URL: ENC[AES256_GCM,data:tBVLXXy9qGnx+4RNN4ECyFwXI/XK25h3J7N6ibGRadOv/7UgKok/oUWrd5KQfX0=,iv:GD158GzbGGaFqWT49N8hQfH5Hxde60SJl+SiIU2O8ok=,tag:bsL3OmaIpnmAEjq9aPE7XA==,type:str]
            DEFAULT_DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:dlS2jdl/tKnCxPfuitRk8EIyGjtZT5dVy2mGQoXE2rkeSnC7qk2Xb7WerMvrxNBCq00e6dKNZMhtTfllMoDnZ/Do7Aw0Vcla,iv:di1Lp2QR+YRnOBChiNCyYv7uuB/QnrY4/3FcX3fXFjI=,tag:LXlCuHErR3nN6LPhTkl89g==,type:str]
            DEFAULT_DISCORD_GUILD_ID: ENC[AES256_GCM,data:K8UaG5lQ96FSKfjm42mWEmgEIQ==,iv:clGnKOGKvZ3vl4FQVVQxHJfFEyIWiKyM4INxhpbf87c=,tag:LU6j9yHn7PXvj04aJ9/GyQ==,type:str]
            DEFAULT_DISCORD_AUTHORIZED_USER_ID: ENC[AES256_GCM,data:IT8OKZwIr9/ogWXs4H+4YBstbQ==,iv:BzhGtnaczRhLBaVs3YBZNyCuboFH88ckjpBfEXzNPrs=,tag:37hZqw3RDPkRdQ/O/G67SA==,type:str]
            DEFAULT_DISCORD_CATEGORY_ID: ENC[AES256_GCM,data:p8HoTVB3yqJCCeyGT/iUuKjUQA==,iv:YDtnuDET/ZUny2WHll5+i0D+h+4vsZ2TQJT1eQIdMsI=,tag:r9PF9LvEktI8+fFNcGcBdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK21DcFJRUEg3WDhxWnRL
            d2hTNHYwVllVNlpEUVF6L3B1c1ZKNHEwbkRzCk1hVUZHb0NqT3RacEczcWNPYm5C
            VkFUWnkwcmNlVU9QSkxKMUxhSWpySmMKLS0tIE1Wc1h5KzVBeU13RVE4THNxNmFw
            MzBFNzNKQW8yNEorSXl3NmlmL1dyTUEK5PsEsnuLeEH01vZYiCzst0y7+nqZn+G7
            ZXhEGwqZpRDxCEalEkUN4KdKeygxNfcJjibe1aZRs1Elq1VoXlMyNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T08:54:26Z"
    mac: ENC[AES256_GCM,data:jW39yKtD2a9abNrnQKGkcQFx5Gawdf4XvL2YHMKGWLlWx1soUt7Jc5LPEfRMe9FZrJDtCXs+xOsrmxNddqLqjAvMqLUuNndm7naP9ZxUydiCmCdpEi5jDd9RqcG0GWll52MrD/IGz3C5h/ipl4JohJHnoDbOvOhEgCr66hBJYXY=,iv:NDvgi9bTbr4Dt/kM/twxKk92VT2We23Iz0wUuqmuzUQ=,tag:HcQ7LVN5Ws2Afzv3R/gHnw==,type:str]
    version: 3.13.0
