# Encrypt before committing real values:
#   sops -e -i apps/officina/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: officina-secrets
spec:
    suspend: false
    secretTemplates:
        - name: officina-secrets
          stringData:
            GITHUB_TOKEN: ENC[AES256_GCM,data:WGJJrm6rIjzFeI/beMHj7Xe46yQShn8uxeSNByCrlS9Rixj6YS5IDg==,iv:PZ9fV1JAq0xnLuLp/HzLWymIY5OZuOFB1uvH5Bn9Ljs=,tag:EXZ1WLSR/juQaV0XYGAHTA==,type:str]
            NATS_URL: ENC[AES256_GCM,data:msP2VWDm2LyQhIjubgBoPfBl2YwB+0d0Kjsh7zHlvdOGm5RCZ8Ec,iv:yOTBwJCx+wVEear4DmnBX+b/QCbVVvM2+5keS2QgxEk=,tag:+zDGzJ+N8tpAYQ7mROCWkQ==,type:str]
            KIMI_API_KEY: ENC[AES256_GCM,data:ZNdK8aPHxajmST7GwiApAqOoGTBLmiKj+W+fckTMRODwsgF+BrGRrLTelb/z3fsF2hsahiv1PGSvOv8U1HlAbbgXAzRC3jJV,iv:A3Duztyj4EwPCgGOo97RatM3aq3vNg7COA7nS6tMPCA=,tag:J4lhmAkJRRcD0zGxOR1YVw==,type:str]
            KIMI_BASE_URL: ENC[AES256_GCM,data:fagv3uaVcBnNSdiZAnLc7s6UiWblzC728ek6jwa4QlJ6he71cG1HzfdBlQcUamg=,iv:Wzt5K9vqDYku4CZSbiHUjdvDGhue+SfT2uB20rPchIQ=,tag:CrWjAphvmAt+zXYzv4ZNVw==,type:str]
            DEFAULT_DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:9Dw65gh+TXwyQuHJUDW2bRozKFzy9Rkx2HWIyYcYeWnm5zBAShKS2LcISyZtQ5j9GYc6DA+BTiMyeJ5Zx0ZI49GGgHxlSPbE,iv:X46Q9B0XOU0F9Oax2TxaOO2Jk/GdknPL6Itvgamv2pk=,tag:0ISOq7MNuNSHnU2TXhgcXg==,type:str]
            DEFAULT_DISCORD_GUILD_ID: ENC[AES256_GCM,data:sVJmo/eQtOCu003ODb0CQj08+A==,iv:19wknqjKQMiVf4PeQn1yF2bxJgkyKk5yNYm4oksE3n8=,tag:fKMGMmMJVKB0fbrExtMR+A==,type:str]
            DEFAULT_DISCORD_AUTHORIZED_USER_ID: ENC[AES256_GCM,data:oqnt92ahojDbF/smDQu58fONEw==,iv:jQIo4XDl77VtBw8X7QUqEjybha95JN4Gs6xTG5AubY8=,tag:Mvc+2YezIp6TfBN4cXqqgw==,type:str]
            DEFAULT_DISCORD_CATEGORY_ID: ENC[AES256_GCM,data:1QBxl4qotWi8rBltAWHDcZunKg==,iv:e+Ro50Au2yli1vY/G1/Wc7mFxifFGrs4OoOwC2aVuyE=,tag:JZKu/HAsrIy9Gq0OrK7Dug==,type:str]
            DEFAULT_LINEAR_API_KEY: ENC[AES256_GCM,data:6AYC9W98MlPp9Pq6ruPDeLlm+RdamLvbSWjZ3rdvbb2A9H93ZAPIdvRDqM6ikwZu,iv:G2ATpY1Mtjmtmieq7zzWZh+xGX0UYIA/khbWUtocCV8=,tag:q/kpsY5iDQuCK8Nsim0n1A==,type:str]
            DEFAULT_LINEAR_TEAM_ID: ENC[AES256_GCM,data:gLSAof5sWUMNMeDA8KAXOWGWTdF919vjekTrht9nDnz56u/Z,iv:mRIDOt7+lfLmVPxPiNxwEf5sJ61McojUHWWRbHv6Skc=,tag:1/WDZwWqnpqcQgls/nXw6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaVZJZ3pScU4zdW1ldXVw
            eTRFYitSODl2Zjl0QmNjbGovUnRlS3VRSXpVCjMycFRseXl0WVVTM0RSOEU4MnVQ
            MFZjTm5jbXo0TlRocmJDN0loaHBkVG8KLS0tIEpGNlRHdStHNHppekd1azA3U0tX
            RDVFSHd0bXBpWGp0RU13Vk4zZUFRWUkKky1rrjaqG0vE+G01shg1pmJ00E5QNbL7
            8BfWLQVQ0VZKXN2KiuI4rdtRJTj1un4R+BiVL2YiMKgAP1CnwCNmVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T02:20:32Z"
    mac: ENC[AES256_GCM,data:ld2vZ4JFlevV+xNLvNjmPsVT2SFVdSNvgQj1Jwt2Sjk7Y3jEVNzTAeQcoQR+Cpc3gjcj5qcjqYJP/l/9d33YK9ua9gXwxHE9UMTyY+SNiDC9lkg/M/LLOmLMG6uCKAZMvuwwtp0M04vfb9qQesMGDk5DOXNFQjqhtCIx2k3ZkJA=,iv:UXToPqLl4LqgEcazhVtT+slhBgVVUChgeFiy8aNbsVc=,tag:LkFH4h1Qg0idAaILfDJ+lQ==,type:str]
    version: 3.13.0
