apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openhands
  namespace: openhands
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: homelab-gateway
      namespace: ingress
  hostnames:
    - openhands.elposhox.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1
      backendRefs:
        - group: ""
          kind: Service
          name: openhands
          port: 3000
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ""
          kind: Service
          name: openhands
          port: 8000
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /sockets
      backendRefs:
        - group: ""
          kind: Service
          name: openhands
          port: 8000
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /alive
        - path:
            type: Exact
            value: /health
        - path:
            type: Exact
            value: /ready
        - path:
            type: Exact
            value: /server_info
      backendRefs:
        - group: ""
          kind: Service
          name: openhands
          port: 8000
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: openhands
          port: 3000
          weight: 1
