apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-data
  namespace: openhands
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-485a8073-6932-4aa7-acd2-caf948e76791
  resources:
    requests:
      storage: 5Gi
