# ⚠️  UNENCRYPTED — encrypt before committing:
#     sops -e -i apps/openhands/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: openhands-secrets
    namespace: openhands
spec:
    suspend: false
    secretTemplates:
        - name: openhands-secrets
          stringData:
            jwt-secret: ENC[AES256_GCM,data:es9/jVar96PEgZqyFPUJ0FJxrlAs0Yy2Zs0ujrbxfDKbgG7OFcVzJuiPsFuhZ+F/19vcqZJLy2kJq1g+KWnYlg==,iv:JSVGJksUp6hhSEA+2+30f4hJxWsgtYS6/SiPaL5YJHY=,tag:vIUKOHMB/S9LwDmhJJjg1w==,type:str]
            litellm-api-key: ENC[AES256_GCM,data:+L2iWoLygdQLmoUCZvdDYY4iE1+2QAeyDw==,iv:3iK++AeCp3iu7ACtCgXf99IC48+EkwdUz+dDABOh9O0=,tag:O630tsAKKC8Yszxua4MU7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aVc2cnlJRytkU1F4YVly
            aFhTaTcrbDhTVHphSjNPQlBwdlFrRGRsSkVrCmdwa2xHT29VNkpzQzBOMlM5dGl3
            bG5maW1lUFlKVlVXakZiU2ltdXkxZncKLS0tIG1pUXQ1cUdMSHpZVG9YVzBPVXN2
            OXQvUzRhUU01V3pwMHpDVVcvamVtZ1kKT9E6nm+G8loGIBjJusQjzOn7Z/pG6JUd
            nCWKUX05eKTfmxdxZew1e0K4QTCR6vFu9AUGBSLi27aFQs9ATDrzjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:56:12Z"
    mac: ENC[AES256_GCM,data:7+6aM5G2sskpodPVhwtCnOb6JZzeKC5ezxGCVV0x0maxNU9Ln/9etW2edoZhPlz19/BSRjJfoPeEIvlP97nuwVIi0EHrDnCYfi5lHcCajn++cAaG2OIwBejPm9cJPfzD64WQYDN43PmEfLCvMrmzCdmVvAauoe9Ye4IpZYgXNIk=,iv:0PyZugtsSUDjIFxBiLBW9qVk5PvhWMsTtQfsnFSbwqo=,tag:ijC+iazL50S/gyi+XS5VFg==,type:str]
    version: 3.13.0
