# ⚠️  UNENCRYPTED — encrypt before committing:
#     sops -e -i apps/openhands/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: openhands-secrets
    namespace: openhands
spec:
    suspend: false
    secretTemplates:
        - name: openhands-secrets
          stringData:
            jwt-secret: ENC[AES256_GCM,data:KuluGW7wtDQ1vQZjSaNB54owW7HUIhfq1trXLoGfjNqUEjAXHHyMCFMEzZrES7af1OqMo7Rx8meKQHQUlum4Mw==,iv:+AsB8d/mr2nQJYzHCkWaGTny+1KsRxWSNdEVEPviSVk=,tag:qqgnMU2OIoWwQN7Q0qbbpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1BMWFRPcFYwS01LZGxN
            bWl0MGpuMG9hV05XNEtMYTJNdWNCVXFvWTBBCjJtRU1PVkVQVnBYSkFIMzVPQ3Rz
            N0lvem1oVmRNWUVsNUVwa2kzOFdMNTQKLS0tIFNERGIydE9wdVlrdkh4RngxOXdu
            L2RsbVRtRzh4V1JxNWFONlJ2cjA3UEEKaTND1gtYpmHF32Im4yLHfLzPkpWsYweL
            +ExfmiDntD6snh66lXLl9htqLyqZufG3cG+jLZYTH5PwztOjXxLKdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T20:57:05Z"
    mac: ENC[AES256_GCM,data:2gGAX2+KhZh8K6fFMCSKuRoELPOBLs2/ISYrGlNpk4EfPnZdagwZV+GsgjJfkmDfQNg8nnig6llvcmlvHg02KuCaiIRfzBz30uYKA6g0jLJMxMkz1SP148siQlAJdVrAfx1WaaDNhC7KaEE3kfO4dEfnzWC0k/dBi+0lS+C3Aw4=,iv:cuX1JzbRTcsPlZcjkMARiGew2Da9Rmg4Kh14/kR0fjE=,tag:e2OSr4nNdvs/cZR9DxHWHw==,type:str]
    version: 3.13.0
