apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: metrics-server
    homelab.local/OwnedBy: ElPoshoX
  annotations:
    argocd.argoproj.io/compare-result: "skip"
    argocd.argoproj.io/sync-options: "Prune=false"
