---
# Source: traefik/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  template: 
    spec:
      containers:
      - name: traefik
        # volumeMounts:
        #   - name: certs
        #     mountPath: "/certs"
        #     readOnly: true
        #   - name: dynamic
        #     mountPath: "/config"
        #     readOnly: true
        args:
          # - "--providers.file.filename=/config/dynamic.toml"
          - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
          - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
          - "--log.level=DEBUG"