apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pushgateway-ingress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "9091"
              protocol: TCP
