apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homarr-secrets
spec:
    suspend: false
    secretTemplates:
        - name: homarr-secrets
          stringData:
            SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:ZesYrkNMmqwtIRtde+Pdah4/vYrTQpLIOmWfYLc6gGY9KDF8K3hBaNPUUt0qwpAydCfZO97iD7ITIxtCHz6Ghw==,iv:eggBqpB8RHLmX5ge4t3MMzyRrXN6q/FzFLj1YvO88Ps=,tag:bOx4y25Jw/hnUd/+R8hgYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMkVFT1pmOHVnajNtVTY4
            OHpmMks0SW5VV1FhNzhqMEpncnRFUnFtcVY4ClF0NUJtTTV6VUFSd01kTnZxUFp3
            R0pGbGJ3UDNlNDJMdW1WVGlpQ0I0UHMKLS0tICs0bDhrUHQ2OWk4SklwYVFzSXhL
            dDJXUHFXekxvbFh3MVlzV3JPTW8rancKHpD/ozJ5mHVmTeogvIIzAKMxfYzL9Fqv
            o6RCJVh3vO2n9q/VD/n7CJFeoQXoOH+qsKmmdRvQkROwAxYmd6IIMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T00:37:46Z"
    mac: ENC[AES256_GCM,data:PFkwyAkggoHsQDc/5geRKznkTmB0MlVF7MWQWdlPEXgyG8Ci0yMIs0aklmGdZU5IqQm8DlQcw4pOHzP1I7gVh0PUKgW086VDYHvsg5D3QdODfIgEQnc8vdmRl3Qn2Mm+lte6vpOlM7o45pSlfJIzsTLbWUrSNIIdYJ8dKT2Iod0=,iv:8s1Bm3uLYl082QCESKms4Au34f4Ca0U/uVTwWxltCv8=,tag:DRq0DA+PzKQp8mL1Zf8xYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
