apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: grafana
      homelab.local/OwnedBy: ElPoshoX

namespace: grafana

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    version: "10.5.15"
    valuesFile: values.yaml
    namespace: grafana

resources:
  - namespace.yaml
  - secret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 1
