apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-secret
    namespace: grafana
spec:
    suspend: false
    secretTemplates:
        - name: grafana-admin-secret
          stringData:
            password: ENC[AES256_GCM,data:yxQC//UvbYGPxkkwBs+FORx1rofgEbSeEIDyT1BQ,iv:FNLUwpadpAapSt/O0PMAF6yiF5IEGzbhqAg8/xlEDTw=,tag:YeH8fBRnyGliG7gD+NaezQ==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYzRGaU43V2xXQk5OaERD
            dHVYYlR4czZVa25vdVhKaGRNQlRSOUQwQUYwCmV1ZGdtak9raUVzUXpDaXgwM2c2
            K0hLZ3R3OXJ1a0Y4Vk5HVmt0WDNvVzgKLS0tIGRma3o5VWNqUkdvTUx2MEhabEJM
            bmhiVUcxS2d0cnUxOTF0VVFXSHNRMGMKbiVgcwM7bjNO8ixu53DamM/bVYcVYZU2
            sKl/QBBp4gvOo1+848wVTkocv9BFuN2JRpZU3As/Rm4bo1i10vJ0lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T01:19:03Z"
    mac: ENC[AES256_GCM,data:nKt+pGa10zt3XzxoFfILzq2IIL7jy+0IM01qIN5onW8qb165y98IXnteAaWeN4tAvVB6nz3K2rQVhwPh1o5K+9dALDtOpebekURzGWfbaz47TDgxK9oaVYHlnqd+yx9Qx3Gzecp4aTgWnNJD7gvK4+1pHkw59JJAJHdNWx0GYqE=,iv:urSOsj7zVvIoUsrjDyfRF31/m5st1KlDBtM5As/iSt4=,tag:+cDpGNzbQ/JFlBDOr5+nCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
