apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: moltis
      homelab.local/OwnedBy: ElPoshoX

namespace: moltis

resources:
  - namespace.yaml
  - storageclass.yaml
  - configmap.yaml
  - secret.yaml
  - vault-recovery-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml
  - servicemonitor.yaml
