apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-moltis
  volumeName: pvc-8f0859a7-5bb4-4e5c-98b7-ba7db38eb1fd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-moltis
  volumeName: pvc-4878c6ae-c788-4673-bcb5-f51dd9a00879
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-dind-storage
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-moltis
  resources:
    requests:
      storage: 15Gi
