apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-moltis
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-moltis
  resources:
    requests:
      storage: 10Gi
