# Encrypt before committing:
#   sops -e -i apps/moltis/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: moltis-secrets
spec:
    suspend: false
    secretTemplates:
        - name: moltis-bootstrap
          stringData:
            MOLTIS_TOKEN: ENC[AES256_GCM,data:c7mv21P4Ar4UtGYRBkcYp9/JqecP7M5WExbamc3qT1o=,iv:88+5ZBYXvgrmf3a0VE0TVyBfX9/0hSQi8/dx1STaMZg=,tag:SaOOpr566SuM0s86nJOolg==,type:str]
            MOLTIS_PROVIDER: ENC[AES256_GCM,data:T9WzEIeccrd6,iv:dw36cKT1eGkkQfxmKnzLjQBhmVNXhjqEbsSeelMWwpQ=,tag:+HNveU/alLpcT8wszAo6bw==,type:str]
            MOLTIS_API_KEY: ENC[AES256_GCM,data:ail0Xcmx/tcKrn+0vD1wcngeE1E0ysFIraPYyLBH,iv:ICfsf+g0qvDT9XLd3am96ySkxMlOSeMTF8C1JrChkOY=,tag:gruA5n1b1dOMki6lyUJFvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cEpETzhOVHg1TXlCeXVL
            RGt4NnB3Z25PMml0dzV5VzVqaUNhS2ZYb1I0ClNmcEN0M2pENkttZjJRNUdYN3oy
            WEhqVHdwQlRPR3BaUkl5VXRmMFlINzgKLS0tIFVONUl3VVRYU01KdXlRMFZ4UTY1
            M0VtV2xIUmw0V2Rld04vR3IyQmhjTWMKLQPP6EztQHEYAfwzXXOjculnv/ce4KbZ
            AtE10LXXCp+hdDsV24gMg4BeWRL1oRitTAm7itUd8tUyOFySmMapxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T05:15:02Z"
    mac: ENC[AES256_GCM,data:RdChkdYp/mSn7QpDuAcZUoPIdtRcFec0T+dqT3101o/vUQp4UJSHoPoJQNSPkvw8EkzbTsnhKoUw7Fu9e8i1rgI1oQWWY88CzJAzNgQnyTLI+MfPGeJ4pL1oYtCmIHIN/MsJV7TY6EJn4ibWzp70p0EW9eQF2AFxcwEmxX99OYc=,iv:w3mZ6SVrlpw1PVHfvcHg6WG0xsI7rXKUkuZZdGJNaY0=,tag:T2FVyAur4PfJuFE7Jsb2nw==,type:str]
    version: 3.13.0
