# Encrypt before committing:
#   sops -e -i apps/moltis/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: moltis-secrets
spec:
    suspend: false
    secretTemplates:
        - name: moltis-bootstrap
          stringData:
            MOLTIS_TOKEN: ENC[AES256_GCM,data:7jx7WEJ7hZqfO2Yx4iUdUDGQBRMRpKf9BamVUha9NCo=,iv:6ZbSIh1aXAX6YZp4CHchDlBoEsx4pM6MgQkwbxnJRmY=,tag:A9OKwuXZklfh5rKYEIn9eQ==,type:str]
            MOLTIS_PROVIDER: ENC[AES256_GCM,data:OpU0FwFHq6Pa,iv:jiM3bL3jE5RGkVZy5dvLgdYPi/V7oOPamGrtJjocLC4=,tag:9JnUUID5mA8GrmRpafIPPg==,type:str]
            MOLTIS_API_KEY: ENC[AES256_GCM,data:xcSLBf0QHj7Si1/yxCUlWOZ4CKERNNw=,iv:bJ9EsybaAl5BxFi5vIAOjhwiivp2NefqhEyfHZ5Kxxs=,tag:Ib0tNykCWXQxIvHUVQcrrQ==,type:str]
            ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:wpG0IL4EGbn14lbqz8Fh7wTpenHcIIxWEYvsUSCcTaj1pBB27lrfvG25lfunv8GCDt2D0bk=,iv:55X9hlmPR5LLuuE++UNJvwG6TSTWF1DaZHewZ0bfHCI=,tag:Jk7o3U6MprNEmBhLz4DUlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeXhVblFIVWNkbE1CS3hj
            YmJZTjFzakQzNXAzUUtGTVQ4Z081SFdaNmhjCnI5OE90T3IwLzFvTi81SHpiSmEr
            MWFLb1drR25YS0R3NVMxQi9qcFVOODAKLS0tIGIvYTU1dlZlYk5WRks4ZUY1Vk9T
            akRBT3VOR1dHbmJoUU83aXdpdDl1QjQKGQcEoz1+I00e6rQaO/q6KvOjKLeFJ3bX
            HUx95kqLTAJxW6hg4bCz4fVKMySI1vTI1SDDr3DIyIxOrpXqDBDNZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T06:32:48Z"
    mac: ENC[AES256_GCM,data:nMEmmzHDeo00kTYu9mvJyhIGGCvEUSXIQ1abDV61TM5hvBIAHdVpndYP3SiAzua5iDgRRSC6u+0aD5u87hAhvKJDmgnJo/Etv/Tu64vhdM2ulRnygiMGcLv7Byan1CjB3SNatK97WXktMt55++q5Ok+gyRjKYtqQF/eE3GNLJaQ=,iv:YGbKRqS+9hCZenvZ8EwlD3BcGBEiqissbCIbPZg1u34=,tag:npxv4iQHerExnth+wp0wgg==,type:str]
    version: 3.13.0
