# Encrypt before committing:
#   sops -e -i apps/moltis/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: moltis-secrets
spec:
    suspend: false
    secretTemplates:
        - name: moltis-bootstrap
          stringData:
            MOLTIS_TOKEN: ENC[AES256_GCM,data:+mQYtzgX7k6HtP27ZkNRdUiniH3i+lmGT9kWRwaqM6Y=,iv:wO65vIzZitMzsLm//KieF4ymyfKYdV7iRfeTdGt98kk=,tag:hfItXTrc9foVC7cvKb1xcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUlVQZXVMeWdUL2RjTUN2
            RmZTT0JNaUNuUWc3SEhsSlVRVG0waGtjUXhvCnJaV2VCQXdHSndTTTBDcW5WMUhl
            YTNRTFZ1YXdnT3R5MkhuTDRaaExFeVUKLS0tIDYzb0ptOWRjL0gyQjdhN2tBOUJh
            VHIxTkg3NUxFWGJOY3VrTUU5c2dmZ3MKncC6SfRLR24clNAbvcQuSVP4O7LbuGzL
            wDknMOxR7k8Zd6ruitq1b/ToquavLCuaLIFGP6zCJxi8jhN8IpLaFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T06:03:18Z"
    mac: ENC[AES256_GCM,data:GXdSSZJgmX7NAlC63HA+PML8lCzy3vtRKTjsAn/FrLIJ1bDzhgYM5MqH1ww1IBY0Ua7HklGIu4vv3nyisByDnoq3AE7UecptydyBqT9KzmSFA16WN9uJ9wjqM+EIW9Aa1ezWdpgG9G0BkuS6tq+QLRgTr4zXZHjVNdVREQvmLkg=,iv:c5CzPDucnhmwkN+eADVshGw9acwA7X71bTTOTT9vwnU=,tag:IfSvOgq0jtsjpm6+0FI5bA==,type:str]
    version: 3.13.0
