apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-deployment
  labels:
    app: speedtest-tracker
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/instance: speedtest-tracker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
        app.kubernetes.io/name: speedtest-tracker
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: speedtest-tracker
        image: lscr.io/linuxserver/speedtest-tracker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DB_CONNECTION
          value: "sqlite"
        - name: ADMIN_NAME
          value: "poshox"
        - name: "APP_TIMEZONE"
          value: "America/Mexico_City"
        - name: "DISPLAY_TIMEZONE"
          value: "America/Mexico_City"
        - name: "PUBLIC_DASHBOARD"
          value: "true"
        - name: "SPEEDTEST_SCHEDULE"
          value: "0 * * * *"
        - name: "APP_URL"
          value: "https://speedtest.elposhox.dev"
        envFrom:
        - secretRef:
            name: speedtest-tracker-secret
        ports:
        - containerPort: 80
          name: speedtest
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 80
        volumeMounts:
        - name: speedtest-tracker-config
          mountPath: /config
      volumes:
      - name: speedtest-tracker-config
        persistentVolumeClaim:
          claimName: speedtest-tracker-config