apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest-tracker
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`speedtest.elposhox.dev`)
    services:
    - kind: Service
      name: speedtest-tracker
      port: 80
