apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-tracker
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: true
spec:
  tls:
    - hosts:
        - speedtest.elposhox.dev
  ingressClassName: nginx
  rules:
  - host: 'speedtest.elposhox.dev'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: speedtest-tracker
              port:
                number: 80