---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
