apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: speedtest-tracker-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: speedtest-tracker-secret
          stringData:
            app-key: ENC[AES256_GCM,data:IljkFatgjJwEJDAw1UfPnwkN4sRI+TKCKdUHn2bBU7nZiseuH2xBv/HB/an8LTe0satq,iv:5qAldkmSpJrehcicmJtMvLj4sLHEPQpDc1rzzV7m36Q=,tag:TziH31k40cL0pXPdDIfZAg==,type:str]
            email: ENC[AES256_GCM,data:7d4xsaZofpzDoncJV8FuO0wslQ==,iv:ioChE2Y5z9dZEBwmqIH4PPwW90jPCz0CoE863keBWhI=,tag:5foiBmb2ncqXYQ37vlLAgg==,type:str]
            password: ENC[AES256_GCM,data:/AVFEaLajXCH2UfKssKypdBCkiGkJdJxoXpMxHsyvzkUyMifvBWhse4trWrO,iv:miWtrO6A+HBs/nyN6tLe7mt9Sx6dXuwcMI6/LWl4O9o=,tag:zCjAvqmlMJ47KBIFu33Kgw==,type:str]
            bot-token: ENC[AES256_GCM,data:4Du24oc11dJt0GGWyQZU3KeaO0/BoESrJ+zkky4BOXMbRojK+fvKNAF1pRwW9w==,iv:KJEsHlY+EFSQb0SbszrbIsYf+2z0vJozHZRgxAyOSjQ=,tag:ouUhjmbTWRfuPwdM1hQBzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY1dvNTBKY1IvdWovRi9r
            ZWNmTGZlMU0wa3k1T1pIa1cwVXVTY2lBN3g4CmVhZHdMclVBWGhPTlVOaSswazNG
            UEIwanl0TkcyWmh5eTd5Q1pOb2F3U0EKLS0tIDZLcGQxZHpvY0RuTXViU2ticERk
            L0hieVB2RE1VZjJoVGtBM2ZvVUw1ZWcKspCV0EgkcqqBe2SXv+1M040cY5LHCqFx
            xSTHvjBCfwUWMZ63x07gEYh+Nih0aJ0vpbpoKUN5xTnfy8JxoX0D3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T04:32:10Z"
    mac: ENC[AES256_GCM,data:7fevh1PV4pwrx0oW+MJ/Ox52mljlH3wTbJRRgZgVMNZWAumw73rqHlXTU+AXwRv4bBD8+frXhRBLbdQ2BOob2LnPXPfvGWZpJFPxwMVDUYvl5LeOITWTCbIFOEspmVhlFvBNksCGrurKZwszzmUsbSFuCx5/gQg8dY3e4bhpVkw=,iv:lOrv4FSM1vX4BU7xWGMeBOEGa8bQ+aGPQBw2xh1OJSk=,tag:hs8Fc6Y1kUDHfIRHtPxSlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
