apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: speedtest-tracker-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: speedtest-tracker-secret
          stringData:
            APP_KEY: ENC[AES256_GCM,data:eyPPQA1i/RBDl1SuA+KWPjaOnjdWf1WQ3VQgPRqV/bzW+dRaj7fuk7e1yz/9VNcfair0,iv:zpPH1ipaK/PiAvO8CL4Q1UGVLbJgGxnIyFd+9Jkqegs=,tag:AH0G4K9kmiiL0QOCiZqtIA==,type:str]
            ADMIN_EMAIL: ENC[AES256_GCM,data:0sOWTy65YuLKSJmrlXPTmgb5xA==,iv:qaYRB40XMKf8qdQ58g/iPB480PpOlwhNY8k7AfGeAvk=,tag:t7BF3xVYguGui9RwuNaFbg==,type:str]
            ADMIN_PASSWORD: ENC[AES256_GCM,data:ZOpmfZc8DNmGcz4ZA0DoFcoziocDnHFQkAXb9OYBWk63WJsBHIISe6xC7rwu,iv:qTR63Xn+cem4UMx4vY0xMK54Wp2yVwiLQwj3kyI2BiI=,tag:MUY4CGQmjHoBxipNe8INCg==,type:str]
            TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:NHIohtMBcFuIq+MMlpGf5wDn7Eu5wSKf63dEueNwJrV4xBEJ6+NtBaV/egOUMA==,iv:C9DjibLDwd1T2BZ2eB9bJC952TY1XeX7FPnrALhb3wQ=,tag:gQGKzPU6L/yw5xq33zpB/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYmJzZThIcTV2a2Jnb3ZI
            c0tLeDRJVFZVTHNueHd1aWpwaUMwcVlmaFJjCnlJM2pkeDJWc1RaQkNXQysyUHJa
            ZHgvSVQ1TWphZnFwUTZQdU5KeW9OcDgKLS0tIGIrZ2Vxejg2QUsxc1JWeWpHbGtR
            bUh1KzZxbngxVlNocnFYYStPMU9TN2sKuIjHzaLdjQG9oOMVwG2oktROeRZUcKhz
            kwviFzENcOTYGY3AakC3/m4V+pbCiy+fksxqBYHtVzfkTaCaYIy+3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T04:21:10Z"
    mac: ENC[AES256_GCM,data:m8aBx8uaKGkoaGB6sTRKVpHIwz3p9xG8twEYiY0iOOEIarMRCkzxcBzcR/vmT04h0XjU5sBuSzjGSYxE0RVKOqu7VfeQIwsscvp83ppAYgA+dsxQFLeOBPsjjEGNd39NtzJLFv424kQ/ihK+kkc7IanmBvp7cQ0ExLLeUP2F7C0=,iv:t1To6x4XEBLgFhM/ytQJU7HifxU4IBJ7lvTUobmJm90=,tag:ARcn19cHhepHB7eOJGc/RA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
