apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: speedtest-tracker-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: speedtest-tracker-app-key
          stringData:
            app-key: ENC[AES256_GCM,data:UGUIPDg830mFW3MNF1FhDUWeI+0k/aZimrwTISs7y+m5wW1kNQV0jl4TMHzmvK0vGJK8,iv:Vm/imEPAjuZ3XnsB6/w1EF+C9VAu0AUX+UzZvonWIOU=,tag:aWtmrVCA2ygThcLPaqOwUA==,type:str]
            email: ENC[AES256_GCM,data:PO3FzdiBcOWwinsfJ1BWMrAxlg==,iv:tfMJpsz/UNwCMmmJWoT4kSbFf2XNxGUYhI39FUfLkcw=,tag:hLcRXbQThLNTJlC/MVxdTQ==,type:str]
            password: ENC[AES256_GCM,data:jObKmkq70P8QD7F8VVzmm1H/PwJV3LwWWyoEah3tG7zWeQDSii1+VClVPv/u,iv:+lcRHZ2pyXaiFR2xPb+8n/FnT7Re0B/ieRnaEpx/Rng=,tag:1WNu2cvfbi+qN+caLi9/wg==,type:str]
            bot-token: ENC[AES256_GCM,data:JEZDwjVmV+S0iuMR4tXRwCUW2MQgdI6q4Y7dpf7+1iuFjHwgaQCrb+Nf18s7rQ==,iv:FKM8DMWodlATZJjk1aKlTOkJh3U0iyzcv2Y1VS6wyW0=,tag:uttXu1B+SsRkw3JdGkAd2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1unhax45cm95ngm2h984sq22v7uxm7rtle8mlrg4mfgs55t2kr57qxkxyml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQXlpWDVjVW9QNWdDV1hk
            STZ2ZUQ4aVZPL0ZXc3QyMDYxT3UwN0p0SW04Cmg2Y2hNSFdnZzlrd0czMTdKWGd1
            NFIwOVRucTlrUGduSk9LVVNqeGM3ZU0KLS0tIFdTSG40cnFQUXNnR01JVzdQTzk5
            ekdnaWNNdlRUSnhJODZLYnEyNTBnb0kKBnzdK+C82BPSYszIxDWHzbmuGRDgszaC
            wzfb6kP14eaCxlj8p3pMKAyrQ9ooTpAW0n9YWsBH3zE0cyNME2zpSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:45:30Z"
    mac: ENC[AES256_GCM,data:baroST4Y/0ZCNN7N9/X1VLddrVJ4zRLGckluT03ggG0BHTrvuHfeK5dPw/9IZu/V/NCmamF5NxNEVU5O0+gQADHA3V1mcHWwGXWowEO8WVFAsg+u2WOVWzHPdFpb8I41Q3z4NqVke8ZBU/ejvcyKf7K5U8mgG6n/HdlfLjexfFI=,iv:bigVBg/j2m+huxesrKdAW2a9UoCLluE0cGqsf0/qVRU=,tag:sdFS4f0r9/HBvFXCZgAKfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.4