apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: speedtest-tracker-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: speedtest-tracker-secret
          stringData:
            app-key: ENC[AES256_GCM,data:VmDhRt1FDERmOATflVbdfDAUY3FEIvCpYbhXPrsvJO7yrLGHK75P18LVQ4Y/+BPaxkQ7,iv:mgzV9G0VSBEVRznytmJZKiMCnz4HcXiKqe5ixY8rJrI=,tag:V7fUVHOIUOCj6wY7Ds+mqA==,type:str]
            email: ENC[AES256_GCM,data:39yyvOFnH6Hq/DcmrLK2z97UCA==,iv:ZrC1n6gp2regFsvJFO4hNMTmXHsYcmDO86YkTzX2lzA=,tag:O41sY7pDavugSF98XrngAw==,type:str]
            password: ENC[AES256_GCM,data:DLyPc0TKl2eJSiCHsngVasrqUNeGinFuC87YXsxdzqUlrA5fgvhTMR5zHq52,iv:qgr1zVhlktF6e1cPE6q6/OrGLOt9tH9/gCsTKvuC8tQ=,tag:N8RP1i2k8lqjhd0jjP2/Xg==,type:str]
            bot-token: ENC[AES256_GCM,data:xcEi2kvKgemhngcsnCm/1/MrtVrFtVhS6CQtv+/HzzVj6oLwY0ciuro54NpJtA==,iv:gOpgWU/8ovix/tqhjEUM7CYlR0PMOey0rzaixQRYQps=,tag:pESX4jyV+Q57SKTDwAFSqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1unhax45cm95ngm2h984sq22v7uxm7rtle8mlrg4mfgs55t2kr57qxkxyml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelpDUExqRW56QU92RG53
            MmJ5SGM1cWJrYzlrRUNIRWxVeFo5R2RHYkVrCnIyZUduUkE0NlJSZTN1OFBwMmF2
            YXZHV1RoNTVQTGhXQVF2Zy9pM2ZoK2sKLS0tIHJneENPNENzNVNTejdNc0VEQ1Nm
            eWhJZWFhSVBueHJSKzloWWRaQlpLelkKCk+1SUNYwuasuPTNaYYWw7GaGBTH35bc
            3+qQlNelI5iNv+u+O8JeekBP8u2RWzwezY6dgdJ0rpkPXUHtger5sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:50:26Z"
    mac: ENC[AES256_GCM,data:DH+nXKck8xbu6WWOd2C1dVKvfalVk/07jgfeiD9iPNx7u3aEK7w42UdFuwDJQsw0JISHUohLL0d3Pof9B5l1Om+Xw9F8Y3H2YSvS6QQDOQoxGfp2QZqX08ingKAkrI5U/oQz+mX6n1OkDSkZx9PWnsuKlA3p4xir+5HKm9UsmSY=,iv:thK9YiHsJbROJVbn00AwM3//IGoMKMC+UmMDLvSKU2U=,tag:w5vwaUR+9sToQiOb9DrBqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.4