# Encrypt before committing:
#   sops -e -i apps/moltis/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: meltis-secrets
spec:
    suspend: false
    secretTemplates:
        - name: meltis-bootstrap
          stringData:
            MOLTIS_TOKEN: ENC[AES256_GCM,data:Ew4KSdSJ1EUjJOYGMGDwMXrAKp2gCMpCcqybZOTPwoSrxt/mtso8fJ4RIYza3TXld2eMA714m0nZ/8kqrWg7+w==,iv:CUkR+L4/yPXOkl9L+Bal2dP2T5gABNLYs4c9T0/V4uk=,tag:oUzCi/ZUXfBSlkKTPvuKBQ==,type:str]
            LITELLM_API_KEY: ENC[AES256_GCM,data:u4pJWyqNLPajmMHfcrYk68Gq+EspongZwA==,iv:EijCtnO62/sQbegvmPCRuTJR4EAVZ17M4L16eNTcTPE=,tag:lyxYGgK99xYIvQ+B6lK8Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Mk1hMkI3U3pIK3hQVGdD
            TVQ5dWZ0SnFTZ2JtdFpNdkRMbzhYTTRoQWhvCnpETCt4QlZDaTViWXJCYVVLZ2Yz
            YXk0WFQ3NTZFeFhseCtVWlZWMVJPOGsKLS0tIEs3NjJoTGYyV2o3elRpNCt3eHRy
            NEhzL3llaXEySVRacVNVeDc0bXZyYTAKDDcES/30gN+5rt2U7YSxkVQcblN5rFCI
            HHEAZ1dqGaC9cnYpwOvaR86is5DTV+zAy8Knp9E/SmrTFGLr27OpHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T21:43:11Z"
    mac: ENC[AES256_GCM,data:ZzXMbx6jYWz2Cda2W7x8IXchqe8+mM6mMf0EF4UF1rsulqZQN0VWcFPOTi5ggvZj0Jcj6E7hde7fi+gTKZMLJlWJdZ8QGN3EY9t2xg4fgp9F5+KKP2g3vNALQAs6/Pi2hj/vxTi9FIC7GK0XGME9JH38B/1moZf49uPApPggDJ4=,iv:R3s45cyJ3KtPpvFh+Ued2GT/8KXygu1ZgWOepaN11kQ=,tag:v8V9B9uV/PtKzRXY7YRMBA==,type:str]
    version: 3.13.0
