apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base



patches:
- patch: |-
    - op: add
      path: "/spec/template/metadata/labels/app.kubernetes.io~1name"
      value: longhorn-ui
  target:
    kind: Deployment
    name: longhorn-ui
    namespace: longhorn-system