apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: descheduler-k8s
    homelab.local/OwnedBy: ElPoshoX

resources:
- configmap.yaml
- cluster-role.yaml
- role-binding.yaml
- service-account.yaml
- role.yaml
- cluster-role-binding.yaml
- cronjob.yaml