---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: descheduler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: descheduler-role
subjects:
  - name: descheduler-sa
    kind: ServiceAccount
    namespace: kube-system