apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: couchdb
      homelab.local/OwnedBy: ElPoshoX

namespace: couchdb

resources:
  - namespace.yaml
  - storageclass.yaml
  - pvc.yaml
  - secret.yaml
  - livesync-config.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - init-job.yaml
