# Encrypt before commit: sops -e -i apps/couchdb/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: couchdb-secrets
spec:
    suspend: false
    secretTemplates:
        - name: couchdb-admin
          stringData:
            COUCHDB_USER: ENC[AES256_GCM,data:l93u9xU=,iv:0reIZP8Qu2oF2s2WxMa4FV518z1FPWB2AJwRegQ/2YA=,tag:1IgGfyejt6POdD4SgdcFbw==,type:str]
            COUCHDB_PASSWORD: ENC[AES256_GCM,data:xAkN/PLI5tay2Fn2jsRVJWr6y9yobSYlllfIsA8Ncck=,iv:UPQSHkXEX64xvRKYNJpKhmH5OZbVnpaqKoAEdOUJyuk=,tag:8uL3ADzdPvwJfE1CbRQqxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdVhQZHQzMDI3RHRBQWo3
            V21jZmVTNnFENkFCRjZ6dkdEclk5SHhGVDNRCjlVQXF1OXA2bFR6R3B3UXdkT0Nv
            TXc5Mmc4UnlvN21ScXpTZjU3L2ttVXMKLS0tIGlVVFJCVTlHaXdYcSt4bmpvUWR2
            MlVVSHIrRkkyaER6eTlSZnBwenVGT3MK+5XL8eIWy83hsd0vzRYuyLH6S4zq+/GY
            ed/irhhWAyd8dxPZM+0Y4VYAVlaGFaVUlyg0vdPIZil+v93odAOClQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T00:16:42Z"
    mac: ENC[AES256_GCM,data:LaocZo9dmLtqDjppRuvIIt/kLRsqfvrQAosxHrXiSvpubBaKtHRD+DIl1hRHavgUfq16SuzEJgSRmC1G+3JBkCozGbv5F7dTT+uWQ+oKE833G39dQTaL0NesPEytk5yU18+7V691waAPouXlLu/BALt4k/nFVGqXH+1hDYQ499M=,iv:9hkeMML2zhBmJkT3+6ZhpI1x950D9l2ETVQ/QVjhrvY=,tag:NvKH6V3MeXdpbD8SroAxNA==,type:str]
    version: 3.13.0
