apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base


patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --default-ssl-certificate=cert-manager/domain-tls
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --v=3
  target:
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
