apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: aegis-postgres-credentials
    namespace: aegis-postgres
spec:
    suspend: false
    secretTemplates:
        - name: postgres-credentials
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:KixGKz+wag==,iv:gTgz3gQ0QBWotbmK8NCXsKu4BUTHEe0MxHEBL6nu8yg=,tag:eanqPepGuRromPK1Zyi5tw==,type:str]
            password: ENC[AES256_GCM,data:juwB+jTidtdz30ZQrOub1EBVN5VimO3pFapbfznU,iv:mzmV0fPhmdascJGh5w6JrPl3MXOOHAKwmQ+2JZHQnz4=,tag:6P9vTzfkwvJlkoHjUcg7MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eDNzZFpPMUJ2ZmtBOUVZ
            TUUvTnNjb1JzdTVMTVNLelR0R3hybkZsL1ZZCjY0dTFEbWVjM2NuclB4QlViLzNF
            aHQ4YlFOai8vb0pTSDJJcWRhMHNjOWsKLS0tICs1cCtteXFKamVhdjNMSmhrTTlj
            Y1A3b0VVbU52a2FmdEp1RURidExyN0EKXpoe10FeOt6lcrPpz1ehcrWqVWnMGBbI
            DZQczG6H3iJwQ9oQhNAf7RCWka7xbto8a6paewVM3G/XV4gDjMXvCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T23:02:56Z"
    mac: ENC[AES256_GCM,data:LhhG2M1poqsn07v47+MiLb0HfOS5MIni9BStjpeAv68ox3tQYGH1KmJ7BljfroE7FqfTO3vSMVYp6g/OgYjscB3bbJgblGqo3rKZRX4jOT2YyDb8yv71lVPGZwbh8oEZoiHR9mCmZdh5SxxnAufb7N3WH35RvTSjyI90SNXq8mc=,iv:0rMgNi0moEH7JV7MufUSIJSivpleo59u1WUKswj/xdM=,tag:1B/iHJXmHvmvnhgbaXBsRA==,type:str]
    version: 3.13.0
