apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: elposhox-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    email: poshox.pr@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: domain-tls
    solvers:
      - selector:
          dnsZones:
            - "elposhox.dev"
            - "*.elposhox.dev"
        dns01:
          cloudflare:
            email: poshox.pr@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
