apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base
resources:
  - ../../base

# Patches
# Remove dynamic "date" label from Helm chart that causes unnecessary restarts
patches:
  - path: patch-remove-date-label.yaml
