apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-backup-credentials
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: longhorn-backup-credentials
          stringData:
            CIFS_USERNAME: poshox
            CIFS_PASSWORD: z&H5K4N#5AjLG&Q!@9uT9#%h18##m!9v
