# Encrypt before committing:
#   sops -e -i apps/vault-webdav/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: vault-webdav-secrets
spec:
    suspend: false
    secretTemplates:
        - name: vault-webdav-auth
          stringData:
            auth: ENC[AES256_GCM,data:j81J35XoGMuFOAE4XynYEKwD8ccFC8DqrKtoE9Q6LEor6mjPv8kEvqqZmQ==,iv:8602OCiXFXgpDhavE5Fn8G+ROn/mloeTpLf8/P/CDdI=,tag:a+Wih0k/iLteiF1mzfkVLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaHU5L3ZyQ3RkRlF6TmVx
            VklCUUJHam5BVEgyd1FVNnd5ajhSdjdza213Clp5MVhGU25mdVl4VUZYWFJkZ2Zo
            alk1WEx5ZWJqVjZtZWl2aTdVQXd0c1EKLS0tIGpzTGlReUxuRDhVSWhmNXV1KytB
            TTViRHluc1MzcmFab0pFeUl3NUFpNG8KyUfob/1WhsH8NywNX39/TdHSyVA+PnuS
            Rmc9rXT//MbeZwAZSTe4pTzXXiiq7+eXVBdHRECcpxALbbiZfHJI2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T05:28:33Z"
    mac: ENC[AES256_GCM,data:cHzYJ7ImVScYGivGMw9/dX2uaZgbNWKgML+WmcMO/tqBD3vcQtrC6v3C0pXDAblUW+FCZK6rBEndmVrcPe2SUp3kfRHERh2mxPVOF2BtlpWzT8hC6BNtX3yJLLe4ry0APCf0f/Ws8i256TE7GjEIIX3zANNg+xmEYAtnswWSQtU=,iv:CH96UpEvqESZfqRzS7deF4M8XtFR6xend1Z9hUYoVDA=,tag:FRVmbfjze7qH8IOKBx7MuA==,type:str]
    version: 3.13.0
