# Encrypt before committing:
#   sops -e -i apps/vault-webdav/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: vault-webdav-secrets
spec:
    suspend: false
    secretTemplates:
        - name: vault-webdav-auth
          stringData:
            auth: ENC[AES256_GCM,data:ruy9R1c3Du/N/Fv/NfiM0/7zTquKEB6e+9kCG2Mp4fe+t1YHHJfVlcEQSclGTfhdnQ6kWUKv9vb7Fzpb5t/TN/T8zCnoU6qK/hKoHRj9GkU0XpWUV98eGwZlZNbZziAGWhedSwUd6DVtx4Ytmp45MAVMTGx4,iv:8Sr2NTnKWah8713OXfA3NoHHVxkRSXXXRHxl4GCjyR4=,tag:JJCKIy+7wpOzAJNK+5lxzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZFdMejZ0bWwraXlldGpp
            bWxLeVRFYU8wUC9zUUNaUi9mbVExYzYvRVZjCjlyc25NelFST3NpQXR3bnZBQUFi
            eHE3MlJrUEZxRnZ0LzV6cEVoOEtGYlkKLS0tIDlsS0xkWTdrWnI3cTcvdk5ZUmFm
            aVV3ayszUHBCaVR2bXhUTUhEbE5GVE0K1Qv91GeIv+K8EmhdYYIXcU5jJnqCH+6h
            NQS083Oc/VxUMEGCKDk1ngkprW0jEhZb9kTy1XZL/whrDSxtVdJ0eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T05:39:47Z"
    mac: ENC[AES256_GCM,data:Vu7tZFKmYMuqfcgV5jcyEouc5al3Sf421GShDFG/wEtqSxxlCrHBqrGEi8ynaituuI7mbxvalYMmVXGRqfmLPkE3o75ax6ek37TB/34wHC335/lX7pt9rzLoJS9UxVJpUo8iE5AsPejroQg4lNqhgNqYx7B3P3UXOR5NBiSfn2c=,iv:1XsjAZJRra6paq/7aHyKIbMonLsTPPEbZo0RlolC9QU=,tag:mMIPZUedvGBGKecXVGIVvA==,type:str]
    version: 3.13.0
