apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: aegis
      homelab.local/OwnedBy: ElPoshoX

namespace: phoenix

helmCharts:
  - name: phoenix-helm
    repo: oci://registry-1.docker.io/arizephoenix
    releaseName: phoenix
    version: "9.0.1"
    valuesFile: values.yaml
    namespace: phoenix

resources:
  - namespace.yaml
  - ingress.yaml
  - network-policy.yaml
