apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mimir-s3-credentials
    namespace: mimir
spec:
    suspend: false
    secretTemplates:
        - name: mimir-s3-credentials
          stringData:
            MIMIR_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:TCKZPGxV4Jnyw1eMZGgzk1MftpGkI/Aek1Y=,iv:a2DqibZX2WbGc1wxRToP1fYlFqf+Hwmax9QqyNiKpb4=,tag:+trGYJcwZxB02NQkX4c2Rw==,type:str]
            MIMIR_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hx74gPzvv3PpvQAK/ztU7h0D+Wsc/W+qXmO2CviGcvCu3qJVq8dkI1dqwATo57MvcB6VTgKuKJCHufkI0ef2LA==,iv:+00C0yv97EOwbkVi5+Ky2SqJAGZ0Nw6To8IGfihDPGI=,tag:QCR20aBZUZrEmtpiZelypQ==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eVZRdStqSnBIU3kyZFcw
            Mm9DN1ptM0NBU0xGRzd6bWVZMXhlUWsvenc4CkQ3NWVuQk45TjJYYzl4UUcrdldn
            ditCOVdnYlg5WjNLMWhzZVNqZnZWZE0KLS0tIGtya2k0bEZxUmt2cXoxUERTNGd3
            N1BGU1lDMGJzTS9TbHEzZkRDMFp4bEkK/YCCBAGAgrAlcgYkdCdtErXz6g0BvORm
            vhgUA6HxZT79Jofg9pQiKNH5bbC5bWIHQW5WppvHv0bORaiBi7+Jcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T05:16:27Z"
    mac: ENC[AES256_GCM,data:jl5Hot+wC3Ja4yR0OpGdWONCbwnTTM7bzRZOGKwBCkJebsayo1HSK10X27DyO2Dxy8Jo3Jm2kvxbBzBTnIiZLV/bb+XUF38Rq+Q0BUwneA2y18v+E0e+1kjinaCZt83x1RBZwR2DwMYbjZMwfNBBTAJFk+m9ZveHjdcMs+BLBs4=,iv:/OVHD27WuzxtIsN9HzT/a10ItNWrmf27jfCzaGnV0SI=,tag:yQ4JUFbzrdrO3lbCRLAhtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
