apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mimir-s3-credentials
    namespace: mimir
spec:
    suspend: false
    secretTemplates:
        - name: mimir-s3-credentials
          stringData:
            MIMIR_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:jOX25eQqjGqhGpm3bm9AVkWO7N4/FIODeVU=,iv:OYZIrT8E05ECCnNiTk1GpSpUjv7+PJldRxFY+Iil5II=,tag:HifqdWEhelFZVwC12D9IWQ==,type:str]
            MIMIR_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:h9e0m1MoZBEgK95/AGG7tf86N9p7Z85ZbDWdP84IOKSYzBo5rSKEArczoZkHZqO7if5OFv8d6t3B5XR7c8wpMA==,iv:oP+bekS/xE/gk7WF0Bw/CIJonoFjwwrdjnGxUIKMcJI=,tag:1/RyCi696dus63QriA/19g==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ2g2Y0ZJWWJFZEREM1Bl
            YmJITVBCQ3hDVTZtbjRpNzJXMTRTUldSWlZNClZ3K2FVUTlZbUhUSUQ0RlNmSEJQ
            aVlIZHl5Y0hjY2VhNXI0VVZiNXFxQ0UKLS0tICs2TmVYOStmcHE5dE1wT3htQmhw
            ZjFHT2tKSTZrVi9oeHVUY0lnQlJWYlkKuZs5exAkazB5ZXrXUaBh65vp89UJ5eEB
            ETXVygkeTvDJXCr6Ty2Df9WKjBmmPj1m2VHOARUdo9zSsBnAqHyHjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T02:39:03Z"
    mac: ENC[AES256_GCM,data:gEx7K84gnjzdPRwQWLCNshSPgGLOfynRRFDKsm+lp+xSdAUouNInHFv/34YcdZpRrhNH3MXRb39DZjvbEJVI2FC7udsVHSthH1EBa57Plhu9GJepFLaRoXdd2OU229z5/c5lP+hduyO4FUyTPrnTFuaHkjlcRVgmfioiSDi24Wk=,iv:DfWDARrChSgBxDpuQxx7espKv1GTUCHXKCjewbsUt24=,tag:svrInENBbSMa2kfDnK1mYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
