apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mimir-s3-credentials
    namespace: mimir
spec:
    suspend: false
    secretTemplates:
        - name: mimir-s3-credentials
          stringData:
            MIMIR_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:MKdvZeVh1uRMcnWfrrxDlgegNqW6aqFzELE=,iv:IyBg6bZfrpiaZutVSHP292gZN4yQ99B6Q2VcgdK6gbw=,tag:l2PWf6k0W+ZoKezaqIIsxA==,type:str]
            MIMIR_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:969CamA6q28hVLqg19r2/vjjfLbBj6gCftmp9oVCAIdpbj74Efkhm36vPuUO9AFQSXuRff8xlBA1I1xBd3hvgg==,iv:nCCBXRu+UxOJZN6DVeXfi1qUUUlHjjkSWphPtbyGAwE=,tag:WsLMVT2N6Lq90Vj9ndWiOg==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWWpPNzJadGwrSlZHVDFI
            QTltY0dkNWVJZzhlRkdSVFVyVkZ5SlFjZ1JFCmp2R1VIUU0vU0N3MVdMaGNPQmFN
            RmhlT2RCZkVYUTNuekZ5STNOcCs5MjQKLS0tIFhnNld1eERiYzdHamhzUVlubDh6
            NGVOZmNURnVkQnB6VWlsNlpicEh1YjQK7F0eJANesrtm75du0mwbyjVoe8SqCP9l
            tHL+aBJujPtCqDFRmaM0IDQoDokV7CVFnU51bofHwjwXE87sfsZPpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T02:45:32Z"
    mac: ENC[AES256_GCM,data:/wtKEAgiRmdiPUaimGzkpeqGqRRvpgWEUnNPyfY4cXaZijQLzOlW4pohduIpo9Ge82003ybXwLXBbkfo0cyvnnv/KxSURQkvurNBxvGwIDqsGZcX+Z/8TOB1aDsIlKH807mzRwBeL5Anpmh2t/fntqg5ox3vw2IcqaVxEPvZ2nE=,iv:6vE4G8A4FLE2o5kaF0P27cuJGNo9j6tKCh+XPIj/+yY=,tag:n2RuQJq16mQEiGq+IhOHXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
