apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: loki
      homelab.local/OwnedBy: ElPoshoX

namespace: loki

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    valuesFile: values.yaml
    namespace: loki

resources:
  - namespace.yaml
  - secret.yaml
  - ingress.yaml
