# Loki StatefulSet Configuration
# Link: https://grafana.com/docs/loki/latest/
#
# Loki is a log aggregation system designed to work with Prometheus
# Stores logs in compressed object format (compatible with S3/MinIO)

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: loki
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: loki
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3100"
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsNonRoot: true
      containers:
        - name: loki
          image: grafana/loki:3.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
              readOnly: true
            - name: loki-storage
              mountPath: /loki
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: loki-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn-homelab
        resources:
          requests:
            storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: loki
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: loki
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
data:
  loki-config.yaml: |
    auth_enabled: false

    ingester:
      max_chunk_age: 1h
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      max_chunk_size: 6291456
      chunk_encoding: snappy
      lifecycler:
        ring:
          replication_factor: 1

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 30m
      max_streams_per_user: 10000

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    server:
      http_listen_port: 3100
      log_level: info

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    query_range:
      results_cache:
        cache:
          enable_fifocache: true
          default_validity: 1m
      cache_results: true
      max_cache_freshness_per_query: 10m
      compress_responses: true
      split_queries_by_interval: 24h

    querier:
      query_ingesters_within: 0s
      query_timeout: 5m
      engine: prometheus

    frontend:
      log_queries_longer_than: 10s
      compress_responses: true
      downstream_url: http://querier
