apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: loki-s3-credentials
    namespace: loki
spec:
    suspend: false
    secretTemplates:
        - name: loki-s3-credentials
          stringData:
            LOKI_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:1L6YREmZlELUHw9qopMi/GN8VV/knJ6r80s=,iv:kNzGTKVwgjNxEKE2OtVBcIpVKyMZOvFAGuZzT8+xYp8=,tag:MbuKtwjXQhOqTBoj/n5+tQ==,type:str]
            LOKI_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:V4egJLcdlesydxM3TizYqOdbXjpzyCzMEVbuVgfPuKfOm4JIvaejX9w9B0s/lo1/lixhPywHzb2F9v4NuyiPZA==,iv:kslR6IAZzS8ZIXBvjUCw+ILiLjZ6vqjEVjD67KLWDsI=,tag:tSVLgqD8yf8vRQgr+N4C4w==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NlN2bzVLVUlKVG82NUJT
            RkZTZlVadjdJR1NKbEtYNnBhZWx5eUhnM1R3CnE1b2pNR3MzL0tVYnpmV2FWYlNH
            OUhrK2xDTDRjUmJ5QVhySkl4d1JNZ2MKLS0tIFZqbzBwVXRnMVcrdWRqdVBJWTI1
            NktQWmg2M3o0dUhBNnZZNVViVTh0VFEKmxVjHRR76zsdom9AAhSocjCJHO2BjGfK
            03CRRN0ey9+RX1iJDXlXqzi9U0cDGADs4ffvNe6m4K0VDrxOOI/gjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T02:21:22Z"
    mac: ENC[AES256_GCM,data:4rdY9OM6Th83pR17/piTbwH7QEa1D9zf+LbI5g8aIu1m4ztBv7PLzPJfPoVXkG/g+olG0KtSxTOECa2yA4hiG300nlaD+OurDwoC9ZeoIh6bRPdmIqRSscSjb1A0/L1k1xzkT8Gl7ana0xGMdu8inQE+I+gjeiq8mEOJFasOzhE=,iv:dCaMTBJn/1Be2TR0B/XhkxN/qCbUnjSY0kdvHgSr06U=,tag:RYic3RXnPgBeNAbAHjzsMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
