apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: loki-s3-credentials
    namespace: loki
spec:
    suspend: false
    secretTemplates:
        - name: loki-s3-credentials
          stringData:
            access_key_id: ENC[AES256_GCM,data:uz5qj/UIkojtAms8TB0897ovPTXjtWUj,iv:kXMotcyeeQSMekNDI1pBUr4XkiFRhl8eOsQ3H2IaFSs=,tag:UQMDx4z8ap39WGa4nKUqOQ==,type:str]
            secret_access_key: ENC[AES256_GCM,data:bujUIz0Bsb9PtgcRHFsqKxNS7Zi6/pbNeS5SLqKmAJw=,iv:DdcF5LdBHmqSDio1uN9VcwaALNx8ShvKzGXlURrcUEA=,tag:s/MRmVdEVHvJQPc0rV9vNw==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU2sxdkt2SGhLbzBYbmI1
            NkhDbVgwWkU3bmYyTWVWdlp2ejdPemxUamlNClZuMkVJQ3FuSENaR1BMMmM3cHZ0
            Qy9Ca0tqWDhPU0NkaWNvTTZPbUw0RWMKLS0tIGVVNE5OVktLNEZ1cEZuMlJDMTly
            NEw0NklyZC9iRTN2N1pFbWlPczVnU1EKEK0FjZSSVp+IQmXbyksQsjOgAtLdJu9E
            ZO7W9+JApWlViBm9G82V/bRj1RGB6fAZSBE0qWg75MMEbDo1GkHo1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T02:29:48Z"
    mac: ENC[AES256_GCM,data:5f5MRoLXjZbqFgwphCCC6lQY/CkBu4cnrvqmojnFeAu3jDgKXoQGgKHi9p+9AyhK3yEBkfoNWUkg7Ui/BsRp+e6pRPZU6+KNrnUelfhF/VLI2m6T4/d4GBLuFkkYJ0lbrAdWV23+Jc4XXKDY3/GcTVzzt4URrI2eLxdOR53yKb8=,iv:nFnwjkODc3FV8/UN7w9D9StejllHjxrQymnB+aNJV/E=,tag:6w8QBRdqFS0/ME9NDmnTTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
