apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: loki-s3-credentials
    namespace: loki
spec:
    suspend: false
    secretTemplates:
        - name: loki-s3-credentials
          stringData:
            LOKI_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:rul5HAefIg+a0B7isWbUlxVDJSfuIkzc,iv:+3j9wOgHsKV0NnQIZo1uUyzcmbFeV0FPvS5f1briBtk=,tag:vriP9Yx46g+UmMTFEquoZA==,type:str]
            LOKI_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A04Ddz11+IgrXLuTEVdybBl0q7r1tvqngXNW8EppoeM=,iv:wGnXfzSusKsVM8M6/gKvPaFQKfwwuHZzHlL+qZV+QPU=,tag:NJmS/gGlVk8suzwYAMAuOg==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eXBkM1dSZFA2dUk2UWI5
            Qk9CeldVUkEvMXhpbTlmenNEeDh4MEpnb0E4CnhBdlJZZXZDMEtpR09HVDZZMXRN
            QU01ZDRQMElQVU9YeVBQS2c1YXhsdFUKLS0tIEEyNXM5M2EzR0lIUHlUTENSSzdw
            UlhFK2xMUzMzU0o2TU1STCtEU2dxV0kKQIMDaXDxg9vVm1Re0YIYcxknkBoJq8WM
            nYn5O//zh40qa8mkklRNLpHnllDyYQi3GKiTDCKvFb9qmSz/osjsSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T02:56:09Z"
    mac: ENC[AES256_GCM,data:fYecGYH3FqQF8dH40gKneallga38VzmJ9csmtc0Lr/dh2fjyryzgl2k/78i8jVhSaokQv6PnnwWgSFqXEOGBiklCBo/JYFAWPYO1a347y5XwokQ/SBM6M4dzjEbAvySMcQPgdoU68kivIomw6ewuvSjLiLoFIVRxkRvNrk4lCMw=,iv:YP99WniPvqDF9DC+FolxeNuQoa8EfYyeg6Kt7/s1Tpo=,tag:/sAK4Hp6J2flid9PkEWxMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
