apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: postgres
      homelab.local/OwnedBy: ElPoshoX

namespace: postgres

resources:
  - namespace.yaml
  - secret.yaml
  - cluster.yaml
  - scheduled-backup.yaml
  - network-policy.yaml
