apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-secrets
    namespace: postgres
spec:
    suspend: false
    secretTemplates:
        - name: postgres-credentials
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:onUytkZZQg==,iv:wXAB33hjXxqqU/Jp3W8H/4CXICqlQ5KMsxAsOnFJT78=,tag:gdIIUvPm4uA7utVUNyiNaw==,type:str]
            password: ENC[AES256_GCM,data:UNsC0vecmiIsD+v6nCKxUfWRIZjW9qjbY79HBvLa,iv:28R2OUp/dk4AsgXUC1M73ck19pikhiunMjmEOHlWNS0=,tag:3gRronhrJ/L7C9hGPd9Ubw==,type:str]
        - name: postgres-s3-credentials
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:ty9JVKuSkanQqarSwMAug+gDOoU7wkZP+bk=,iv:e7krwmVcpdTaAE2ixZCQntsgg5mXpa9x/gTVGDDab5c=,tag:EhwXgPIctGlQPGHZdcu/HA==,type:str]
            SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4NrhBrJ/Rfjcoo5L46hwOiybTDEbDz8ftZSxPUk5FQC6mGr4HjC64KHB3iLg6FE5pzcaoeib+4AAsjO2YyT0Eg==,iv:bOxBTDB1Avo1yu9IkPut6e7JyS3e3RV5dsCK6T2sDqg=,tag:rDwzdZbf2SZulxUmXjlV7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDB1T0xvMncrRkNDWWtL
            K1BRNlc2VXd3NnFobENnNndwT0Erd0tFV0FrCmQweERJaTRrK0NPOGh2b3NlclZ6
            M0NSMkhucW9UZGc5N3VMY0ZVLzF5RW8KLS0tIHIyeWVaOXVqTjhNWDdkNzNYeWVp
            dzNMNkNUL3FadFFOUlcwd3dOMmhuMWcKE3Z2d/hjxsicNRPYuW6nW4ww/CegIEaV
            YNOGnH23O+f1RVIXWIDaI0TuXVmOyhyC3YCk4sIDWLk95ABXNfbOgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T23:41:30Z"
    mac: ENC[AES256_GCM,data:tg30/Edfpvipx1Q3ufvWYhAlD956jc//rf22dPVTJGPuMP146nO7/poxXNnhuI7Vk/cJVNxFg6dUuQt2Ilduor54qm6ngIQDZKM1MwZMjG9NNvW5YM987DvB3fRsQJ21OKjjXEE6awTJFY40PS1XJUVbPDi3XVzdOm4MzbXC9nI=,iv:QmSHnOkgBAyAhZu514wHIwbl5MRDfoZhyoi2mxS0824=,tag:bQd++76DnD6pOr/vfifRpw==,type:str]
    version: 3.13.0
