apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: metallb-system
    homelab.local/OwnedBy: ElPoshoX

resources:
- github.com/metallb/metallb/config/native?ref=v0.14.9
- address-pool.yaml
# - l2-advertisement.yaml
- bgp-peer.yaml
- bgp-advert.yaml
