apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: aegis-gateway-secrets
    namespace: aegis-gateway
spec:
    suspend: false
    secretTemplates:
        - name: aegis-secrets
          stringData:
            LITELLM_MASTER_KEY: ENC[AES256_GCM,data:Vyad/uz/y17GaCuekgpcj3cL+ak8NKBYI+gABwa/9reWYoecCtPeFxXByA==,iv:EAkjVAxBbOH6CBAye92VFpWhjXgSyv+xB7D/QDe5ncY=,tag:9wy9LX7bmO95wSW8xjkMsQ==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:1jeiRvrmS40tUW2tpmCVbhxI4lFkKRnAsluEw9LCsZ6XQalmh9mZ9K4sqRbM7Pt5EEIqJQ6mezfvDUxOON6ng/n55ojjudpULGgoGjZwWpxuA6zXIx9JVtiCJz5521mWFPHrgJ51/bXqs/s84w==,iv:toZ9vZ6VL/TfYoBHZm/T7FzDAFb7JVBkqPFiFz2rdBw=,tag:L+UCOtDU17m5Q0l+l7qpZA==,type:str]
            MERIDIAN_API_KEY: ""
            ANTHROPIC_API_KEY: ""
            DEEPSEEK_API_KEY: ""
            KIMI_API_KEY: ""
            OPENROUTER_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOVh0MEFzdk4wazlDdXd0
            RGpRUjlzK3ZQNzAwZ0RhZXphVTZGV3ZFclVZClIycy9nOFFiemJPZEttTDVJZEoy
            NDBDMVJhbFhqRnhBRmFYVXFiaDRXN28KLS0tIG1KSmxBdkhyNFd0SFAvWkE2c2th
            TEczV3lETyt6Q3ZjWDJ4bE5QaWpsMkEKfFvs/y8uWlH7BCUV56RCuHfwnwK5XESf
            YHZSLlLGhiE+DP966IvP9QpwTu+4wouwsiYwYXrio6PRUkoSrjecSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T23:03:21Z"
    mac: ENC[AES256_GCM,data:SuIVojpruq1+/E80HBK4rKF6mAMqQHg3gF6ISnxjMZXI7SwaGiwQrfb3bZEH3DRUvAESqWm1yAcbHzK4/+43ugkAOJMxNhcYsdEKsIrMdIeX4nFrXIgXnKzfFg9BjeEJY4bs4QWMz06+y64EYtiziOUnbz8xFH7/OmgDzohO1eE=,iv:Y95F3FibkVhG3cJ4g4jSgKhyP/JYqkW/JQBbxA2KXcI=,tag:In17n5/tD99bg5cDUU97KA==,type:str]
    version: 3.13.0
