apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: aegis-gateway-secrets
    namespace: aegis-gateway
spec:
    suspend: false
    secretTemplates:
        - name: aegis-secrets
          stringData:
            LITELLM_MASTER_KEY: ENC[AES256_GCM,data:7DiWxP6ONVbFlQg7+TSxrImJRuotQIHv53/kA9N10+3Y9m1vzS/td7IyAg==,iv:LTjQyRWiUhF/LR8lo4frYajnwzfJqjG/PRNjsF4D5Vk=,tag:2mnxwIcsPNMqeTJFsKRiXw==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:GULHlCj+LPQUqaY0s8fvgBOjnTTewUewIbmQwssTvEBHC5MFedxm8nBl4ZgkWXvRsEGVX3jciWOiCoTRfyg9Z3tPj+NxdCdv/BSVKFYGIXi7PzUYRsMCkb09Z7YwJX+2ni9FyzuzJg==,iv:WRxYTKq7dj3yj11gEFOyfDoGC0y+dPsGVWwA+HBPj14=,tag:8VeprFFUN79k1IFRXk8SVg==,type:str]
            MERIDIAN_API_KEY: ""
            ANTHROPIC_API_KEY: ""
            DEEPSEEK_API_KEY: ""
            KIMI_API_KEY: ""
            OPENROUTER_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUTNwQ2xkbFR3MTZ1aGYz
            aFk1LzczdzBBcFlmelVybWZPY01PL2g2SUJZCnZPY1QxUTZiYnJ4dTNkZ2FJR2hF
            UkttdEN0djFjV3hCdW56aTF6d0ZOTmsKLS0tIDZ5RTZONHlxeFA3VDZvVWs0NEw4
            SHpFNy9DYUc4b3M1NmE2QmpsQ0pxOWMKxhYTm+DiOEam0YJBiPl5jmLXUyzoRqpb
            2XtTOInDK4AWBUKAKPScTrN/doBjlzt1kg9EuGcAMJln6xHDZEesww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T23:26:28Z"
    mac: ENC[AES256_GCM,data:+lDSGEQqgMGDmJ7p4Z9v3QD3CT4PIT5tYxrpLq5rotTzdjGPW5Q5LBhFSxyS8qWVd8+LpM1CpMnGFil7oZeaB04J8rzzeL/4npIAk4Kdy7t8RYtT/GAs5zh/shHzx+yT3fHwOGijsoiKWK+9lRaBRopwtx2YQZgYpD/YC0Krf3A=,iv:xkBMY+Z8Zk415O0yfF1QdaWjK+1l5tfx/oKgEGnFps0=,tag:bcSK4ZX8d9ztdtOd9rDkzg==,type:str]
    version: 3.13.0
