apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: aegis-gateway-secrets
    namespace: aegis-gateway
spec:
    suspend: false
    secretTemplates:
        - name: aegis-secrets
          stringData:
            LITELLM_MASTER_KEY: ENC[AES256_GCM,data:th8aHaisPOQxp3k67l9sNApB62DMglFQicaQwNM2yHWlqJeetVGfm7DWxg==,iv:039TOWOHNMWQCI3szIO1O8Fjs4qK6SpajGKp3H5qWRQ=,tag:RdibxI5UlTVi2WFKtuGT9g==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:r+cJQEx38EJQBbRpLfMUMCnY2OQcXVTeAfFL9PGNYLup2ko98/j8oYwGivK34FIAFDAa6+57AraWGv/fYV0mKXD/C38Mnj5rT6csFfJIwfo2yNDzMEdESGH6E6dW8824ViM7hUIwVw==,iv:RKbOYIO3TbDicolrH5jCwbFCVJxAZH8+kj7T9wwriNE=,tag:Qe3kszCVykLOUXMus0O7ZA==,type:str]
            MERIDIAN_API_KEY: ""
            ANTHROPIC_API_KEY: ""
            DEEPSEEK_API_KEY: ENC[AES256_GCM,data:muMWlm9PDWzv6VO/jFYptv49xLHmzCJmWX0tiHCJdxW+eDU=,iv:w7hzxsGPDFl7CyjDJoaef39tG2Vz1/ifULXqz7BC/xw=,tag:0cBDMFyxr0638tEbDJkdGw==,type:str]
            QWEN_API_KEY: ENC[AES256_GCM,data:KOzinaUTQJJZ+RJxKdkcrGQbCFZd7jJKoDda7uMaK8d5zvc=,iv:NmLPjpZpdiQECYlmVIFXg9iBvYSh7pVk1MfEYWc82Pc=,tag:XeBEQh7Om/UPBRzaT/uV5Q==,type:str]
            GEMINI_API_KEY: ENC[AES256_GCM,data:WLBK9hVP207VEqy1dTiQPRxIcBE/FZFp1TCi3jvbzk8/TFV3Cc9WbzV2MBbQbzSzuOAJWSE=,iv:OxOFRSUhtBTiT+lnyHziK3JE5SqPGiQKBIFf/QeZ2+w=,tag:9mVV7Nv8jaR0pb2JeXFMVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1THRVa012TG5NakdrNWpK
            SEN0Tm9QYkJXa2t4UzMvT1JIS3Fob0JwVmg4Ckc4ZHU5bElXYSs5bjZEa0dQY2M4
            MFZVV0hpNUhuYk90dCt2eFJCa1hTZzAKLS0tIFU2R2tpbG14dVNSRzc2OGU5WDZF
            MHJiWXVKaE1rSEJZOEpwc1phL2VhQUkKUv6im+NGUhScltDAjZy4Pn0a0fTLX6Kp
            5zYqUTpzYS9TEvvIADfQZeFrbf4RKHPfdp7l3PleLKPWcSGKA9/M1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T02:50:51Z"
    mac: ENC[AES256_GCM,data:qmfiG3TD0iKzC0lRg2IfN/5Wiqak/2PJwsS7WNcbU8VyA/FjBFtljoccylb7yhZ0E3kq2eYUTv7aJKjg8Ab+PpB+tC+vzPlv19Ttr9dpfW8+djTTFT5Dw2xVsgNc7JPuR8Y4MD3lK9RKuF4lL+Uey0TI39hjPUg8kaWKrra+6U4=,iv:ge9AlfUGRxjAgNaziO/Z003Y7fktC1fGhfOTvUH3QBE=,tag:7QVWH/vXV/PJBrQAhj/pwg==,type:str]
    version: 3.13.0
