apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: tempo
      homelab.local/OwnedBy: ElPoshoX

namespace: tempo

helmCharts:
  - name: tempo
    repo: https://grafana-community.github.io/helm-charts
    releaseName: tempo
    version: "2.0.0"
    valuesFile: values.yaml
    namespace: tempo

resources:
  - namespace.yaml
  - secret.yaml
  - ingress.yaml
