apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tempo-s3-credentials
    namespace: tempo
spec:
    suspend: false
    secretTemplates:
        - name: tempo-s3-credentials
          stringData:
            TEMPO_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:VsDHJpRgEgCKad+SfFL+E6svJcahgA+vCpA=,iv:bxX6zyvgKfsnowOnbZU5lipw7u+b1AjBdai4wCVShx8=,tag:akmo/0aNPCeDsFysKruHyg==,type:str]
            TEMPO_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cqB4w0n/83F/s0PBps/YCjqgOmVkkXkHUQldwqdO7TLA9b9vfbe+rPJS33BKacd9i8EkXzZcE2tGfYssY4+ZqQ==,iv:yNm9YrN9A/fxhrGpqDJQ9uW6z3SlDTRwvxX5VUlfKG0=,tag:TDWaFCt2uMvOVG2IGXyS3A==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OWxIVVh5Z2pVbEJZY3dh
            ZFk3Q1dUcUpRMmtCZy8yaXZFcU1PSjRZSWlFCjYyVnUwOXBuMVU1VEtoT1V0K3ND
            WCtpYTNCY3M4ZC9HVGFTRUJEeWtLUk0KLS0tIGZlS2lwVFVXZjZ5Q1hnNjVvS0gy
            N3c5VGFPUXc2cjdybVBJY1VtR3p6K0EKl/mTsLdipGwOyhoQsWCrH4S/P39QBQ/1
            Ixo6ECIHGbSr45mukYyFnC45o0R3rHgx9S5Bbot1Aux8WEPErfsN1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T02:21:22Z"
    mac: ENC[AES256_GCM,data:1h1AX+0BLTNUslGomWhjEpCUpLQncC8STrRXEnMrH8cjvbAkYxEeI/BnvTDLGR15CrB4mMicphO6KSmi4VPrdAyyFgJGbAouA3RZn3TpOcyEfQARczoUjUB3P7EiXnzfzRzhD+wGIeoQDXbj69gqPmxMgcmkpUqo7Uj68ht5XOE=,iv:Egk0/ehGQMe+3oMx+5jCQASrwCAqKarY6PldN6vst6U=,tag:CaDm3RYsVotO+AysQ5VnoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
