apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tempo-s3-credentials
    namespace: tempo
spec:
    suspend: false
    secretTemplates:
        - name: tempo-s3-credentials
          stringData:
            TEMPO_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:famEg7RPkVnUEHLQKzTp7W6t1trKIQAG4HI=,iv:Z+u937DPd8uP6pBEpW+uaNCoriH11QDLHsVlkCMIsgY=,tag:FSsYR37Sp6rQbn7LTRKOrw==,type:str]
            TEMPO_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uGEGY8mszyMZ2n67vyeDPGfzoB5F4gBBSzYw2AWf+/FKBumnS4/wcu6Jc3jiWqWaarsm5LRjMpRiOddzK1HKyA==,iv:7Yj68QvKZDl30SCIzQgGaNNlO07CuHOL6X2sk3l3yDw=,tag:zl4w5tvkx4azmwKWioQiYg==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMUlPYlQ2V3BoTHhNWUpt
            T3N0cE5Vdk10N3V2R1FZbm1JRVJubnB1ZW1JCnd0d3pSV1RnUWV3R0NGRlQyaEpy
            eHJ2enVQVGxiWGpyKzV4b0xTaUxmWVEKLS0tIDZTR1ozbVJyaWRGMUtlYkV3T3lJ
            VmtNRm42aCtXaWpydDRKODhmN0IwODQKO1Ouoaxs4rX39cyYR+mymM3DRwW2KnYX
            MKx/nwyk1Nr5dkYjfwn63/8nm/srGVf4xUWC3UiFWrjjw3Dtw9eQ+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T05:16:27Z"
    mac: ENC[AES256_GCM,data:Lt1HycIX2wilK6fMqCHa6U11GfC+Eu6293PYnnyrmc2RZCFi1nUYgAlAPF0LktU0krNC0U1Avc4yUZpx6h7aGA7WA53bLwrC8Wpt6/5Amr+If372blkci/vT/fxyGACIWJSbQDasWscXlkQ4/wlmmTMFSPu2YviWDuKJD+Bw4a4=,iv:721S8ErmbDWykPsDNR5ivGcfjvll6k+bc5qLM5V0po4=,tag:ghfXL8bZpQRPmV+n0CvjEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
