apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tempo-s3-credentials
    namespace: tempo
spec:
    suspend: false
    secretTemplates:
        - name: tempo-s3-credentials
          stringData:
            TEMPO_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:VoFCivrO0RkalRpttmS2N1ktpzb5p/SFFbJ3/ZrDOLXvNafBh7afPw==,iv:1PXFInxg94lCbuGM+AjvtAePQ6URwAA8WXqJQ9ACs/Q=,tag:COJ8ZodnLbiI00lICyb0/Q==,type:str]
            TEMPO_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:w3ZgTmxSB9xUrJoG+WvWExOhrH0Xh2UNX70t8TGNRpl0BOErzBO8U42FTmw39aBZQSDADu/hUVV0QDyu1F9RwA==,iv:Z3TfpMid5cPC2gPxG5NQbxjqxbVQvR0SiAYLzobZ2AU=,tag:vKo7rn6XZQ5hMCY5M+L+VQ==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcDR0TUYxZFh5L3lGMVN3
            RlE1N3ArcGl6Ryt1L2xVVkJ2TmZwUDJQVG1JCnE3YW1mQmN0eEU5M05vQjlmc3cx
            Z2RIMlM2NU9BTnFCaFB2TnNkK05KTUEKLS0tIHQ1aC9Ia0xBZlBXeHZwUXBBcW5y
            WUg3ajRUMkpZZnQ3bi83azNEVC84MTgKtZ7vzsZRnASRfCK9V/Ba57kIjG4tFNLD
            dxkmjTEEFTIvrVsP8nWvdS6OF9EMx9ebAULlqr/P7l+KAFA0SccaPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T02:11:15Z"
    mac: ENC[AES256_GCM,data:crBem9TEf0CSvSV1F5jmJdg7CRMbYkkrI6BeZH/jZJKtBTtGrDKUpoLf0KZ1z9hg+GM76t4Q7z9c73k5bpXG2bQVEweZZ5lbRiqtbzUZZ396i+EkLtTaiZNcc36LFWpN2PZ4nwNpkR8ZU3eaMvGdIyc7Z5oGn8o3UFOM8/8xeMA=,iv:l+ewOCM/IrXgbkuQT/UWaZf/SWgtvmH/Qc3cB1tDXd8=,tag:66tkODmgW8FnOOK8Q+e58w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
