apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  labels:
    app: dashy
    app.kubernetes.io/name: dashy
    app.kubernetes.io/instance: dashy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
        app.kubernetes.io/name: dashy
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: dashy
        image: lissy93/dashy
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        envFrom:
        - secretRef:
            name: dashy-secrets
        ports:
        - containerPort: 8080
          name: dashy
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            cpu: "256m"
        volumeMounts:
        - name: dashy-data
          mountPath: /appdata
      volumes:
      - name: dashy-data
        persistentVolumeClaim:
          claimName: dashy-data