apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: garage
      homelab.local/OwnedBy: ElPoshoX

namespace: garage

helmCharts:
  - name: garage
    repo: https://datahub-local.github.io/garage-helm
    releaseName: garage
    version: ""  # Latest version
    valuesFile: values.yaml
    namespace: garage

resources:
  - namespace.yaml
  - secret.yaml

# Patch to add S3 API port 9000 to Service
patches:
  - target:
      kind: Service
      name: garage
    patch: |-
      - op: add
        path: /spec/ports/-
        value:
          name: s3
          port: 9000
          protocol: TCP
          targetPort: 9000
