apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: garage
      homelab.local/OwnedBy: ElPoshoX

namespace: garage

helmCharts:
  - name: garage
    repo: https://datahub-local.github.io/garage-helm
    releaseName: garage
    version: "0.2.1"
    valuesFile: values.yaml
    namespace: garage

resources:
  - namespace.yaml
  - secret.yaml

# Patches
patches:
  # Add S3 API port 9000 to Service
  - target:
      kind: Service
      name: garage
    patch: |-
      - op: add
        path: /spec/ports/-
        value:
          name: s3
          port: 9000
          protocol: TCP
          targetPort: 9000
  # Add apiVersion and kind to volumeClaimTemplates (meta)
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: garage
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/apiVersion
        value: v1
      - op: add
        path: /spec/volumeClaimTemplates/0/kind
        value: PersistentVolumeClaim
  # Add apiVersion and kind to volumeClaimTemplates (data)
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: garage
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/1/apiVersion
        value: v1
      - op: add
        path: /spec/volumeClaimTemplates/1/kind
        value: PersistentVolumeClaim
