apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-plane-to-garage
  namespace: garage
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: plane
  to:
    - group: ""
      kind: Service
      name: garage
