apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-secrets
    namespace: garage
spec:
    suspend: false
    secretTemplates:
        - name: garage-secrets
          stringData:
            rpcSecret: ENC[AES256_GCM,data:uP8xJogwrRD/Ytrct7TnOeAJmDmoOpHvgE3QBA9vMVIOrvTEW18AN5mlFbdcirKJM/ahj2CxHGTtPCkf71SJ4w==,iv:SCbroJI8ZFnjMcAtT6tSWwBDuBZchimoNk00uKkmQ5c=,tag:Wo+ZPXUKeQEMKPqS2B7ieg==,type:str]
            adminToken: ENC[AES256_GCM,data:wCRPDU+VHXRH3xSj/fVICd4j97c1pa2UCtP51YqskhxBXxZDcqKcb8hBFZzKkiZ169iN0k5dX4bhr4wSD+0+XQ==,iv:Gc68nCLiY3/KND4q+nHjMss3COm2U/5AAWHhbJekF5I=,tag:9av1siF4XlOfkqpi1Ccmzg==,type:str]
        - name: garage-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:2/9khuC6Do1VXy+KhCrzchGGtR3b7fs8OgM=,iv:/pUXes3Sd6cGEaIZXGcQghY4DzelDhPUqeXBS3qcmi0=,tag:F90hqabuaPWo1mJhJeWtsQ==,type:str]
            secretKey: ENC[AES256_GCM,data:/aBEh+iiUsVEppU4Lc8ULyRYshsOloI7J62wK9GuIx9lGaaKi9dIS0fS5201RzheroFOM3h2o5w7Mk78zP0Zqw==,iv:67y5G3SjSE9XoU5HaEZeD79Inw24BHHS3SVM4ts6mdI=,tag:X1MHmunhJYzQWCXvh4BdLA==,type:str]
        - name: loki-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:OfDogz+9oxpAB67UrjFvgzQgnBXdszGn1L4=,iv:Zs26xl5juJJqzF2yyHPQzvOPP/msolLMmHftMFj8IpE=,tag:4EhkwETva6bo29nd6XxASw==,type:str]
            secretKey: ENC[AES256_GCM,data:7fsGOdxaB7K9rHOBG3YZMNinKYJW5S47t6EOuxCTtrhXP2KRzvKLgdmZfex8SK1FdRt6jxPmkvy9Htbm38aMBQ==,iv:QrzkSyGZ8fKFV8l5nTqdMTaIXKvoBKpSu7Ow1zgBWMM=,tag:ozE7uNcvrEkm6lN6z/bmDQ==,type:str]
        - name: tempo-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:pbewwfPRygj5CM9uff9TWlGOHI3Gb7B3Teg=,iv:2n0B7atYWsNLEsfNMletfs/h/u94C3cdtgE6cqkAky4=,tag:5TmgdQIq48+4v2Wsusa2/A==,type:str]
            secretKey: ENC[AES256_GCM,data:Ydx0QcFaTN4PxRTyEc+eUndaYiC5Oaa2+p52+4ecluggAdiE1TfZE/7uvmS1VA0fY7b5m24p1FvsDXD2L65g6A==,iv:cHns/bDfUpBJ1KXVffPzEa9SebfcsIzn9BPk+vdV1Ug=,tag:va64ZmhRuHDypGxejsOOPg==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ckd2UzA3L0JrVUdyRjZl
            UVJwVTM4bWVnOEl4SzJUcGNXL0tIdkRXNUVvClpRak5NTW1OMko4WUUyT1RHMVNl
            akR6a1plR1NwalNoYm03U2hLYytxUkEKLS0tIEl0SW4rMlJNRloyMWFpeHBGVTZG
            am5NaExjLzA1b1RiTlZ6a28vL0JaMlkKtR99dtL/+GzitI8fmuyvM1ULTtfXzFmD
            Ug1G0vguMN40oQ2ZbYU7WzZsuc8eFgXu82NpsavVY9C5nnJom1xCHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T05:16:27Z"
    mac: ENC[AES256_GCM,data:rDllelpx+fsCG7XrZ1inoTAb+N+rtdbiodFUGpVkZlQezNs6Bq0mb6PzvfcQOJHQp7G+t/SYRIc2gKQucaRH+MFQXEcj46z+6dn0UGohKgnNwL1IDGIUcXF3qbUWGLkwFMos66NWuJVB4u+1yR2q2Ot/oDcDk1KSFDeJcPYyn9I=,iv:4PDls+XS50YIzyiw6Ii3Ow+4tBqky9tgA9UXgm1F8rA=,tag:cIGrvCdqJmBb+L78FjGleg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
