apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  suspend: false
  secretTemplates:
    - name: garage-s3-credentials
      stringData:
        accessKey: Eo83;WtO)C;2WnEl%s)MGR)T
        secretKey: KZWxNHlm<EeN~dI3I`Qk=W!79b[Am+Zu
    - name: garage-rpc-secret
      stringData:
        rpcSecret: (mX?d!I)Q<Kc5nUc>Ne+AtU!A\l>h7eUm9|^wHSo(Ots\>s(ThQ%fos3c4<{|
