apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-secrets
    namespace: garage
spec:
    suspend: false
    secretTemplates:
        - name: garage-secrets
          stringData:
            rpcSecret: ENC[AES256_GCM,data:jttinOF+VPkALg7XfLosL1NDq0jdhl//6BT2WLeGSm9BU+aSQoEMteihG+8bY3r1KmkMXz44zYTz7DUnMiBrWQ==,iv:/IpW/rtciotULkgttcgS8ABRH6ke4NWv7Pq9ga6oDxg=,tag:VGIjxKN3yWEwOKHUMktztg==,type:str]
            adminToken: ENC[AES256_GCM,data:RBzsqcYgiDXvpXX35lpZ+slHw8DFt9LJPAseRyZTsH/rw4oLnGF0hdyJx9JtuGqNyQni6dv/O12iuktgJo2C+Q==,iv:qBPkITwLGlIA0fv62Ij+lZ/EeT+iryVSmjVtf/CA0EM=,tag:uBuxxuM4/QKOYY07DSedPg==,type:str]
        - name: garage-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:ZBdpDp4ltgdgrHF01SZxiRkWrEJyL9LkXgU=,iv:nA4MiLNNHvS5Lc1+rgIDpejnO4GP9U0Bug5JKWLJ/Uw=,tag:w1cnKrTDt0wjvqIqf8fhmw==,type:str]
            secretKey: ENC[AES256_GCM,data:8o21f574nnH+lVu1Fljggt/N/YUj9Y2UHqV0X13VRrRfOSKNxPvxFa2gPgpxl4J+7jf2m/+TB03RQzjpFZfblw==,iv:BoaxTGzRb0c2enl/eQzDbo89hIUXKcv/TVMPlgW3B0c=,tag:n/AH9x2AFBvxbJ3+8NfSFA==,type:str]
        - name: loki-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:y4H/WND5WVUFPdcwMyIdHdR0LL0G/mUyuVQ=,iv:uKHJyylWWeKD9J3PjCaWrjoAkMYrcThuQWfpjjKK15U=,tag:jvjFMdxkzG6HbTGw4wzL8g==,type:str]
            secretKey: ENC[AES256_GCM,data:rG7ACYvyNmKzICERgJkBeHASYPTb+ilsrMQpWvDhUNENkA1nHyqCKBkyWF85TRj4ZeFgP1DmpcZE3fvc1kXm0g==,iv:LNMaXKQdVqMORSHTw511jlsQ9pGBbgU8VOJycXM/5+0=,tag:cfrjpVDSmHwhOrymVvLxhQ==,type:str]
        - name: tempo-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:G0wQdR0Xq7HWI+n4t3SMXbAFLO3BLE6YLOw=,iv:8k++VtCGG+6t/3zEvFamP5rtn+kLDaIwfMUm6jx04gw=,tag:bOgpmFvfm6exgdCsKgsPTw==,type:str]
            secretKey: ENC[AES256_GCM,data:qF0KnCjdLPaYvYWJf6G7lkwRlCDC07W7QpGBY5owtd+YkZzhYP5Q3kLPzCB/luHLEA9/MOlxdM7m9/Dc+gylTQ==,iv:upGj4QdPxuh6I/ceoMNKuBlmS6CNpyyOPdNAzgppBPQ=,tag:isbani+puvL/piFIecx65A==,type:str]
        - name: postgres-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:aGdxpMMKebgUDlaRBjXLTBtbDbuOvJzOHFc=,iv:zNVLRev5pGBflVmj5HNOwO4VDgQ+rhfz3YU3Zf1fZKE=,tag:QYWJAyNmKlruKtLQD6Cc/w==,type:str]
            secretKey: ENC[AES256_GCM,data:OPsmd/vk1tw04RKnNaMitfcp64M+a3GLzoqQspe0JxsjuK+TdIeJ3lhJKhrICNr9YR99pFMsHw4dVF3ihoDnMw==,iv:HuOZKBFyc8U28DF2bebEqb22HJeoBTcIFZ9BNv7vRaw=,tag:zYfMNULE1a6GpBBy2t7wow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Mzdad0tOYXgvTXJlbVZF
            YzdReGc5MSswb0IzMHpveEc0VmxNb3pZOVVZCk9SYllqMkhtV3psUVNDR1ZmQkEr
            YnMwV1JQVnYxTmVKV0xGWXo4d1V3bDAKLS0tIFU3dU9Qd2RWQTJLd25iM21ORmY0
            enF1YmpCcnY1bU9GcDBXbnB1UkFUc0UKKlm5g+0fXp8gvkttc1goerIGMPMm7e+a
            dnFsKiYxmYhmXVsCfE+rOz5gvAQQDlot75y7VD57VMQMNGPd92DzzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T23:41:30Z"
    mac: ENC[AES256_GCM,data:9dddM27EJjmYPG8doJfFOMeKwJtvvnC9Q9VOtjB+jRzGMSqcqhDwTYNkv4bBqXiFxDm1cDDCrO7oOWwKbv786+tIB24upXADXaqyI3LaD7nGEHBDQLOCuXqGSwDZGFbaVcDwYb64xsei75qtVG8hCPiWkSwEshOZJCugccnG2g4=,iv:oanyUNk5Rqqxk6rHRWZG8MGad4w65PIr0X+qcV7RIQc=,tag:cco7RWnY/5FMDijYfiw41w==,type:str]
    version: 3.13.0
