# UNENCRYPTED TEMPLATE — encrypt before committing:
#   1. Replace <YOUR_TELEGRAM_BOT_TOKEN> with actual token
#   2. sops --encrypt --age age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q \
#        --encrypted-regex '^(data|stringData)$' --in-place apps/monitoring/base/secret-telegram-url.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: telegram-webhook-url-sops
    namespace: monitoring
spec:
    suspend: false
    secretTemplates:
        - name: telegram-webhook-url
          stringData:
            url: ENC[AES256_GCM,data:uphtJWb/t0D0KtEbl+jpO2Yeel2asSjk2UECSq5iREAe8gvE8AH2FtQTqUo/CUmXknpFR5in5TdPYmYW2oXbXYyyqF7K2P3n+mwz/suTP/Q7g2B0ZPg=,iv:RI/jhxzgCCEGgym8AvVKUnEkak79paphsVz0HmuLfTA=,tag:tel95NBM2FgLv9LZ6xQiUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z2xsenFNR0t0MjhqOWlp
            dzVpRnJRYWpGUTF6RnNSL2FGZytMS3FWYTFzCjVTU29RNGNPR0xzZjBKTngvK2VK
            ais2LzRreWdSWUxaVjNGeDJCM2RrVncKLS0tIGZHQWFWOVpBQXJEK2d1SlF2K1JS
            dmJndCtGWUFYcWxuQW00QkE2WHFnekUKYOLEoHGmhc8K0qnW9gchjDsYIzUfTbHV
            GWpreNZUsGhdjf/27VdzzJ4PePvPYI9sMdKRFN7K02xIsur1e5XQEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T23:31:58Z"
    mac: ENC[AES256_GCM,data:XtgUh6jYJx4+mJ6/165j0UHuJIV3koLZw+UkIWzHJiVfaFqWuZ0i8srsDbuVxoFwLr1NuqfYMG70SAW/ej68e3iQPsqI4/9TgJ0QLkD6Tm7OjIdWHwzDrWQewP21etrAbKpwiBF8oXsECueFchSP/W5Mi+95ZoWy/+UOCCgGcGg=,iv:ckcYTC3vwDj7uAjOObeKbt2M7kgMABtoAh193tut6y4=,tag:8vnM02UeBaX2Ytx/FctGBg==,type:str]
    version: 3.13.0
