# UNENCRYPTED TEMPLATE — encrypt before committing:
#   1. Replace <YOUR_TELEGRAM_BOT_TOKEN> with actual token
#   2. sops --encrypt --age age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q \
#        --encrypted-regex '^(data|stringData)$' --in-place apps/monitoring/base/secret-telegram-url.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: telegram-webhook-url-sops
    namespace: monitoring
spec:
    suspend: false
    secretTemplates:
        - name: telegram-webhook-url
          stringData:
            url: ENC[AES256_GCM,data:RXbWR6U8LJgs+PyVKXopi0H+Hcepzt/P1/hWBVb4lNjP/ZYnkklwUkfr7Xp9GEcKXqs/kSM5XQpIwLLaH1ZUPP8CmWw5Cha0dqN99C8/WGHHTamNkIU=,iv:aYceyCsOrMfsiTW9dcVlBqyljR3q7yVd7ACIc2Llsf0=,tag:PCdC3sM3YxtrgKKt27mF/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJazZ3ZGZQWC9iY1diTGlL
            cUtIVjVnK1gyVGxSOTN0SFBGUVFSbWdIdVRnCndvaHE0czZPd1dmd216Um45VEJi
            ai85UE5QdDFJUXpLY0llMHMyOTZSVlEKLS0tIGprMC9tOTNxSFR3K2tETDU3ejFr
            RmtWSlVnQXJobHl3NkNCOU9ETlhZc2sKGk/nTdNGxoWHa+fDOumYMW5yoiqgbOA6
            TgAfys1rN6iXHsHVLpi8DEicYkL58TV3xjZczk1e7GkCnNtHUV4bKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T16:40:28Z"
    mac: ENC[AES256_GCM,data:IP72Y05cupgJNS2cvzlL0Q6iyMpCM6ESK06SByiEAMI4LiBROfKLgXn/oZwCkoo1/mNdQCDx/ljIkLr68qBzoPRL3BbQZgWgl2WmcZc/e35DNgAXBxqaZBkGrSwVfDiRHsNyBKkBwy7rW31+ztkBkT6D27cinzglI/5GxAWd5m8=,iv:mhDgbsjsYu/iEuz5fS8ILz8q0/Pg6lCN14po7E895/M=,tag:nqyNgYv1Tjzfcg2F4lblMA==,type:str]
    version: 3.13.0
