apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prometheus-s3-credentials
    namespace: prometheus
spec:
    suspend: false
    secretTemplates:
        - name: prometheus-s3-credentials
          stringData:
            PROMETHEUS_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:jCPtCYRLYbxpGhE6jKMCXkBMDHX+InzyxbM=,iv:jkD3sL5YWSEe7x15DtWnPvHdw0roa0ErbVzuCkH8/n0=,tag:brnLt82hV6LSu9+60YT/WQ==,type:str]
            PROMETHEUS_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kihPvdOk6ramCaZzqNSZINiWUgQ0qiW+VQysceqO16jyRQZEliyf0D2Hqm2cOsOVtmFO7HJG3iDaJWEkQociDA==,iv:yQ9VMn3NW0DzTLWdzAGzX1/tuQFXBn7pzUXEkBhZ4yM=,tag:EFjYGbifvPdmGbn9/RWyrQ==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d2dCdEJmV1h2VGFyNXJH
            R3RkakpYY1Nja0wzVTIvcVo5TnA3QlczTXhBClFlVlJQeVhnK3lUa0JiMlliRFg2
            bm1PekFwVTR1anp4K2dvS3A4akh1TDAKLS0tIGhFNzN5ZFVncW9OZy9xUnREK0o0
            RXpyUjBMWERpclJLMzNEU044QklMRXcKDdzr48Y6qebL6532wYTCjiKXfVQ0Om0E
            FIRSCQGlExIzFg5nKFg0B8Aq0p1FBOK4sVug2934wSa+PFCDJ00Dzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T02:33:44Z"
    mac: ENC[AES256_GCM,data:3IB4hYBWNUi/eA67XAhN3wAnWJ5zWZj+0AGuU1eWaZMf0+T6C+rLsyFRxXxgGP6uPFWBObRuSRGMUfxAwcQ7vQdN9dIX2sK57UQ1BsNjGY2+rsUGYnOYl6vzWr7RyJI2QNttBz2/l5zFBP9PD2/K3I65F7gezQLD+w1nMzGI/4I=,iv:ZX/Kq/U4POz0Al+/hUn0srypLU/QB7lHWFCim9E7nmo=,tag:aNveXQ13lCzWr1CSnT28gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
