apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: plane
      homelab.local/OwnedBy: ElPoshoX

namespace: plane

helmCharts:
  - name: plane-ce
    repo: https://helm.plane.so/
    releaseName: plane-app
    version: "1.5.1"
    valuesFile: values.yaml
    namespace: plane
    skipTests: true

resources:
  - namespace.yaml
  - secret.yaml
  - httproute.yaml
  - network-policy.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 1
  - path: patch-web-url.yaml
    target:
      version: v1
      kind: ConfigMap
      name: plane-app-app-vars
