apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: plane-secrets
    namespace: plane
spec:
    suspend: false
    secretTemplates:
        - name: plane-app-credentials
          stringData:
            SECRET_KEY: ENC[AES256_GCM,data:6CjBtgnu5CU3NZONz+038zrorXcF5yKYY66UjrPbXTmRLrebUW4ajokOSkffkNm39cgsL1LpOs2lHENfC1r3ew==,iv:otTZLSD7CY983tzb9ru+RBy524XSfCC1h/e/N01AVnY=,tag:0cqjuyZ2G+Xkfex2Vo0twQ==,type:str]
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:M4sEZtF18SLZW6kULDa+RQogNWSXoI7sVs+RR5IDqPmWPtHWOwjgCVc5/tVaGN37Wmv/FsFZsUWFIKkINhdrPw==,iv:MGo3xhA9wLJ7VtJRTq2tPqFM61g6Mxj3W150X5dqkhw=,tag:DE9j9qv4jf/XZlpzCxcaIA==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:7YfDliQwlDQFKjJE5KJ5eB4G+gewu2fXJ856iIgYN66CvevDealYGhqmIpSC/zcPb5o8thDYFnqTV9ycc/CEdjmyX8uDlK+wRBe8i4mPMwsMPLeV//g3h2kwXVnqL2PD5jFIOFU=,iv:2M8+DRfNYxD+0tOWiWUA17mrZJQQ62uzg422a3Q09GY=,tag:T8MduQVfqwX0AmHczXMW2A==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:ckBQ46vCy5jwyJ98s8yv+25RCWpufiVkO2oWobp/Q4/PjW05D5CVJmTMlCjNzyinz4JvXMw=,iv:RQu1b0Q4Ilm7cMGOEgHA9GBuS0KUG8WP55bcGOAkKjs=,tag:QOv+7bFlYTdNnmYEhkoRmQ==,type:str]
            AMQP_URL: ENC[AES256_GCM,data:RefoYRhDyAE0luCQgLBG+Y/KAsmUtF96WqypInf+pAqQq3+0p0UCv1D1hgqNDBwpNtVBkIi41C49/G7jNHI+l08ncBO7dzTOaS7hBHm9XqAk4fCGh7YRs2w=,iv:0YtVO6I40mYAeNlZihsp2r9deKHf/A/K0FdeB+BBuag=,tag:EBOvFmj87EGElpdlnscZTw==,type:str]
        - name: plane-live-credentials
          stringData:
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:p/7PWUDGOESGYhMOzwCWMKGdYl/2E69oeFRikBoMGc5nePj/WGBIybPwzzucd008tqvCFw61aFDL2dsafdDqYw==,iv:WCwrS/mUDc7Bf1plncpGIhgDR2UP7BfnhZlnAzNhDp4=,tag:BpIASqdrZ5zwIC9x2QjdVg==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:6RyjD+yg4H/BQvihhIVdVPYm40sge/DlX7Q4V8f96N8JPzNcVOaFAeFtPPzDTZh049YS4rc=,iv:EkpRz1I1JVN1TYoc4ckpB2TB4QVoqmSC79/TLVioZFM=,tag:8xOGMIj3vyXU3D4RSz2Hgw==,type:str]
        - name: plane-doc-store-credentials
          stringData:
            FILE_SIZE_LIMIT: ENC[AES256_GCM,data:SPkqowymbEU=,iv:FKqTmH6ZNuEeBa0bDNqA/BScrHJPQG2n0JIzaA6+ago=,tag:t/yuReLDfcG+uThnBtEhbQ==,type:str]
            AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:954ZvEHXVWG0sptlFg==,iv:gfBql/aaY3ZptUXfUG7fRieSH6icPo4q66SwiyZyjDo=,tag:uB8NTr21CFWmLVFSMRv9dQ==,type:str]
            USE_MINIO: ENC[AES256_GCM,data:xQ==,iv:ZoxeOODbvNuA4rKmaraqVdP0oa/U7CeQvNXxfSJq3sQ=,tag:NfCn6yma//ZmnSIPTcF+EA==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Gi38d6z/lxtU3e2O3WpJEns8TZLR8fiAgsU=,iv:SBkxvcUEQI7xbIPltB03W9ONlm4RMsjqTewAT7v6QOE=,tag:AFmfA7BGEeYDCAYPWxzifQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:T/1LtQRLw7SKzjxXV2YM4Gs7cPcHv7T7qdGeE0ZdL3opA3LUHUdPJmdzvqESiLGR/kI+tawMQWIipd7EPMfkoQ==,iv:4kIG+MesM+ToEtIii/YT0kPH94Pd5a358w6UsbB1lco=,tag:uMrYj2lc9aXqDiKSd8H6kg==,type:str]
            AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:45AGqpz+ckIIAoLpAPFIa0jbFQCuI9kK5K72shWy1JKdCF75MBt7ceJdqg==,iv:IS/ZsVWt0sgDabfI5K2WBoAnOBA5HhXFHHJ9poVE9to=,tag:pDirs18R/Y8l9nNxZJj8NA==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:98Q4Vib2,iv:oDUQVKTKtAYLnmIw44d3qdLdufBhyFsV1iJ7mz6f2pE=,tag:NjUa8ylp7RQHsOErfdLyfw==,type:str]
        - name: plane-rabbitmq-credentials
          stringData:
            RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:3tgCtOs=,iv:/53RtNckb1niOFVuix5ZnQoBBS0U0pnI/jdBfAVsASQ=,tag:Ymqu1BnzeRKkVhWAHzkEFA==,type:str]
            RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:oQP/9EPW8kJTqm146D+sJohozJATLUZjMmAxcYJcPzo=,iv:KNzdPGy3TnVG3PkBo3XlXl+ZTsgescdW/kEevreYANI=,tag:jEhOkStOqreMgSAN520xQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UXVZbEltTEVjaEVaVU1s
            RjV2djdmMTZjcnVRUy9TL09sUXNPaVR0aUQ0Cnc5Nzl3NUc2UFVkOVFPMkk5RHhB
            THB5U1hLL0daaGF2d2UrMG5FVWZPeUkKLS0tIFg2ZG1vRVpId01SY3d4M0I5MnFk
            aFZWc2tHcy85RDdYNnBCVjJSV0pQd3cKBzi3GuGwJ5m1IHBN+lhOsW8fyHE6vNDf
            phBIMSIhzoeTTLV5OHBIRXbnr4llDUCbm/DvyvumwdPGuBkfWZUzmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T02:47:00Z"
    mac: ENC[AES256_GCM,data:DiN0gPEwA8haYezedfwUNRXIBYQuI4sngN1B1xrsfEp3XQobJHI0v5px2+CRrOGbLkbRJ/oCSQRDlQMYMrXlHFMsBI41KisyqcjUyYIBSSq0p8aoR6Jq+FPP8Q5nWt6CblQ5objWDCwKwpiY8XxbIrKgm6YcP2KqWuZC6DKTM9o=,iv:0P9Q2y8sdi7qT6mq0yrZkqRg/xvrdOYr1cnEL1jvyuI=,tag:uqpMwe+THcVlcSrXU9i5xw==,type:str]
    version: 3.13.0
