apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: plane-secrets
    namespace: plane
spec:
    suspend: false
    secretTemplates:
        - name: plane-app-credentials
          stringData:
            SECRET_KEY: ENC[AES256_GCM,data:y/Am8IJVxOYFnt2vrzVQZzYsDXZyG5au/6XSIS7aNJWq3X5P5LdVB8XGbpQMswmW4J7Q0hMnRRwYtZot5eJtIg==,iv:lacqYEQX5sNBJ+8JP2f7Ok0WUnUD433oUV4KyW7UR/s=,tag:rp4Uqj5MWFyXfdPPrAAx/w==,type:str]
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:lxey5ZZat/sxpaQmUatcKmQj4N0tMK1RPUep1gplCzvcQWUL1mg/6Pe9MpbGird7dp8Xpjj7BHtxNWSZs27T/g==,iv:5PLSynrnhd0Khlh+Hwtk2FDuUmhCS3rL5C7Qw2oTxAo=,tag:dGRvdSLB/PkJQnpqJgMFEQ==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:xPgxxWW/6zQjqTMqs5BvMNqO0BVuHzokCIbdaaFUVlyYHcOIxZzuiTe0F/74vET9wwkLXJHf23nWoTo8/5qW+8iexJrGdid4pAFo+5ZfWMIyRlbdYTcCzVUpJH0ufgeHB6J+YgU=,iv:Qi7+kx3y9pcEDuFVlQs5H7LPRQs6mGZdIS4sXJnuCNA=,tag:y5Qgp0pcJAsIbWZSOkntZw==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:Q6RWUOcn7DzkaAYlhi+GlwlYp8KpAX3Y6MfPC8eWFgsZgEyNwondzMZaFuggldjLyAQiI8A=,iv:mi7tkmqXibqnGUAniY9o/V94Ytu11H+6m0mS0dYKGm0=,tag:Z+S0pg7e5g5uzPp4cndGiQ==,type:str]
            AMQP_URL: ENC[AES256_GCM,data:JUVv6M21JxASCKNVD4KeM5UvH7qpWYVigtUaQ1PjHw2VZnw287GOYGnEX59aB1c+mOQOi6OajOG6R+bl6GFDivK1M2TivFvGEQdy2auNPiSmOd6FKNRUw74=,iv:/WJcs5B9LGia832goZ2yoluKHwpMKBNQTOFVWnDHMYY=,tag:n0h9Wa25/Tpj/T2+TSnOjw==,type:str]
        - name: plane-live-credentials
          stringData:
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:2T8yK3Gv/OeMFdvM1HI/89Jeq0sXjmYcf9dwUMFMNCkBXm46WmLmAcyoZuVX99vqvnVPgReD+QD+8ns5EQjW1g==,iv:fp9Yc2+VCV7ngJM0slNCvq896LOaX7yVomYmYYmIvlE=,tag:tHftalInh6UkzOjFWvOFRw==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:1Z4B1sP33gXnIfTGEIZ1iG4oWkFgQGOURDJzkibxD3qqFFTl9E0y1CIOWIlA+0OeHhardXI=,iv:sgY7x6oMUD4iQN5r3yIt/b9nwHzwOU+dP/RATszIYIg=,tag:yx/DE0AoT/4kdA+eRGjodA==,type:str]
        - name: plane-doc-store-credentials
          stringData:
            FILE_SIZE_LIMIT: ENC[AES256_GCM,data:hCuTkh15AzU=,iv:dmjWnxT+OA8epX5Tqjmj+OBxqTjyghUKbvSRMr6VlWU=,tag:aG7buYzjbkVlyC8Obfyjsg==,type:str]
            AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:r++/afOAddGyNBwz5w==,iv:NvIt9CYWWd5XOkgBpm6UQreZLF2nkRk7o85F+Ca1GBA=,tag:hvbEjnTobpo9nbGrryrOWg==,type:str]
            USE_MINIO: ENC[AES256_GCM,data:dA==,iv:B+mwXrRUqBGFhUomEek06CpZD1MF4Gv0yujGb2MjUfg=,tag:b7Tkm2IVOtXZbEjBO1W/Gg==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:76c53a9mZ4osIxLtvCHcMkAlAKuUwSjdwqk=,iv:6cojYbQiNiBIXu8Etsk9DzaeX45rTlyqsTPGMW6/uAk=,tag:LPvdQgUUXt5ziPs79Jee3Q==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3PN8HE7ovYx1Zgd8cAiI95azH7U1ZpkWlErW7C0y0oWbYmVfjJ43eMDmkvKX5fqBg18Nf+tK+DbAgHaOlmIlIw==,iv:VUiGigL8xLDy1uElqbJ3Tevr6yByBdz5mjaDC11bdS4=,tag:lKstvyacq2IVmigX7XdJLw==,type:str]
            AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:ZM+W4gxuWScZToxl+P0pEq9D/gSGCC71yJ9bd4+xiBPsg7R01ZG9ali2Cg==,iv:ADh1xWvW2OEhJ876RMLeQ7kXyYXeabkeVrjW/RL6l/w=,tag:zGdyz0MiP4mNAmq/lre4+A==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:5CZjhONY,iv:I1yOZfXAD7wo9jjMmXAQnfMZWWewjwKhm+f4cyyrsH4=,tag:IMT37dweQ6qtgG7LbaUAkg==,type:str]
        - name: plane-rabbitmq-credentials
          stringData:
            RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:VKvl8O4=,iv:xH9GFK2Pd7y9Bm2crQe3Esb7sXVWbPtcn245pQeHHik=,tag:86gZ+kSlPAQNNJ3h0ByLwA==,type:str]
            RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:JmDTMJ3V3tvEHNLgERfoVA5HS+XG6g/txeQcMsYOJMA=,iv:RO+CwJzCaCJwGyYz/xje1AYuJ4GwKJ+CukBFuO2B+cw=,tag:VXBmR1xlohq2+r2buu3CcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZWZDRnViMWFmUnhTWDlF
            NDJ5VExRUFhNa2M1Qi96d0NRL3ZpSWFuZmxNClZSSituUDA1VkdrQXF0N0d4ZEN4
            YUl2T3RVRnhkaEQ4V2UraDdyZ0wwUmcKLS0tIHhZend1TUUyTGsyTGpDU2dPNG1r
            VkRQbFM1cUFJcHdEY0k2S2t4Vk5MeUUKKjY05+TAhyN37CisPEBDQTHfhCDOw/pL
... (7 lines truncated)
