apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: plane-secrets
    namespace: plane
spec:
    suspend: false
    secretTemplates:
        - name: plane-app-credentials
          stringData:
            SECRET_KEY: ENC[AES256_GCM,data:le5SHLzIv1haREYebk6hnPb10qQRB0985oBk0EAGySu68N+2xh5abMAc8CUoZZn/jIyF7iK44SWjEutwy/td5Q==,iv:x8KydZOKkjJ7HHPWeWQNEwGvz8+PVJvLigmz5dO8rP4=,tag:AZt1gnbrd/cJ2dgTndMTIw==,type:str]
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:f+r4rX5tvC10v/KSi+e1o6gGkuXqb3gWHNIxfNffrmFgN63EITR2S/jhy0/c5P3CQhpgz9RM1UPLxsmVm6owxA==,iv:IrtBLetGFLwZDJUgtafNmPz2D2J0Zb2qCe+oKwS3z78=,tag:7z60yBZunRz0QYq8tvLM7A==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:BLwmUTEN4AMuZ0+dmtsJ8fI0iNUJjiJbdxZ5duZsFDeoT5Bbs4TgK5fbEbnXEUVLs3rwZLtP8ZYEW7rFKe4Y2jT7V/0WdM30+Q9KsYJSgwRIXrRL7j7ZFFSAE1VB9v7wiLgj7G4=,iv:k+P7UnNsLJt3WB/oPNtOAxsHvz96c+pDcrg96neZwrY=,tag:NKPBYNMKphxQtydWpgjscg==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:duvTNZEfrlyy+ILTsVyoVtUZxBclEe2dPS4yWOkkCYKuePXZFFQAwXWeb07vdkpGip+fu2k=,iv:MQvaVGkblsv4YCgH8kgaO6xvLx1RZVBqsurq7JBIE7M=,tag:sqOSPg9a/Zu1YpK+ZtjcBw==,type:str]
            AMQP_URL: ENC[AES256_GCM,data:CYOll1w8iNyvKJ2V3yHGCu2Tn1B9SYNLBLxiAiYXYJ7AMxJoOnp5kfuKSoMx/sBR8rzHGX+Vd89yLOmPffBj07yW4804jsuYzK6QPMp9Oa3E1vgxRAZ3LfU=,iv:8mXdFY8EsMulRUhH4Xv95ivg20CbbibdW2/MiSZyjys=,tag:NI9vOqDU36hNUgWeufsqvw==,type:str]
        - name: plane-live-credentials
          stringData:
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:3oCF/sBiaQJw6ywBrcfOXTqs1aXK/qjm33xnp86z4xpzF3w5CXxQhYyGoCAzFktClDvu7CR0l83MKj3QAJIL/Q==,iv:/WB7hfv7e+hnuWP3NEaoH5x3Nz8OnfNpdLfguguUnRE=,tag:bn6vJaZcfhtKwAI6uDywSg==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:jzYBM6AauKx9NWiqI+wshEFtvVJ32zyY4fAnKPkC0bnFlLIt+j65V+gQiTwEQdsRYiVdwOM=,iv:LE1XXZZ+YXeWuf0z3CrhTece4XNW8/TEk0pPxE9ou6Y=,tag:1IGD6eMRP7yKsDwvZVCCMg==,type:str]
        - name: plane-doc-store-credentials
          stringData:
            FILE_SIZE_LIMIT: ENC[AES256_GCM,data:/Dkqxz5UlHo=,iv:w7ce0Y8EnEm2zdke7xYUVF1QpX4/d3r3DqxwM6A6LMg=,tag:bWENPO9CwY91j9rn3nZfJw==,type:str]
            AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:WuCAVZBEjtU2sWBqfg==,iv:1NqzQnGsJ0pAlr7JNRgzqhc5lTISMBXfzefWx3jApUk=,tag:xJo9le71OlQCPMshmF1o/g==,type:str]
            USE_MINIO: ENC[AES256_GCM,data:5A==,iv:HpWjGgW6cR3QhrfilJ6ogAz07EzxsmALUUENQlRKXNI=,tag:bznXRHZnlLFd55vX8KeF7g==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7BZpot3SdSUJH4gPhryAZ4obfAtJIdppwnc=,iv:X7KNZYJyd7+13Rb4arISzsuaRyqQIFg5p0AEINvIir8=,tag:/REB+VXybg/Zw7lWLmjdxg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x3eMI9LJUvwkS3QbgYSQyhuLgU/iHzpyyPkskSkWMoNbSTf7UnUWkKUN12SvVjObr6IfRQsQyAXqo8BMGdjCeQ==,iv:5CzA1Rb7+zG3iRkkTUmmGcfqQcVZgSM6BCLF2vpwPMU=,tag:kG7SSWOHLqG15WETchpPvg==,type:str]
            MINIO_ROOT_USER: ENC[AES256_GCM,data:jW3wZwHgsG6aVI5dxqdNqajfhfAEhaiM59w=,iv:oBMSAooIImVfHteKroMgSeyh7A+b9AaBg85HH0yWhW0=,tag:ZQQl3pl2pxc2c+nMjcLwrQ==,type:str]
            MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:+GKkJopM8hmDsa4iKQMZn/2a3EUm1jyBLVZRRp2UnB+Wt64Cbql5XzeGuqJ7dj1DcoMhsk62JGTQ8ZkVrR6gcw==,iv:5UN18J+3+3Qs6HkdatXqiAo24ikZLrlHb32xo0/+DLc=,tag:CP0Rt6OxP1omqhC3nUTafw==,type:str]
            AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:Q3Axg3oPqwElLihRsCbe8e8cZmoRVxm7uKDNdxkFIAaHaXb2GHxiT6hMwA==,iv:v4EFNS2NU5lFmMhfKZrC9mIWW0q4xJGCuVBQOIO7AgI=,tag:V7cCNxRFP2wvfA75VRoEQQ==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:6vcUMwlh,iv:ZkbPXpVaoszRfy7snX4hO0HcpVNlNP+Qgd2SRVgAZdc=,tag:xQ3EKdS8MBX++3zwLzyp4w==,type:str]
        - name: plane-rabbitmq-credentials
          stringData:
            RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:WN0A9So=,iv:uFb5CFjWT88At5dxbQD2mcQPtk+PDl4JXZkcOWkYh6Q=,tag:kt7BCRqG73LNPzLbmUIuvg==,type:str]
            RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:SuA661seNoSiBI8YJ+RocbtK3dLEm4QY5BUDrgAwZ3E=,iv:qKgUEPYKMoyIqBcI4Y6VTrQfLcICr1CMDAR8Mq9GuyI=,tag:l8KmnY26ty27rE9GQllmpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b1FZWUwzTC9zMEZMb2F3
            MitRSm1SU291enhoKytOazN4WE5yVS9mcVNvCkhJMytrNDZiZ1JoWDZTVEJQbXVq
            THlERjhpQ3MvQnUvTkpRU2lUQjlxR3MKLS0tIFBYWW53VUN1ZCsxY3dOQ3NwU05Y
            WnhUM0hoWTk3N1ZlYjZYODc4ZlVRVmcKDJJcOzOOqzvVmWrolJEKjnNwYcuocppE
            1q6LpIx5AbaO1y45qDZE9DatweRm4xr+C6bvEeraaOOBAsfa3ma6wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T02:59:59Z"
    mac: ENC[AES256_GCM,data:Agms5zDo5+sJJ1A0v6j2th7XEQmdGxh3oGldB9QHOeb67wtnQu65nT4O9O3UJa0UlQ7WBSi8B8euBRVhrdIeyu36sWFdHJyBs/QqvSGjeFwMYsTfsBEDoYWVli8gFHCo4iHIOrIV2re1wfwZi/BKzSUOW2758rtM93RZjL4KHf4=,iv:+wqATawnbnY/buXWKvj6WI5xihVrFoWAe1z7timeARo=,tag:mHSRVyVWNg8sRP4BQrS67w==,type:str]
    version: 3.13.0
