apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`uptime.elposhox.dev`)
    services:
    - kind: Service
      name: uptime-kuma
      port: 80
