apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uptime-kuma-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: uptime-kuma-secret
          stringData:
            UPTIME_KUMA_DB_TYPE: ENC[AES256_GCM,data:hMXke8KNQA==,iv:uHOtfi8sTwRXl5Ysy9pp2rvDwfDu0kW25UDneUYssCg=,tag:N4YA4xeMgAEGfRTb/YJOSg==,type:str]
            UPTIME_KUMA_DB_HOSTNAME: ENC[AES256_GCM,data:FjRmg+0Y078VdLR364ho8TlfjHCDn2jcz01m,iv:W7Ja6PmcKdZoagS2i2RzrM6EauwpcSh2uFynn2MiEe0=,tag:CSSWuy+ZIER1vP5GRPDrYQ==,type:str]
            UPTIME_KUMA_DB_PORT: ENC[AES256_GCM,data:8SJgsg==,iv:LPnkbI0MC4Qa/kCV6HHmdfzdpbnte3b/B6W4nVRp39s=,tag:47G+QMh9PCgpBJGAwLRgzQ==,type:str]
            UPTIME_KUMA_DB_NAME: ENC[AES256_GCM,data:Tpyy6AW+Ppk284s=,iv:O1A/AM5zytndX+K2yVY/Ny6VgtWADrE3/rUOAI1KU8o=,tag:wyMt1/eN8SF/rIFK0iYQVA==,type:str]
            UPTIME_KUMA_DB_USERNAME: ENC[AES256_GCM,data:HZDBGQ==,iv:241ZN5bnYkihwi/xLopKugvpnu20sK4pozjJ6odaOcA=,tag:xhzhcJ7W2KvapxbIn0nUGg==,type:str]
            UPTIME_KUMA_DB_PASSWORD: ENC[AES256_GCM,data:pjWfHE4DQok7RwFM4tPatI206Umvf+idpTVAZRCY1ec=,iv:u/IRc/S2KEGQ66P6mAubzOBAfQCL30GRjmRrK5NZ8rY=,tag:UDgYEkSVe+B6JHHIF884dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeXBVakpwK2lYbzdnVUtE
            aHdsclZjWGpNN1Flb1NCS2ovem04a2ZXQUdjCnQ2WTEvdGdlbS9hRG9Od054K0NF
            QkpsWFZDa3RoN3kzc092WUY0MDB4ZFUKLS0tIGRhVjhOZXFXTkVQc3pjd09oQkgw
            TmcwZU54R0Zrd2FjNWZOYldzd2xWZHMK/8eh/dyWhX/bN8u5msStvJK2lKvbh1y7
            dys1ZAYWZmDr4QO43ndYgO0aigbxa4DDp0LSdbC2HhJPD9P1uW9Qiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T01:55:37Z"
    mac: ENC[AES256_GCM,data:d7y+ZIyL7ZQghhD+VM50k5zE9Xd9umkUMFddp2CjAjxykTJz4iwg64zz6P8tD33jhIm3joOOYxZ6XDhuYCTH6NCdSGbSNq2nE8G8DzPxZjeCPCNRgMivcYrMrxIuCCAkZkoZ5APkRzj4zI7edf6hKNJ4nAyT4ZrtFHPkc70KWOU=,iv:6Q+H4EgI8ge6l2QgN9ANyX1RKjh+JHnY9cUPrwiincY=,tag:aVAhH2T+J84b9J0QmKGb5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
