apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uptime-kuma-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: uptime-kuma-secret
          stringData:
            UPTIME_KUMA_DB_TYPE: ENC[AES256_GCM,data:0mgXbmtylw==,iv:qHuMUD2U7hU+9Ru2Z68wKsInEFXG3DvoaSveHKSuWOc=,tag:361GOigC0fDHR+vjFHtjfQ==,type:str]
            UPTIME_KUMA_DB_HOSTNAME: ENC[AES256_GCM,data:pkZYxfir+6ntRT6COUzqdwLaQesTYhk1/gGX,iv:TmcVOFTPwURt8ccRU3uCOW4D3EXg8xS51npsDDqeLLk=,tag:4QBRO2kyDTmBfnpgkSZ+Kw==,type:str]
            UPTIME_KUMA_DB_PORT: ENC[AES256_GCM,data:YRwGpA==,iv:fup2nA3mGz/2PMVeyhosMruP+O7n6mMnQt9bKqxGbhM=,tag:c/uxcMft+B2aig5Ubu0XUQ==,type:str]
            UPTIME_KUMA_DB_NAME: ENC[AES256_GCM,data:KT7EnArVmjRrSqI=,iv:qfZ+Uov2ov+bg/vQPE6Lrdox7CZtMXm4ALOVfm4KO5o=,tag:IFYSzHxPmlQApAfTf5O2Tg==,type:str]
            UPTIME_KUMA_DB_USERNAME: ENC[AES256_GCM,data:/H1DiUjd,iv:tbeXmLEyA9acxmFUprv5ttK+1kw6OpxuDYaydddc+9A=,tag:pk1Cx6GUU0yHd/wVJDXGEA==,type:str]
            UPTIME_KUMA_DB_PASSWORD: ENC[AES256_GCM,data:HLo59eV6OOTack2vGR4QD+k8e+pyjhjGDuRDDGsCT5Q=,iv:1Us1R6lWx4/p37jjojB3dPqqFI1lb974vDa2FtDfywo=,tag:1ee339BjSG5znN41CcGrEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByKzVYeDBMQ0ovUkU0eDMw
            M21ZTE14enYzeFN2YVdPd1VTWHFpY1FzT2pJCmJCNVM0WlBJUU1hdms0TEtEcG9E
            eGJvR0pRZlFkOU9RSkJPQmRSRDhJQkkKLS0tIDVJajlmVTNDOXlnOGIzdHhMR3B1
            SzFtbzJnOWx4YTFCT09KTWNXR3kxQVkKxic3GuAwejDJb8ncvy6QK4Jn/pA1xJUh
            pa/3tqBUWszvDPubPA2WIo/oULOGYG+hpKFoiFsaQ02YiVXE/g48oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T01:57:06Z"
    mac: ENC[AES256_GCM,data:aV7vf7Eg6tE7yxyjn0azjzJ5owUXYkZK/9QmQHt/4/NIVXe9B2VSrFV1Knad23KXcX3fsLhpek7GPEmX4oC4JPmF82Ar5d2uOMU0D9bFBsgMv7JPLpA5YSu5L4xK04a3b43Luun/hmWxD77cvRkAFUAE5mX+MRQ68TTUA6+0Z2o=,iv:VC02JP4wH4WVhj8mz/nUv40eVCfIVv4hE1BUj1hetP8=,tag:GWn51q0+/qqLFnRvQv1PoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
