apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uptime-kuma-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: uptime-kuma-secret
          stringData:
            UPTIME_KUMA_DB_TYPE: mariadb
            UPTIME_KUMA_DB_HOSTNAME: uptime-kuma-db.elposhox.dev
            UPTIME_KUMA_DB_PORT: 3306
            UPTIME_KUMA_DB_NAME: uptime_kuma
            UPTIME_KUMA_DB_USERNAME: poshox
            UPTIME_KUMA_DB_PASSWORD: EFRV@P6X5&Qs0$E%@1oNd6x$u7zG$x@R
