apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uptime-kuma-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: uptime-kuma-secret
          stringData:
            UPTIME_KUMA_DB_TYPE: ENC[AES256_GCM,data:fVZcgYTY0Q==,iv:m+tKe7GgNdJNfgE3gkxHdxtDRXb+Dco7coo4sB95clc=,tag:IIv801n/jRUevTLZBHbxLQ==,type:str]
            UPTIME_KUMA_DB_HOSTNAME: ENC[AES256_GCM,data:vd5fb8ZjYXmo3AFEu0DXuWDunSCUTwr8oomD,iv:EsSwmIAtAuoZXHuVyH+Rwlvb0XUtdRzC5Du0sfj0XvY=,tag:SWt1UtiBwMtWGsjLDIHI4A==,type:str]
            UPTIME_KUMA_DB_PORT: ENC[AES256_GCM,data:gLlJ2A==,iv:V11eVO98dLocyE0Q2OHR4SmTvtDnITzgzKChm2dZM8E=,tag:hkyld7BIwSBZ6F4DPnxGnw==,type:int]
            UPTIME_KUMA_DB_NAME: ENC[AES256_GCM,data:wMmnd8qSAXwfUSY=,iv:dHLJyfFbwjYUwlUHJj1gr0EQQpH5Cr67bkKf/r1HG34=,tag:7nelLOgU7SE1pzBnv3V3EA==,type:str]
            UPTIME_KUMA_DB_USERNAME: ENC[AES256_GCM,data:HNkBVVhq,iv:0Ie0ZYvsg/aldsGwYXHljN/2o+awr1T3oJ8rW55bigw=,tag:E4Oj2AWZFL9HVOnaP1du1g==,type:str]
            UPTIME_KUMA_DB_PASSWORD: ENC[AES256_GCM,data:McPUeyB50kV8jDMLkDHcE0NWFDxxMEUyKY8dc9mDPkw=,iv:ba0hAYRPmoMjUIfiBN0nEr6/MbyqZGb6yQc/Dqxeukw=,tag:iD2QUBGqa4gsNW7lk88jnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdTd6NWN1ajV2VUNscksz
            bm5FZGY1MW5ZMUNJcldENlZNaVlWQWJKQUU0CmZLU0gxQzlEaWpmUFgxeU5FWXVa
            bTk0ZTYwRHFVd01hUmFVakVFdzBkUmMKLS0tIGdqckZHVFhXdGRkSTVkeHppc1M3
            WlkzRm9kZ09JNERIZkFKYk1DeEltWmcKvUD2PhdvrzzsY/E1HcIleklpOeqcpdg+
            HS1fzmX7A0T2yXHw43oI1EFr/3Jt8paoNlERaNIY+1AdkcRUOnRAOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T02:06:06Z"
    mac: ENC[AES256_GCM,data:w1d0kvsBCM7Imh3ltaQT0ox4xMQjtt1/3j9FUGNPxOSJAvLYfY+PHWYKmVmBSI9Ehb+IMEIKJMbRelWC28qc7yG5b9/XBdHnCNUoU2W0sbk/Frsz1PkYzNZJrPP2SYOb9UP2KG3prgfnmucrXnDO6SFGb0BB7bcvlEf74+SHlm4=,iv:56UYcYgn420A9mGKPE1gmRAuQPtPiyLeKB+OEz1QRhw=,tag:c42YUTjd0lJTKD/K4FCPQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
