apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uptime-kuma-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: uptime-kuma-secret
          stringData:
            UPTIME_KUMA_DB_TYPE: ENC[AES256_GCM,data:4gDFrcZtLg==,iv:ElQPdWKpgotJ3zjC39wmp+I9mGFJOmPGOl7F5fQAjLs=,tag:0cLitgOdExuMVlKXBC6mFA==,type:str]
            UPTIME_KUMA_DB_HOSTNAME: ENC[AES256_GCM,data:+89Zm2uY4AMAqWAhQsfMyyAHfw8useHJm7UE,iv:+i1rXd8gZj8kMnOiEvSUotMlGhiLVs6gix00Quccp3g=,tag:PBCk18Zdz2G1t+Dgd3Xl/w==,type:str]
            UPTIME_KUMA_DB_PORT: ENC[AES256_GCM,data:yCPDXw==,iv:2T3sFnmmq5ySZGuLhVaPrBoZl6/mamygPbef1KUpChU=,tag:mH9vQG74WdgOMiMsVuwFpQ==,type:str]
            UPTIME_KUMA_DB_NAME: ENC[AES256_GCM,data:RYV4cJWgyzsEyZg=,iv:ae+nweWxqWvxqwE6SdL15mHzrh2kiiAN1HlcwZdyXmY=,tag:RjnjUQQfBeRzubrt1icYvg==,type:str]
            UPTIME_KUMA_DB_USERNAME: ENC[AES256_GCM,data:tPQw+Q==,iv:vakf0HMbhlVont9dPl44/LAczlDAVb3zuFH8x2pv5JE=,tag:DlWHMg/lnHCYVFQ5nO73zg==,type:str]
            UPTIME_KUMA_DB_PASSWORD: ENC[AES256_GCM,data:SDae3ZgbLTreorHiG2ecggIP0q6cE+bvrlOkU/1MONQ=,iv:dWOsQr+tFAfhkW06u6wVYM/2rcW3fR1BOmxexquDRXI=,tag:6NVlBFFaCLOZVqabdeypXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOHlZV3UzTWgycVF2S3BB
            MTdRQWhObnhOWVR4a01JcVRQK1Ixby9wc3pZCnRlZ3NEclByNTJGZEhNQ0NWVGR0
            NkUycnhNYlVKUjZPcEZIZHF0R2JlaEEKLS0tIEJ4LytVdXc0OVpjRkVyOW84NGp4
            SUx5dkpoN3ZZcW0rdDd4ZHBHTlFTWmsKtp0+s+Ivnj5iH+d1czfe49C0NIO0dtv3
            EFLeDDVLiGH5lsn0z3l+DWNscHefkuvovDIjMie+to0btqM6NzOAgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T01:28:24Z"
    mac: ENC[AES256_GCM,data:9P6FCBsQSPtmGR2lPJOqP1H2/lZ4kDrCJIlX4fNsWhbc6hZjqvqixmqMeMAnk3fp4A4jeTxKHJZOjq1H6FeK3TADvwozIi6Oklk1ry4hObZA9hbNwcMyaUYNoSyTi2CtCEHuA4g/uuQrMH7Ogy77sBpo20s2WC/IBmGM2SnxVRs=,iv:l1jp0rGljHo8a9uE5Iv2jrjl0/lUQA5N6VdHiZymu4k=,tag:FuTixkJzZ/QER71mnrzv/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
