---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic
data:
  dynamic.toml: |
    # Dynamic configuration
    [[tls.certificates]]
    certFile = "/certs/tls.crt"
    keyFile = "/certs/tls.key"