apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traefik
    homelab.local/OwnedBy: ElPoshoX

resources:
- https://github.com/traefik/traefik-helm-chart/releases/download/v34.4.0/traefik.yaml
# - https-middleware.yaml
- tls-options.yaml
- tls-store.yaml
- configmap.yaml
- ingress.yaml