apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
    app.kubernetes.io/instance: traefik-prd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: traefik
    homelab.local/OwnedBy: ElPoshoX
spec:
  selector:
    app: traefik
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: traefik
    homelab.local/OwnedBy: ElPoshoX
  ports:
  - name: websecure
    protocol: TCP
    port: 443
    targetPort: 8443
  type: LoadBalancer
  loadBalancerIP: 192.168.3.10
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Local