apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: adguard-home
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/instance: adguard-prd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: adguard
    app.kubernetes.io/part-of: adguard
    homelab.local/OwnedBy: ElPoshoX
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.63.67
  clusterIPs:
  - 10.43.63.67
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: adguard
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: adguard
    homelab.local/OwnedBy: ElPoshoX
  ports:
  - name: web-admin
    nodePort: 32350
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: web-interface
    nodePort: 31608
    protocol: TCP
    port: 80
    targetPort: 80
  - name: dns-udp
    nodePort: 32149
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    nodePort: 32149
    protocol: TCP
    port: 53
    targetPort: 53
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}