apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-conf-pv
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  hostPath:
    path: "/media/poshox/ehdd/configs/adguard"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-work-pv
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  hostPath:
    path: "/media/poshox/ehdd/storage/adguard"
    type: DirectoryOrCreate
