apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: home-assistant
    homelab.local/OwnedBy: ElPoshoX

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- pvc.yaml
- secret.yaml