apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: langfuse-secrets
    namespace: langfuse
spec:
    suspend: false
    secretTemplates:
        - name: langfuse-env
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:fjZK9sdVN3L8/8e6tLpD49BwDfxCGq8jqBSm/jasng8C6mv+UI1AWKMoyn9GwszBUYp7SR+eE986f6Wb03y4Ootn6DQ3m+RbxiZ6nIQ8tX5YdPWMd9LXCSX9+QQddJbhdR1IQsb6RFo=,iv:zJrAnhBuiFe3Qy3SXqybjWciHP5RWiULvR/0/t9/bgs=,tag:eqdSyqzPjGBaErV01UklCg==,type:str]
            NEXTAUTH_SECRET: ENC[AES256_GCM,data:FDOx4xuEwNO9pWch6FVqfSlLh2FvqkEwFtdDSrbl52mOFl7dGeFMsyfDlO8=,iv:G7ZDoW5sxJlZR7lpdaOg5heLvdMU6CPSOohZLhFk3kA=,tag:Bc7eH5cBBYNbAlsDfSg2+A==,type:str]
            SALT: ENC[AES256_GCM,data:3OcHI+c/Egi7XcIpfd30WlaeTnbhu/UpgziY0R61fcdOo6rGUochb80Fjyg=,iv:reCAFGazO7qL6t5QLp1TK4QcJkTFvCnI4sFXLFXvPHE=,tag:zZ1uQy5pOrwwY/OAMrbr2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSWVSVVBoYTc0dGRJMHBI
            eUkzc25RNEFqVTR2SE0zaW5yL3QzclVwb1VnCkt3WitqMWhoWlN0b1ZCUnR1bXJK
            M0lsaE1uNzhWamRCWUtzM1cvRzJsZncKLS0tIE9rWnQvWGFXOFN6M1A2cVZaZWw0
            QXN5VmFOOXZlZjQ1NStWU0tncUJLeUEK5Q4D9P2lqJCfmaoAkMvhae/O/dM79qmF
            es2M/AiZ38Ee/JWGiIaC9FG0pIWC+cW8S7AVkH4UhQdBNPW4sa4b0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T02:53:34Z"
    mac: ENC[AES256_GCM,data:jFvVH64ca84x4AmUS7GlofY8aD2XFv+VOvNY4W2bKGCNaBxmfYoPIdsP7LenwhVP9vM/emkqehoUaXGv4eu7N3tjNE9Z/PEPbG9DYvATojN8/stkB95wRNX/dIOXumKsK5Bq4LxAn1bLviZ5CVtTDgueSwOu+Lv3cgegxJKVG2I=,iv:vfFJTblYr9+lRwsWdaBfLchgf5kotgFromhQ3wHiDl4=,tag:oOBxxttGZU10rZFZ79SZ3Q==,type:str]
    version: 3.13.0
