apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: elposhox-dev-cluster-issuer
spec:
  acme:
    email: poshox.pr@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: elposhox-dev-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: poshox.pr@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
