apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: cloudflare-api-token-secret
          stringData:
            api-token: ENC[AES256_GCM,data:wnrqxRWZF/MrxAyXr0U2zCOcmEHtbym2lER7dvuGmyFDPRCj5CmBCQ==,iv:Vze9ugxNZAHZ5G8QZc2gZBxwI9ofoMmTMp8v8++ReRs=,tag:tO/RRUuhXqXAzoAn2LLSVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZnFlMy9JYkJER0VxcGNh
            aFhZSlZoYmFMeCtCMzZlR2hqLzZHbEtxZWtvClNEekdYR2VWLzBQQXhzOUdpN1FE
            MXgzenBuVWpPZkxCcmVMa0hTdWZKU00KLS0tIDVoYUlUc2NzMEVZZlFnOU1GRGtx
            WWttdHJlVlU4ekRSa1BVa1h3VzVJTGcKHYgh1lAXimFBWgRGjHFhbP+54wW4gkUk
            Ly/TJn0hjkbcU7UCuJIIF9hddxC7plAVXXxzu+x9V26e6Gdu788DRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T17:38:37Z"
    mac: ENC[AES256_GCM,data:IsOzRH6pN2Qg9Fu7AnyNvpgEfRUJJe/1Jr+nDBDI2DF/B/ucQM+7xo1rKHTRtHoviVp18LDtd4lwqidqhGKJnez4jS7a4TRt0COsY0/N/YmFxN+XZPu9FXTpTi8bIjiKrwXfwD97mufSmjTqESK8TGYh1N331ucSnkTQoJwqLhg=,iv:Ma3rImXu2T5kMyOCmnTEZEK8mZ/pRUk8tbJx23WG4P8=,tag:2CafsfrjzSITaECR1C8hXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
