apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: cloudflare-api-token-secret
          stringData:
            api-token: KNfX_gFCHizCJaQtCjShQLEaoWXfmLWavrAE14AM
