apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: aegis
      homelab.local/OwnedBy: ElPoshoX

namespace: aegis-exporter

resources:
  - namespace.yaml
  - deployment.yaml
  - servicemonitor.yaml
  - network-policy.yaml
