apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aegis-exporter
  labels:
    app.kubernetes.io/name: aegis-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aegis-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
