# Encrypt before committing:
#   sops -e -i apps/hermes/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hermes-secrets
    namespace: hermes
spec:
    suspend: false
    secretTemplates:
        - name: hermes-secrets
          stringData:
            LITELLM_API_KEY: ENC[AES256_GCM,data:fJPtAvUL2RmjCwo8+ucN9EpGA/WwObxmUQ==,iv:353o106EVEOFDra2HSxgoJKvrr1GgMYNWlnlyYqLwrA=,tag:atVFHitnNbWAukrlVWSCQA==,type:str]
            API_SERVER_KEY: ENC[AES256_GCM,data:AfJnSOTe/x3eLrc6gOJEpnVwY0W1KuFC++4t1Jive9oMyxThL0YhWLtqqcnN7kebB4Ed1t+LOlBYkgJ+oioDoA==,iv:KyV4RmgtsgvgIdazhrcnDM17lf8Mf5efcc38bjg4PPU=,tag:wGI3RkEtk761+nchRh4W1Q==,type:str]
            DASHBOARD_PASSWORD_HASH: ENC[AES256_GCM,data:QLX+Nc+KkB7tTLhEJvRtGPhFtg1UZDNO4NzEvY+Lzep9TSNTBmTlAE+OXv9rGEVagP2c+sVyXxrQQOzGlI1O7QLeJpLqpVoXkvI8KaUANhJzkt7/2zg=,iv:/ESnn3yKjfPBHi9WfJweILJ/jLK9ufBkH8ES3rmy4hI=,tag:ejfNBpRnfCvP6Cz5SxQmvw==,type:str]
            DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:l326Ob41JowGaKiu1oFwRqyKXIxDmtbI7mCRmPjlmL53qRLeURj0u/khF26Ewxj1C3glb7KPlN66kE4IKeaVN8yuL+ikZQMe,iv:9FiKLcUIDqlL9mVmjuN2NxlSf5xxzPyHWpDbjxOClEU=,tag:wis8ULjiYiGdcC6fqVCsvg==,type:str]
            DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:Oj3oQYPScA9tS6T8MEirqfgLGw==,iv:mqAEEY4QjrrwoLqrNLVYyRQEI74f3JxfmthEyAvR/gE=,tag:IRADe8Ihn0K0ImZJAjjcVw==,type:str]
            DISCORD_REPLY_TO_MODE: ENC[AES256_GCM,data:zvEO,iv:LxvvXiyt2h4ea4EDi7kV5xue2YnuPffTJHWYv40qhwk=,tag:7uCNUt9UL20l05Ac62aY7w==,type:str]
            DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:t/SfX2UyovJGFHrNtnjmd1sC3A==,iv:InIApgIMKvZCFtZZEXG/WPsK/2HXcXpCXJGAUzJR5AY=,tag:YpYGZlhbow6KxYGaBZnsPA==,type:str]
            DISCORD_HOME_CHANNEL_NAME: ENC[AES256_GCM,data:WBjQ09BQIsYAze6QiYX0ie9ac90=,iv:iSH5o52gzxbgQYEs3eO+tCuUUbw7+se3sGT0aZrZr38=,tag:vXMoP9FWcEkIeEpsuU+juQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUWUwejg5Y09wOG9aUGFW
            SldwRmFPUERBbDlKamMxTG9aTnVWWjlBUlFNCkxTdTRMandSQ1kwdDZiWTM3ajBM
            UExtS2ZOVStxMUJNVXBNc28rdHRzZ0kKLS0tIE1qU0ZxU0VtYjFIb1hjWjhqcmRO
            RWRDSXFMMEJvc0VmVjZ2akptb2l1dkEK/MyGlAnlckcx2XsPKpLeoHgQBPXBiSfH
            G63Ax8QuDUP1i0wMf4wHvY/LWG8yFC1WuExIQnQfsSI6ojNQJ2T48w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T00:52:49Z"
    mac: ENC[AES256_GCM,data:mLMTGrbOo3jhTaoeYkNBL04dGTHJBDDqjV4sVY9tFW/IstCXsPsaW8LB2fAPXeDOG3mp688dKCfEiD1oYLyc2ygVOQQZsEcjhIxLyN9bOkTG2Pmb8ZfswMQwzS0oto3aaIrENTDSgOCcLdOvRvn8TRrH2Whrzktq8Qy0aQa1wKc=,iv:3lfLtDK5aH2AV07U4g2nJlhgpTLNcTI9e0xLUUVZ7/E=,tag:EC07GNIU6U2osNJ7uBN9nQ==,type:str]
    version: 3.13.0
