# Encrypt before committing:
#   sops -e -i apps/hermes/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hermes-secrets
    namespace: hermes
spec:
    suspend: false
    secretTemplates:
        - name: hermes-secrets
          stringData:
            LITELLM_API_KEY: ENC[AES256_GCM,data:E6ZtPUCvNwpJwZJSXIDiXAM3UWFxsz+mZg==,iv:xXRfgk+CixOPn5pWTSrLImokaW1lMPSC+xK+Zu+WLgk=,tag:Q2U4d3p5RFQKVXIkrP/Grg==,type:str]
            API_SERVER_KEY: ENC[AES256_GCM,data:W4T88SBJf6UWTg6yMybkQMySB9HNsIn2XriKBe/0+rs6oovPifOhgb7ecx069DBMm6j7/4kNoz7Vq9SUj+p4/g==,iv:ofHE+qujYDcNfkth1GLnfzFLBQAkxqLzZhezOgmZ+cU=,tag:nCGmG8YjwtWCATSqXOkS0w==,type:str]
            DASHBOARD_PASSWORD_HASH: ENC[AES256_GCM,data:r4Oul6dYiUvjpG/pyiKz2YOuiN0CiDFR8fyhGJ4mN8jlFfdYOlf2LNSuLiK3U2mScYm2YnXLOAHK5XRnmNuPFyxt9DclB+rj5FJlOlFTpY/GNrr7g+Y=,iv:xnaLpISZAB3wdS54xF9+0mtp1T27KvksDAAvaM0bln8=,tag:iZezEL3uah9EUI1AKafeJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZlpFZGRvVkhjTHlia0tF
            Nk9BTjJWNHduRUZESUk5b25ldTg0bkMzMUJzCjdxbjdsZ0ppb1JBNmcreUxvcGd4
            bVVubWYvUjhEd1o3RHViQ3JCbElTSVUKLS0tIGliNlNaS2NQejY0am1DTFhERXhu
            WEdvekVsakY3a2Y4ZmU2QmFENEtBUVkKjDCF11y4oHYRO/7CQ9Bw8pB1HAvQ1+dQ
            A/b+XhdTA9ftZc508zIyAR7iraYKhNmjG25sOZTgI70gi4CDLf9/gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:22:54Z"
    mac: ENC[AES256_GCM,data:hRD4+G2ZnAETsekdlGJ203i3r8zLaESl6+Y0YDwB8y2xWlPv2Pm71FKntVPShP3T/C0bX2iWFS9zHYZTE7jMZlBDfLYc8Q1ApOjpL0gFRB1JWX3p+xjz/Ym52U2ozVDG4NmK7N1jDvOd6XQViEEDAX+SyBNmO1y7pPwtdLvVK34=,iv:bNOQHa+jpNCFWZVITWQt3y7MSXdql/crtOSktwVN6V8=,tag:T8guKXiuFmXtgv/o+TXpBw==,type:str]
    version: 3.13.0
