# Encrypt before committing:
#   sops -e -i apps/hermes/base/secret.yaml
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hermes-secrets
    namespace: hermes
spec:
    suspend: false
    secretTemplates:
        - name: hermes-secrets
          stringData:
            LITELLM_API_KEY: ENC[AES256_GCM,data:m5uzTKisCjyiJwNkrupcNawqzzusDLxrtQ==,iv:i8MLq7DUHs01yDEgsA8F5Dxn9G2MOSwYJorrsHglJU8=,tag:m7gMYgJZ1lSqYHEqHWHjtw==,type:str]
            API_SERVER_KEY: ENC[AES256_GCM,data:97ZcoIBhRRb58ifn6CL6FepEFVpiWxE7kYT8pVBZSjX847T3kWiU3oXSlcXB4trNBbitgfRf3GsavTDKWIBPTg==,iv:ClnbnTLRf4nxPp58kGWq7JP6GSyZ+HXW832DX8ubiX4=,tag:cKBAg+kxxvGk0HHYdNgNNw==,type:str]
            DASHBOARD_PASSWORD_HASH: ENC[AES256_GCM,data:sPGRm+R4nZB+SCOoY45akfZHpTdim4Kiow792ZCnHk4NnTG0yOHlxT3YHR6Z5mcCgV1PFpV/yT9BbPh5gqGsDGS2JFBSnuRw/kr1Srfk95/B1uh1poE=,iv:8v1lRsdLnWBzBSgMubuK6P/yaWlynVnICBXGNtmLmVQ=,tag:AI+FYbbCn9s2qCsVxlosaw==,type:str]
            DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:FzG14ifUQdFagXsVSJGYB8XUIZ9AJotERgTgKJpSGyN1+pdS5V6HIgOLVNhoCxdgCcgr73alzcHk71Okgd/oP4Jm1Z1O7Q7o,iv:tsP7krDai+/zWyWeZa6lCV5P5sNY5KVHDA/nvg8LpaU=,tag:4IBydnXOkA25M/GURk138w==,type:str]
            DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:kUNT1j9vnsICXuU1yH4Q5e0Y1g==,iv:dflMgKuHjR4mpLe9aDyGy/0EtPCIqzJ8DxWQKu0Y8mc=,tag:WFmjSACiXnJRKmSICNuWtA==,type:str]
            DISCORD_REPLY_TO_MODE: ENC[AES256_GCM,data:AbHj,iv:geqGqKGN+d02seJnxf5RMNfA7MqvicSRTMnnmXxijoQ=,tag:75kJZ5WQ0HhBt2Qs5c15bA==,type:str]
            DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:aCpeuA/FSFXMSSz/wfiZ6GgzJg==,iv:lWhKSpIQ9+IsBZTKKh67VEHmlD0DbjhXFkZNKdVHrEU=,tag:ZpsUlLwe5IMEcOPo4p9k1g==,type:str]
            DISCORD_HOME_CHANNEL_NAME: ENC[AES256_GCM,data:OHiZxoeZNCYCjRysJFaABd7vWTI=,iv:Wp8CHKwjjJx1+gONbcNE/fbo+O1jzh0E6KE5vSMhPgw=,tag:+I1ngVvsCv4o/Xye5VD9ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL0dLLzhwc2JzTHNUTkQ1
            MG5wUGEycktBbTVpc3NwYS83Z2tmdXYzNEJVCnNhc1NGcnprMWIyU3p0dloyZG82
            SHFVdjRmTW12ZEc5S01vNkprOHR2MTgKLS0tIHZPMW9TOEp5anF3SFM4Sm9kbWoy
            dTAxZjhPYlRXcnFpengvQ21IdzhnenMKzdfkE/nkifamYzAYj4j4R2aBGDt9Wdz1
            kkA/3DgmKeFQHhXJTUkL7DRT2qW1VKhFA9a8y5R1ebfxCV79aZ2vyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T01:06:21Z"
    mac: ENC[AES256_GCM,data:lWfrcA/727pZ9+JTUcsq1RSg/8pqtwM/J6e3FU3hKLDA4+XTCXiLmTjxoAuCMfSPHZwFkzGNCI/LTFCfq3578nztztRZnrm9hNUfU7xK4/1f4MzGBYc09dGS1xT2oK0jX5nzul726is32UAYFS3Hh6A1eNheciMqsOPqCYcAlGY=,iv:j8dQlJKqmr6PsQP1RtYyRd4zcOQnc1Izj9IZoLjmlSk=,tag:WMvABUf3B9sJd5A47hVzlA==,type:str]
    version: 3.13.0
