- DNS:
      - Primary AdGuard (Pi Zero 2 W):
            icon: adguard-home.png
            href: "{{HOMEPAGE_VAR_ADGUARD_PRIMARY_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_ADGUARD_PRIMARY_URL}}"
            statusStyle: "dot"
            widget:
                type: adguard
                url: "{{HOMEPAGE_VAR_ADGUARD_PRIMARY_URL}}"
                username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
                password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
      - Secondary AdGuard (TrueNas Scale):
            icon: adguard-home.png
            href: "{{HOMEPAGE_VAR_ADGUARD_SECONDARY_TRUENAS_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_ADGUARD_SECONDARY_TRUENAS_URL}}"
            statusStyle: "dot"
            widget:
                type: adguard
                url: "{{HOMEPAGE_VAR_ADGUARD_SECONDARY_TRUENAS_URL}}"
                username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
                password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
      - Secondary AdGuard (K8S):
            icon: adguard-home.png
            siteMonitor: "{{HOMEPAGE_VAR_ADGUARD_SECONDARY_K8S_URL}}"
            statusStyle: "dot"
            widget:
                type: adguard
                url: "{{HOMEPAGE_VAR_ADGUARD_SECONDARY_K8S_URL}}"
                username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
                password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
- Containers:
      - Portainer:
            icon: portainer.png
            href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            statusStyle: "dot"
            widget:
                type: portainer
                url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
                env: 4
                key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
                container: ix-portainer-portainer-1

      - ArgoCD:
            icon: argo-cd.png
            href: "{{HOMEPAGE_VAR_ARGOCD_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_ARGOCD_URL}}"
            statusStyle: "dot"
            widget:
                type: argocd
                url: "{{HOMEPAGE_VAR_ARGOCD_URL}}"
                key: "{{HOMEPAGE_VAR_ARGOCD_KEY}}"
- Administration:
      - TrueNas:
            icon: truenas-scale.png
            href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
            statusStyle: "dot"
            widget:
                type: truenas
                url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
                key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
                enablePools: true

      - Longhorn:
            icon: longhorn.png
            href: "{{HOMEPAGE_VAR_LONGHORN_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_LONGHORN_URL}}"
            statusStyle: "dot"

      - Proxmox:
            icon: proxmox.png
            href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            widget:
                type: proxmox
                url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_PASS}}"
- Media:
      - Jellyseerr:
            icon: jellyseerr.png
            href: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
            statusStyle: "dot"
            widget:
                type: jellyseerr
                url: "{{HOMEPAGE_VAR_JELLYSEERR_URL}}"
                key: "{{HOMEPAGE_VAR_JELLYSEERR_KEY}}"
      - Jellyfin:
            icon: jellyfin.png
            href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
            statusStyle: "dot"
            widget:
                type: jellyfin
                url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
                key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"

- Personal:
    #   - Home Assistant:
    #         icon: home-assistant.png
    #         href: https://home-assistant.elposhox.dev
    #         app: home-assistant
    #         namespace: home-assistant
    #         widget:
    #             type: homeassistant
    #             url: https://home-assistant.elposhox.dev
    #             key: "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}"

      - Immich:
            icon: immich.png
            href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
            widget:
                type: immich
                url: "{{HOMEPAGE_VAR_IMMICH_URL}}"
                key: "{{HOMEPAGE_VAR_IMMICH_KEY}}"
                version: 2

      # - Octoprint:
      #     icon: octoprint.png
      #     href: https://octoprint.elposhox.dev

      - Actual Budget:
            icon: actual-budget.png
            href: "{{HOMEPAGE_VAR_ACTUAL_BUDGET_URL}}"

- Observability:
      - One Uptime:
            icon: oneuptime.png
            href: "{{HOMEPAGE_VAR_UPTIME_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_UPTIME_URL}}"
            statusStyle: "dot"

      - Speed Test:
            icon: myspeed.png
            href: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
            app: myspeed
            namespace: myspeed
            statusStyle: "dot"
            widget:
                type: myspeed
                url: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"

      - Grafana:
            icon: grafana.png
            href: "{{HOMEPAGE_VAR_GRAFANA_URL}}"
            app: grafana
            namespace: grafana
            statusStyle: "dot"
            widget:
                type: grafana
                version: 2 # optional, default is 1
                alerts: alertmanager # optional, default is grafana
                url: "{{HOMEPAGE_VAR_GRAFANA_URL}}"
                username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
                password: "{{HOMEPAGE_VAR_GRAFANA_PASS}}"

      - Prometheus:
            icon: prometheus.png
            href: "{{HOMEPAGE_VAR_PROMETHEUS_URL}}"
            namespace: prometheus
            app: prometheus
            statusStyle: "dot"
            widget:
                type: prometheus
                url: "{{HOMEPAGE_VAR_PROMETHEUS_URL}}"

- Media Tools:

      - Sonarr:
            icon: sonarr.png
            href: "{{HOMEPAGE_VAR_SONARR_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_SONARR_URL}}"
            statusStyle: "dot"
            widget:
                type: sonarr
                url: "{{HOMEPAGE_VAR_SONARR_URL}}"
                key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
                enableQueue: true

      - Radarr:
            icon: radarr.png
            href: "{{HOMEPAGE_VAR_RADARR_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_RADARR_URL}}"
            statusStyle: "dot"
            widget:
                type: radarr
                url: "{{HOMEPAGE_VAR_RADARR_URL}}"
                key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
                enableQueue: true

      - Bazarr:
            icon: bazarr.png
            href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
            siteMonitor: "{{HOMEPAGE_VAR_BAZARR_URL}}"
            statusStyle: "dot"
            widget:
                type: bazarr
                url: "{{HOMEPAGE_VAR_BAZARR_URL}}"
                key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"

      # - Jackett:
      #       icon: jackett.png
      #       href: https://jackett.elposhox.dev
      #       siteMonitor: https://jackett.elposhox.dev
      #       statusStyle: "dot"
      #       widget:
      #             type: jackett
      #             url: https://jackett.elposhox.dev
      #             password: jackettadminpassword # optiona

      - Prowlarr:
            icon: prowlarr.png
            href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
            widget:
                type: prowlarr
                url: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
                key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"

      # - Kavita:
      #     icon: kavita.png
      #     href: https://kavita.elposhox.dev

      # - Suwayomi:
      #     icon: suwayomi.png
      #     href: https://suwayomi.elposhox.dev
