- DNS:
      - Primary AdGuard (Pi Zero 2 W):
            icon: adguard-home.png
            href: https://adguard-primary.elposhox.dev
            widget:
                type: adguard
                url: https://adguard-primary.elposhox.dev
                username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
                password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
      - Secondary AdGuard (TrueNas Scale):
            icon: adguard-home.png
            href: https://adguard-secondary-truenas.elposhox.dev/
            widget:
                type: adguard
                url: https://adguard-secondary-truenas.elposhox.dev/
                username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
                password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
      - Secondary AdGuard (K8S):
            icon: adguard-home.png
            href: https://adguard-secondary-k8s.elposhox.dev/
            widget:
                type: adguard
                url: https://adguard-secondary-k8s.elposhox.dev/
                username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
                password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
- Containers:
      - Portainer:
            icon: portainer.png
            href: https://portainer.elposhox.dev/#!/home
            app: portainer
            namespace: portainer
            widget:
                type: portainer
                url: https://portainer.elposhox.dev
                env: 4
                key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
                container: ix-portainer-portainer-1
                
      - ArgoCD:
            icon: argo-cd.png
            href: https://argocd.elposhox.dev
            app: argocd-server
            namespace: argocd
            widget:
                type: argocd
                url: https://argocd.elposhox.dev
                key: "{{HOMEPAGE_VAR_ARGOCD_KEY}}"
- Administration:
      - TrueNas:
            icon: truenas-scale.png
            href: https://truenas.elposhox.dev
            widget:
                type: truenas
                url: https://truenas.elposhox.dev
                key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
                enablePools: true

      - Longhorn:
            icon: longhorn.png
            href: https://longhorn.elposhox.dev
            app: longhorn-ui
            namespace: longhorn-system

      - Proxmox:
            icon: proxmox.png
            href: https://proxmox.elposhox.dev
            widget:
                type: proxmox
                url: https://proxmox.elposhox.dev
                username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
                password: "{{HOMEPAGE_VAR_PROXMOX_PASS}}"
- Media:
      - Jellyseerr:
            icon: jellyseerr.png
            href: https://jellyseerr.elposhox.dev
            widget:
                type: jellyseerr
                url: https://jellyseerr.elposhox.dev
                key: "{{HOMEPAGE_VAR_JELLYSEERR_KEY}}"
      - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.elposhox.dev
            widget:
                type: jellyfin
                url: https://jellyfin.elposhox.dev
                key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"

- Personal:
      - Home Assistant:
            icon: home-assistant.png
            href: https://home-assistant.elposhox.dev
            app: home-assistant
            namespace: home-assistant
            widget:
                type: homeassistant
                url: https://home-assistant.elposhox.dev
                key: "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}"

      - Immich:
            icon: immich.png
            href: https://immich.elposhox.dev
            widget:
                type: immich
                url: https://immich.elposhox.dev
                key: "{{HOMEPAGE_VAR_IMMICH_KEY}}"
                version: 2

      # - Octoprint:
      #     icon: octoprint.png
      #     href: https://octoprint.elposhox.dev

      - Actual Budget:
            icon: actual-budget.png
            href: https://actual-budget.elposhox.dev

- Observability:
      - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.elposhox.dev
            app: uptime-kuma
            namespace: uptime-kuma
            widget:
                type: uptimekuma
                url: https://uptime.elposhox.dev
                slug: home-lab

      - Speed Test:
            icon: myspeed.png
            href: https://speedtest.elposhox.dev
            app: myspeed
            namespace: myspeed
            widget:
                type: myspeed
                url: https://speedtest.elposhox.dev

      - Grafana:
            icon: grafana.png
            href: https://grafana.elposhox.dev
            widget:
                type: grafana
                version: 2 # optional, default is 1
                alerts: alertmanager # optional, default is grafana
                url: https://grafana.elposhox.dev
                username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
                password: "{{HOMEPAGE_VAR_GRAFANA_PASS}}"

      - Prometheus:
            icon: prometheus.png
            href: https://prometheus.elposhox.dev
            widget:
                type: prometheus
                url: https://prometheus.elposhox.dev

      #   - Promtail:
      #         icon: loki.png
      #         href: https://promtail.elposhox.dev

- Media Tools:

      - Sonarr:
            icon: sonarr.png
            href: https://sonarr.elposhox.dev
            widget:
                type: sonarr
                url: https://sonarr.elposhox.dev
                key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
                enableQueue: true

      - Radarr:
            icon: radarr.png
            href: https://radarr.elposhox.dev
            widget:
                type: radarr
                url: https://radarr.elposhox.dev
                key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
                enableQueue: true

      - Bazarr:
            icon: bazarr.png
            href: https://bazarr.elposhox.dev
            widget:
                type: bazarr
                url: https://bazarr.elposhox.dev
                key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"

      - Jackett:
            icon: jackett.png
            href: https://jackett.elposhox.dev

      - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.elposhox.dev
            widget:
                type: prowlarr
                url: https://prowlarr.elposhox.dev
                key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"

      # - Kavita:
      #     icon: kavita.png
      #     href: https://kavita.elposhox.dev

      # - Suwayomi:
      #     icon: suwayomi.png
      #     href: https://suwayomi.elposhox.dev
