title: ElPoshoX's Homepage
theme: dark
headerStyle: boxed
language: es-MX
target: _blank
showStats: true
statusStyle: "dot"
useEqualHeights: true
providers:
  longhorn:
    url: https://longhorn.elposhox.dev

layout:
    DNS:
        style: row
        columns: 3
    Containers:
        style: row
        columns: 2
    Administration:
        style: row
        columns: 3
    Media:
        style: row
        columns: 2
    Observability:
        style: row
        columns: 4
