apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame-deployment
  namespace: flame
  labels:
    app: flame
    app.kubernetes.io/name: flame
    app.kubernetes.io/instance: flame
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: flame-dashboard
        image: pawelmalak/flame:multiarch2.3.1
        imagePullPolicy: IfNotPresent
        env:
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             name: flame-credentials
             key: password
        - name: SHARE
          value: "media;/media;yes;no;no;all;none downloads;/downloads;yes;no;no;all;none"
        ports:
        - containerPort: 5005
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: flame-config
          mountPath: /app/data
        - name: flame-docker
          mountPath: /var/run/docker.sock
      volumes:
        - name: flame-docker
          persistentVolumeClaim:
            claimName: flame-pvc-docker
        - name: flame-config
          hostPath:
            path: /media/poshox/ehdd/configs/flame/
            type: DirectoryOrCreate
