apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: flame
  name: flame-pvc-docker
  namespace: flame
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi