apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: flame-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: flame-credentials
          stringData:
            password: ENC[AES256_GCM,data:8Sg3AJxZp6V2pL4H9DqSmHg=,iv:eDOwa14n+6Eq1OwxW3Aj+keVbHz+pWiFRt3TRF8/VxM=,tag:U+Gtju6PeJ0l3hOeSb53eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1unhax45cm95ngm2h984sq22v7uxm7rtle8mlrg4mfgs55t2kr57qxkxyml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb2NlbTVlc3VIM2hoN0Fh
            Q01EMVpreUJybEtZUkoxT2dIbDJhNm9FS1RZCjZwc21jVm5RWFNiazRrOVlBbk5F
            Nk4yTjRjNDhXdGp2N0ovakE3SlAwZW8KLS0tIEUvbG1EZlplOXptZ3YybW91TEpr
            d0pJelprZTFGSmo5Q1I1bGhVQXFmQVEKeoSu2MC9xQW6rcKpeDfwxnS0YyPN/G4m
            Mpox6xsXPSYE2p2/zm8gLEfFQcl5RNwDVa+Rm0ie9CJVI9GWAcLvBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T06:19:55Z"
    mac: ENC[AES256_GCM,data:vjeKYQoryNjrcMH/iNDn0flYO78xdd6Z7M1xaBzZOgnDjNsnAawa0Rr7Sw2W24i2LrSE+p41K2ehXJ18GU9pgVEIbW3Bt9GcFh+rtr+ujHCTaf1VUai5tnVpGFvbL4ouPNFjOvnvvC4vS41cSbBotJoaNUpSwcyKKNW4olJG/wA=,iv:Z5BmHHi9ZUPH2+4u7zGSgKBytdmo693qnjyH/3MXE2U=,tag:DTbpryx7fDHwwnT+V2X0XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.4