apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        app.kubernetes.io/name: n8n
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: volume-permissions
          image: busybox:1.37
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: n8n-data
              mountPath: /data
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: N8N_HOST
          value: "n8n.elposhox.dev"
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_PORT
          value: "5678"
        - name: GENERIC_TIMEZONE
          value: "America/Mexico_City"
        - name: TZ
          value: "America/Mexico_City"
        envFrom:
        - secretRef:
            name: n8n-secrets
        ports:
        - containerPort: 5678
          name: n8n
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 5678
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data