apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: n8n-secrets
          stringData:
            N8N_LICENSE_ACTIVATION_KEY: ENC[AES256_GCM,data:/xtocuUC0zvwL9vkxgnN4CKZsqVG6DyPxz8Jv2iAFiEB0O2D,iv:hF78+jRMXol2AqRhQaYXpspaYgj30JjhZfGtJQoScs4=,tag:KUOEGnYZwSxChiferE2s7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTzNEWHVMMnl2S3JQWkps
            dzFMdmI2eFh3T3NNVWJwdW50WGFrWVJHdGhrClhXdnNSRlVQTUFOaURKa1MzVzQ0
            SXBZTytycGxTbFZaRjdJTmt2eHVsc0kKLS0tIElQeXpSeHN3SkhwNmU0ZWFiSlRL
            elFYMUJsTGJ1eVVVb1BzM0plazdsVkUKZgIJmE6/BjBzkWbockvz4rt4kJu16zcv
            yfUIHgdwZ8Pf8PBnAfYGKda+Y3QEIS2xgdOpq+d9r1yT/ipgj8QX/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T05:51:59Z"
    mac: ENC[AES256_GCM,data:k4Ha94W0bMuKzfo5L6WUQmdAJiMTMRJ49Af+mGv9HKKdyyQzsdLfYqwAHOan2NMSMcTNKiwRw6I7o6Uu3njd2kvchluWjMukRSZqp/dTe6jQ67CKz6Jw6GwYZPh7/U1d+GgUPj2M6PJ4peOay84OrVYkvIABuGlfY19oms8TbRc=,iv:zEWDYnrBvFUzsZteDSU7Ofh99Imw+sYj+6q6OT/6yEs=,tag:VmAQMangadrYGbwtMxcvBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
