apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samba-server
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: true
    nginx.org/mergeable-ingress-type: "minion"
spec:
  tls:
    - hosts:
        - samba.elposhox.dev
  ingressClassName: nginx
  rules:
  - host: 'samba.elposhox.dev'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: samba-server
              port:
                number: 445