apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: samba-server
  namespace: sambda
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`samba.elposhox.dev`)
    services:
    - kind: Service
      name: samba-server
      port: 445

