apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: samba-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: samba-credentials
          stringData:
            username: ENC[AES256_GCM,data:LQwOmtmP,iv:PbiWWkNADnsRpNyzsOlUB8xkuVRrRrbOBJHk0Uxc8oE=,tag:SWrDNz6XFjUjFAYTjlWigQ==,type:str]
            password: ENC[AES256_GCM,data:ONOkw70afPWnmoJ+q2MnSxvpcstYrtHW9Ywr8H2fXug=,iv:bY0l5uBepRbT5jw+o2+mzgtSUpI+UwExrYCy0WmBVfc=,tag:0uqP23ZYkPLAcG5DnPhULQ==,type:str]
            fulluser: ENC[AES256_GCM,data:z2Pcf3yAQjPZMfxqxqysqqXkf0AEcHLWqLT6qO8p2E2w9Hc4H1eW,iv:EA0khkjde40rsCQ/lGl+mm3wxJbYvezVlEvlKPFBF9c=,tag:knmtMDe8oOwV8V1psQ2VvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZFRQdFkvZnhKeXlVcDVE
            WWorTEhadm1zb3BQMjZTU3AzYng3SDJVRTIwCitmUW4xakNQYWk5MlhTWkhLODND
            U0U2dXlYWlJ2WTQ2S1R6dVIzK0RpM0EKLS0tIC9HVlBNNFJZazE3WVByUENrcU9O
            WXdYbUpTZ3VKY3VDUXJNazFOa0JwWjQKJUPLKls2gaHcwS19/tr0Ihuw+YnslN/0
            qpZJP3lSVMycs6IjLrEShqEMA1hV4UMlaDdR24ibrLngaqHGt5XXcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T01:22:53Z"
    mac: ENC[AES256_GCM,data:jjgCl7M1A0v4G8B1F2wNblgSYhkLUKbGj+wNKB7+2mBq9jxnmEYYA7I1zjrCcM20qsFASsjPVDx0iDtOlchx4lvrDeH8EKl+l+L5vs6Wn1AEfC7pN7jdRbXMaLVRSvQCL/mb6evM00/heOua72HgyTnheE6lWRuNdTBgXh4yVQ4=,iv:kyzC/nv9HXRbsNyt74X2IXEb4UrCIMLiWAuZDHCoSuM=,tag:VqXIEVS9CdLYaWQIqSd+6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
