apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: samba-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: samba-credentials
          stringData:
            username: ENC[AES256_GCM,data:gDJNHUYT,iv:hwyfF8zlJsS2sum8LrAhpPBJcEeXRpL2nvMwp//WPPk=,tag:lfWorZn7O6cCbBWd95O1Sg==,type:str]
            password: ENC[AES256_GCM,data:KMU52tNVpUS9dvZDhSPMZeY=,iv:f+Cp4T0Mpvmt633WE8sHVkJBqjQ7wgJSSdFafsgEpZg=,tag:WFGrxmyj9xT43VkZP3DzbA==,type:str]
            fulluser: ENC[AES256_GCM,data:xGhIbexshlAl9vlqnmrv/WRY8ZZsAI5B,iv:mw1eynpOefO+czshNovKt4otat/nw/Xh7LFPUvo5MKU=,tag:gBF61NodP9fZficwdPVcBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1unhax45cm95ngm2h984sq22v7uxm7rtle8mlrg4mfgs55t2kr57qxkxyml
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TzY1ZFF1b2hMZi84V1ZU
            Z3psRkllV05jZkRGL2ZwQVdPWUZJOTVIOTFzClN3cVlXTG1wOGlMUk94Yk84RFVt
            eE1yMDRtYjVwMG5KTlZxckRQUTVIT3cKLS0tIDIzalRWV3ZxcGwwc0JHL0YvUXQ2
            eEE2M0FoS3N6eDRRTEZrRGFoLzgvd28K+zg0orGySdKIPjIrmWovWX7mVlFM+5ux
            HNUQ7AmizgdmFUMkSiRV8skqyeQbuvMgvXccVXKlv45eaeyF9JMicg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T05:21:22Z"
    mac: ENC[AES256_GCM,data:VPq0rCrZgYfufB2aEstR+GFTPQKV4U3qR7+ezgiv2gjhmUTDPff22Ghdf/vd4WZ0LgFAmwDvtkg9AOQvUUcD1weEAJwyah7Z+ANXtE2QwkuYWWEFWyZpB04z7v7FDafTfWDHHRbYgEt4fwrqwH8NjhrkwDgniXZ4jvupFqeyKIg=,iv:66/aBFufEFJaHIEWK5GXFXf/dSR3hm8JMu1H9GcTW/Y=,tag:Mv71wSG9lgQKqgdChz/oAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.4