apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: samba-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: samba-credentials
          stringData:
            username: ENC[AES256_GCM,data:9FzgQ0C1,iv:ItEYCKy0zhAp6H5rHz89HfLZgaiPbUTsyOjyveL2RS0=,tag:n6bxwdy0K5AF5pOFk9KYsQ==,type:str]
            password: ENC[AES256_GCM,data:y1hCiUGgS9YeabRfdFylNezhooDjSzAwwJXjudy/SYU=,iv:mbOW7zMNBZi81q7aw/ByKYQTslkpK7ArjbueakD0wBU=,tag:Z1m1RGYXmfZBfFcItENWxA==,type:str]
            fulluser: ENC[AES256_GCM,data:D0PQUPXyDAFdgeyHlxCqpoqKP5of3N1uWbPW4iaJGzyV8CEm0v+n,iv:KLIrJ1THGt0+xQMdIeqjJbfdEvQdvnICgMZH3gkAiOI=,tag:Z520d2usED4u9ZHQGCRNMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TVBIWEQ0QWVWNXZLeCto
            QjVqOEt6UFRpMXhhbTlWbkdlK3EzNkQ4S0RzCjdza3FFbkFmb3FYdGhqVVAycGtj
            OHFyVXdxZzFNb3RFaWpBb09BaUZ6TnMKLS0tIDUxUGVSNDRSUzJOeGZ0eURPN0g5
            RFdOYzdpSWlhdUtCczdZOUhRQndqRFkKhyzNA9vgl/MDEa7++I8OxD/1ZGKDJ/PU
            DcmT3fTyamWMoAewWyzJaPtMoarlGxSlK7krlzIo5e45mqd62Q1/Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T01:12:07Z"
    mac: ENC[AES256_GCM,data:TaQRZh08cgbILx/Nd72SIqeRVO8Ij1xAcxdARYhjhJ6NaW+Mh225Rh4Nkm9IxDVmnWfrqU8CqJrlvHCYQuk4cCDHb6wl3Rdm5xbarYmFulBhO4QjpObNdsKrPbCW0NeArSfFjaFbnDYmTzfaRec0PDN6lN10gFUhfoAa1tQdNQU=,iv:RKraSIy/6hxf1SvDcnBjYCVVC19CbgtC1erp5dAGQ7Y=,tag:/73r56F8outI3bgiKmCYOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
