apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply labels to all resources
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: kube-state-metrics
      homelab.local/OwnedBy: ElPoshoX

# Namespace for all resources
namespace: kube-system

# Explicit namespace with ArgoCD prune protection
resources:
  - namespace.yaml

# Helm chart as a resource
# Official Kube State Metrics Helm repository: https://prometheus-community.github.io/helm-charts
helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-state-metrics
    valuesFile: values.yaml
    namespace: kube-system
