apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply labels to all resources
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: kube-state-metrics
      homelab.local/OwnedBy: ElPoshoX

# Namespace for all resources
namespace: kube-system

# Helm chart as a resource
# Official Kube State Metrics Helm repository: https://prometheus-community.github.io/helm-charts
helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-state-metrics
    version: "7.2.2"
    valuesFile: values.yaml
    namespace: kube-system

# Override chart defaults to match existing cluster state
patches:
  - target:
      kind: Deployment
      name: kube-state-metrics
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
      - op: replace
        path: /spec/template/spec/hostNetwork
        value: false
      - op: replace
        path: /spec/template/spec/securityContext
        value:
          fsGroup: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
      - op: add
        path: /spec/revisionHistoryLimit
        value: 1
