apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: meridian-secrets
    namespace: aegis-meridian
spec:
    suspend: false
    secretTemplates:
        - name: meridian-secrets
          stringData:
            MERIDIAN_API_KEY: ENC[AES256_GCM,data:m46LeXTGZRmKna28u28mjCBPlNxHSFzzL11FR0vqypAg/B9RL2VaEQoftoJMmyGI,iv:qxsoyrRCF/L9+k19znm1UaMCIWg3ChhDrbH9vPD384w=,tag:3xFVDGYpxH5CY0v2w7S3jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q21KQW1uY0lyL3FrZEY5
            TVRNNHZFc29pbWhLbjFEZlVvaEdaKzZXOVNvClNVUWloeGlUa3dCRVlwSVQrRUgy
            dlllRncrQ3Rya0dpSDJiUHNzekpXMjgKLS0tIGVhNXJONktHT2I4SUVxR0xpNzVT
            SXQzN2doTFpnWnBzc1doaS96WDFJUUkKj6TlFxhLrDpJ51jpZAGflgTi3jwzlzwm
            LV5QwPssUt+AO9/x4xqG3e4sS5mtfWDvcqN6V1h4NWsONt383X933A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-13T02:12:35Z"
    mac: ENC[AES256_GCM,data:99dIl1GmrhhPXcQ0QIicihsgkDQ60ge26nQju1l36USe93DXIEoBKh+0J5ncatRkTHtjrDH0bsvaAngOzqa421Plqqzl2JzFqsmau5AQ4wEKB2vnBdLLpYZb3YvKD0X/ZI5uXMch/vGqPC2xL9CdzT/d4H0sGWzjYwh3bgHvuWw=,iv:CiKQMaB0DBmuy4HKh6ChGfQk201U9vIe+h3DP4IrWhw=,tag:vr77t2eFpp4+lxww8kl4FA==,type:str]
    version: 3.13.0
