apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-sync-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: adguard-sync-secret
          stringData:
            ORIGIN_URL: ENC[AES256_GCM,data:QwATuTBlBK3/6rxNgCoirX42E07tSGln0PbaCtBclPxjmN40,iv:zCzT/OxKEAG7YMDYH1VeN+UTTzScgl66ni+dF5o2/Ng=,tag:pP4pIKgSXIE8FqeAT4iUZA==,type:str]
            ORIGIN_USERNAME: ENC[AES256_GCM,data:ewGrOXBQ,iv:Am1nLy7JuFvwUDqeooTl2xBhqyVJI+gzmxGaM8WiSgI=,tag:M0n7BRHF6LU8f+VGoAQoPw==,type:str]
            ORIGIN_PASSWORD: ENC[AES256_GCM,data:Iu0l5BLwgqRqgHNQTtyfLko1mwfm5IIy1ELklsc2JqfPPhHFfFESEKr1wiO+,iv:OmaqaMAQ+JXNB8Am2kSmNhtO54XX5EyGk5AEfmlRt6A=,tag:z2IyrOzIME9xqcE4bFHkkQ==,type:str]
            REPLICA1_URL: ENC[AES256_GCM,data:BHa9JQMUjmY1UTo5Kef4TH5MQV/ks8RnhJ9o0tNhjPM7aVWVk4esyTBFVJhr0w==,iv:HO3bzJwcUYYA0vL/m88XutEa0kuFIOPm3zrRCc+N/SQ=,tag:2fXzNUAVIvrnq38zVQu9jQ==,type:str]
            REPLICA1_USERNAME: ENC[AES256_GCM,data:/CSna/Jr,iv:FtB6cqj+SeeCqOjZSl8ezrJyyM9KQ3pTELjmcvBfbMk=,tag:QfY7dlWpZdpqS8dTe+3McQ==,type:str]
            REPLICA1_PASSWORD: ENC[AES256_GCM,data:q265EiR8/T6BXt4B1rGJphmFZB2Ez2BoYjRIPAW9a1J0Lh8Dn6cGuG08PwCO,iv:r56fHBjhgbGTcufg+IIl0bDKBTaBQgqswjJ2bNlppqI=,tag:gswGxB4M75DDlclb1plXbw==,type:str]
            REPLICA2_URL: ENC[AES256_GCM,data:m0cFH2Yuz3OBzJJA9ZlQNGlNDWfOWo9FpmaZKJ9UgikqrPT5JrrwR8V8,iv:35bqu3Bak7GOqEIJac08owlcPIQoqX91hs9qhuAJ/eY=,tag:B15RYOQIvfFJ/XAT+OKhcQ==,type:str]
            REPLICA2_USERNAME: ENC[AES256_GCM,data:VG7mFmR+,iv:iaSmJRdA3REfxU0SbqDbeo5u6tunhup2Roaj7G47vjM=,tag:VNz5SqemMj+a7NBW5xHBJg==,type:str]
            REPLICA2_PASSWORD: ENC[AES256_GCM,data:RFzsQ7KHpYAjS9SagJTY2//yRTRuEBan7nQzDu0C7XfkQu8C2krurtAITRrG,iv:Hrpnyw4TdQycXTqCsBCAtEbOZBFpQm3+LAVdjiUMquQ=,tag:M7o09l4PcWdP/IkI5NSeSw==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaUxqaXlJWnRMaXdXSnZp
            UzlyT2Z0T0dHSGNUTWJ6dEs0U1hnYlB5S0RZCkNTRWhHS2pPQ2VsZVN1UXF2REtZ
            eVU0L0FINktpZDZSZWdpck5oQ3Jzc00KLS0tIG5VdGE1VTdoYklBdVhPNHBWUmhC
            dmsralZmMXU2WnJWVVFkbmhiWXBpRk0Kf0d8aoI2BgnhvDHa3mOAcNtg5ZsjjTCI
            HPK2OPf6e16XB4/OzFOOFpFrnBPC+FFshwb1d3xb1QBFSry7wkviSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T23:41:04Z"
    mac: ENC[AES256_GCM,data:odOtK2GePTzLDXvDcxo7/g2WqsD8rElAh6cba2Onge/MpXmaDUaFgNmjMVws06HuovvQ/J9tyeD94sZEd74+ntZiNoCOcPorMv2dTmYlThsezBOe1GFZYluz8KXvPMCaBnwyoYQ8PbLWqVWlvhRxcktNzF5xRIqG6s2hJ5fCnhg=,iv:pAOAMsQEJgjBdUHGyThZljhsL3ia9+Kyw/9kxkfPEOY=,tag:g/+EvGoul6w+2WzTVvPZIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
