apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-sync-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: adguard-sync-secret
          stringData:
            ORIGIN_URL: ENC[AES256_GCM,data:rmjABwl5tqO+vehZ5RJvBXo5n0e/QwqcKsxQwRZLcQQcGyxL,iv:y6Mv9aMfJEwXXrpxJyqRAGBghxLETa4lPZ49SzNbW5o=,tag:lqEFYvsf/7cc4wJtyPgpjg==,type:str]
            ORIGIN_USERNAME: ENC[AES256_GCM,data:Alw7+ybe,iv:sEtedY0musRSyKVpo34P+n8ORucTslcmDDc7s2r6Cy4=,tag:e8YsQYZbIL6JvIoPHuaS3g==,type:str]
            ORIGIN_PASSWORD: ENC[AES256_GCM,data:nYAwW9Eh/lbQjGLWzSRNO4To5tREmNxtjGIBdc06qO43X0gZtAmXLnUOeHPY,iv:sPQzc/j6L6vGo+l05GCW8FXkwmWxKYF/+g1CtWF1oHY=,tag:kcDjuMcQLVh0mfZcZs/qcw==,type:str]
            REPLICA1_URL: ENC[AES256_GCM,data:hcmTNe4GYbBlubDToT4OFAXK,iv:pk/0GRfviGEr16dUTuqMQFOInFKbn2Vyd0mHT3r8KFY=,tag:RhIyiN+UATNBfLU9d+kMiA==,type:str]
            REPLICA1_USERNAME: ENC[AES256_GCM,data:2p6GuNKa,iv:1UNjYAWc72OgEo5dZJsTb7Bul9Qj+ZezmcWWe/9SyyU=,tag:ltLVOO1s5tQKwXM3ebVhdg==,type:str]
            REPLICA1_PASSWORD: ENC[AES256_GCM,data:/V5M/vIt9GjHIr3pC7QP+f0grnlT9z0CWtA3HzCUKKHyg6/aFfZYtlT3viQZ,iv:OzswhK2sc7jf3syMyJ4iExtbSNS5PpQoHptq/Hlg4GU=,tag:l+ImTqzGhfkqEiE32tFYtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMkZrMFBaU29tSTRjZkRN
            S3lKYmFZcU5UUHoreDhOeldOUDVCOU9jK1JnCmR1bWZTem82U0dVcmY2a0xoamxD
            VHFyY1M5cXRITTNkUVFKUmVXSXJRV28KLS0tIFpOMFV2Tlh0d3FaSmVacW9FMmFY
            d0Y5TG8rRTZOdXdSM1BoRVkvdE9JdXcKkqU58FGHsPcquWNzryvKDFddKhhhr//f
            /FwYPT16xvka9OeKwvcKM7De9j7YJqhwSozWnZKgCxM5evUbAAOkGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T03:06:15Z"
    mac: ENC[AES256_GCM,data:e2Ynre2BoyLvqQi9QqJqGVpSZpo0/dwCx70NW0GyJeTA0LwFra2f9gKmtRA5p7INiSpQOV/r0c9NSZg2WjUYz8q7a2MXi+zFoF8nHzbltsBk5uLTp2DDV1dK/pSHRwZzR//1Q6P05KJ7TUOeoSoSmnZ9S3tRnDYEsYWvYAcLIfQ=,iv:zmAFO4Ro9cj+pQgRr6BIJYYdHwVto0N6oK3nbk9XpgY=,tag:+CaR+X/ll3lE397AV7rmWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
