apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-sync-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: adguard-sync-secret
          stringData:
            ORIGIN_URL: https://adguard-primary.elposhox.dev
            ORIGIN_USERNAME: poshox
            ORIGIN_PASSWORD: E5@^P$ocQYE!n39Ta^77D1%ukouEHB!P8Y*8F49KU#@5h
            REPLICA1_URL: https://adguard-secondary-truenas.elposhox.dev
            REPLICA1_USERNAME: poshox
            REPLICA1_PASSWORD: E5@^P$ocQYE!n39Ta^77D1%ukouEHB!P8Y*8F49KU#@5h
