apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-sync-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: adguard-sync-secret
          stringData:
            ORIGIN_URL: ENC[AES256_GCM,data:4+t6ZKqvbRhR9mCT4TYesMj++/u6hLYq05UKS9T0dx692yG0,iv:bjadOtL5DiojF94SuXTjwZHkDQuX0gk6s+AyVWL6SM0=,tag:dedMS92TCeP2Zg3ClGC6wA==,type:str]
            ORIGIN_USERNAME: ENC[AES256_GCM,data:K5RN6N77,iv:QDGqwWo05JP1cSJFjHR7g7LoGNAlp2ZiAzYGKAScpXQ=,tag:aq3Lj3H8TbOUxzIhgohq6Q==,type:str]
            ORIGIN_PASSWORD: ENC[AES256_GCM,data:cnxi9W5A5O3mPzQH/MDuo5QH+zWMbee8JhnMTrJSlbZ3hjsrWTTDSUSgvuQe,iv:l2m2apm9SLrjqCXnu/GobDk24Q4z3iurihAh/DKzf2M=,tag:875C4Wca1dJyfZttbGG30g==,type:str]
            REPLICA1_URL: ENC[AES256_GCM,data:p4yHHBnCr4/CKF3GKGnbkfwvfU4CM4hWKSvEZ+YnRecE5hdRhYPEuaKsMgTq+A==,iv:L0Nw0Z4JaciZuLMhoHgCoF44g7RhHDdFrjPBoRvdHoQ=,tag:jkpUJkO7OR3zfvKBhv65qQ==,type:str]
            REPLICA1_USERNAME: ENC[AES256_GCM,data:EA7shx/f,iv:cJ/65SWimx0ZkBi74yEk8yOAb/ob0/vMxTQ+t44nTCw=,tag:/7ryoKgr4UiY3pzG6zoo9Q==,type:str]
            REPLICA1_PASSWORD: ENC[AES256_GCM,data:lHEmiQWXpz/547CHzsCSy+j95DZuw133ONaEV7ObdfESQzaH0hBkDPVytNrz,iv:iDJ0xTVUCLLLLDl3/VDiG9taunGC6ioED7uKLso7gzg=,tag:qpUJ6fMneBu1yVm4vlHtnA==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhak9GUkZaVjNmVzYvSUpw
            Zk45NVB3eVN0S0M0OWZxdjNBMU5oS2xkNmpJCmJVNHVPYWlFbnZNT1puVWFSMnAz
            VWtGSFF3V0JHeHhRbXVvZWhhZGMyZ0UKLS0tIHM0L0QvUys4K1o5V1FEYlZnZzdK
            UjNsVTJacXZxdVE1L2R3M2lkd25zRVUKO0jkZukaxxrOeXrZ2y6bcHXJ/FhgHMa6
            7yMNec383OmDNQu4AEXrdgBeeInWX12a4zLRRvpaI0pcbGU5AeOFZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T20:45:54Z"
    mac: ENC[AES256_GCM,data:DnFV27o8/3cLh//030YfQVu+HxQdX3VRnwjvuIGwF3UT7xpVtmjpe7bcZpy+nl3iK27qZg0tFp1IP+xFo0YDUrptc19fTCjlZh85/6sG8ojCYJKfqCcIedKIgSZd+AVLO5zN0dVE8f6eGSIvLHm9OD4WRERuXknHw3N47VPFhs0=,iv:grOrFvH5P5OKxI799jXaU17H4HR5x2b11r2hVZDXQ1Y=,tag:TI/FL7wJ6MmyfgEKqeUekw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
