apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-sync-secrets
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: adguard-sync-secret
          stringData:
            ORIGIN_URL: ENC[AES256_GCM,data:SqP1si/T+04pfeVCsyveik4uqpHd19bb2k5hjl22/OQzs2CJ,iv:bpmBZvpBiTRZvt4F79oN80VcWzze+unoxMqI4ZYezic=,tag:qhXSvM0Lb44aG558H86r7g==,type:str]
            ORIGIN_USERNAME: ENC[AES256_GCM,data:FgcPuNvC,iv:1ei6zR1scgiHStFn785gsCm5FpxoylbwrvIC108EruI=,tag:niuyqzqkI2u21oZ5T6UDpQ==,type:str]
            ORIGIN_PASSWORD: ENC[AES256_GCM,data:+yaWUR8I7tsHX/3S1w8pywTwc97pPy0ax3URER8XwrBqw6eBTsTmaf2Oq1tA,iv:ERQVPUf+cNRvjDAjjL65Zd+iMM7k08C/rNSzameSuJo=,tag:yThsSvcys6UKbHLLRcnqDA==,type:str]
            REPLICA1_URL: ENC[AES256_GCM,data:oCJmycbwoCl/n0QFrVdyX+zjdZwzPMbQVNIJ/1Gz/rIcgmT0p1Pf9Q4VHj7Ycw==,iv:f8bRFUNu0mHjIxf3ffnVoOBiwAk1XDWGI58fl1CecoQ=,tag:wPVk3OhcawW9OmfmSXDtrQ==,type:str]
            REPLICA1_USERNAME: ENC[AES256_GCM,data:9Phg+m8/,iv:hYJfuFzA40IB5yy7iqEusn/xld5Jxx9T0EXvtVBTGzQ=,tag:vgLw4mC+SvgpPNM6E3R/2w==,type:str]
            REPLICA1_PASSWORD: ENC[AES256_GCM,data:nl/31Ihuu4lFCTHPixLvDxcOR4ub6yJLuh9ZU7t43MbNlH3kbw65dTgqBLGt,iv:Ap+7BOvMMNLXqFrZJzWUrZf1xqUxid4x0LmW5msc8Xc=,tag:tDZ9W80o4GMPwV4+2gBylw==,type:str]
            REPLICA2_URL: ENC[AES256_GCM,data:On5VdWihGGbY5hGQ2Xk4AQcX4JZow858HUsZA/EZeTWOZxICYipqHZ4P,iv:82wlHMHRYz9Rw3ARILMBYqcvSAILzRgSzTvGkrwWqIo=,tag:BJhXEpdOjtdQQz/Pt34OVA==,type:str]
            REPLICA2_USERNAME: ENC[AES256_GCM,data:TwkuAxMr,iv:GaSj34UQjkeP2Kvyt+MGiIM8IUyCovGa7IJy/qHpFvg=,tag:dNNlxGJPV9g/L0gecUmpAg==,type:str]
            REPLICA2_PASSWORD: ENC[AES256_GCM,data:APi3a0sCm4YGHpsCTWwwUL27494f4wd2Cblq9a9GZqQ+PAvABsbHXfJlYAfT,iv:tki2OWJ6NJhsPqaWGsbWdLhNBRRrcPHPmeADxmuYPPw=,tag:N2xd1c6K6XtsqKMcnNzlJA==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMXorbGJvWmIySG8vTE9r
            bmJ0UjAwU0dmMGlES0dXZ1k1MWd0ejZtbndFClE4SFRKeDBSdGQ3NnN0cEpodmd2
            Wmp1aUtsRllMdFlIV2xtQnN1dkNTN1UKLS0tIFdXS2xIZU9JTDJqd3dZWnVsbmpj
            RUNkMVlKRUhpTmQvYXZscE92N3k5c28Kuni4GHGpxkN777KiXv/frHvZoiGGT+yh
            Mbu6snoMFPo4xQ93psogKECiJXJ6B8oESeQrcx4/vARKPekqtkBXcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T01:18:49Z"
    mac: ENC[AES256_GCM,data:nLT7LwGxVHKOnprqabbezSayUm9eOqbICFWjxxjmm7xD1aWnwhpaqCWNofkIuzGijyNqccK6Gw6fjr8LtDfHRKqHr+3muqb9razEEgUJ02ZOhKra/eME65DSozLwtFL0AAHkrU9FJuqjBmJtMiJmGJuSZT1p4H9aB1FdQhsOFOk=,iv:9Dsh29RYm3RoJoaLR77u13ZGR6jxeG+KbIUmIAucGCg=,tag:mGhaLf59I4vXNid8WvlsMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
