apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/elposhox/officina
    newTag: "ec3947ebad7e3055d712c212cbda46e45b649c4f"
    digest: 
