apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: homepage-secret
          stringData:
            HOMEPAGE_VAR_ADGUARD_USER: poshox
            HOMEPAGE_VAR_ADGUARD_PASS: E5@^P$ocQYE!n39Ta^77D1%ukouEHB!P8Y*8F49KU#@5h
            HOMEPAGE_VAR_ARGOCD_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJob21lcGFnZTphcGlLZXkiLCJuYmYiOjE3NjIwNDQ5NjksImlhdCI6MTc2MjA0NDk2OSwianRpIjoiYWY5NmU3OGEtMmYzZC00YTY1LWEyYzItNmFlMGI4MzBmOTgzIn0.1jCoXkgUZJLMdvIIeie4soV3yLnYQpvSVTpSlR3hJxQ
            HOMEPAGE_VAR_HOMEASSISTANT_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5ZGYzN2E3MjE5NDE0MWI1ODk2MmZjMjEyYjc1ZDdiZSIsImlhdCI6MTc0MTMyMzMyNSwiZXhwIjoyMDU2NjgzMzI1fQ.o5MOooGbd-FAoNEzDs8esRRbJ9plEkoa4wwwq8m_zkk
            HOMEPAGE_VAR_JELLYSEERR_KEY: MTc0MjUzODk4MDc4OGI1MmU5ODQyLWEwOGUtNDdiNC1hODZhLTg3MmE3ODE1OWQxYQ==
            HOMEPAGE_VAR_JELLYFIN_KEY: e10fda7eff74414e8b08ea3c0b77e9a3
            HOMEPAGE_VAR_SONARR_KEY: 2bf6d8c7fb084a11ac184fc62d5eb3f6
            HOMEPAGE_VAR_RADARR_KEY: 997503078f0d4b7f9397259ec7cea060
            HOMEPAGE_VAR_BAZARR_KEY: aaeccbd38ba64cc5f1c7178d2bf55d7b
            HOMEPAGE_VAR_PROWLARR_KEY: 1e481784b52d4f3a9d98801889b3c8f8
            HOMEPAGE_VAR_IMMICH_KEY: hol7uu8BWKTlBhM4KusfD9XGhzWGD6qHz9Zyb7Rw
            HOMEPAGE_VAR_UNIFI_USER: Homepage
            HOMEPAGE_VAR_UNIFI_PASS: wX5ycrZP0^nZ8#6$kZqPFh#R2Y^l3W9H
            HOMEPAGE_VAR_TRUENAS_KEY: 1-DfEGzGM8pPkq3VoqmY8p9Djtzvyz6DAPU61Jdse2WZCcoU5aUAPaONPwjCBJsTRa
